### ISSUE TITLE
smoothed AutoRotationComponent rotates backwards if you keep turning

### ISSUE THREAD

**Issue by OLedelay** [AlmasB/FXGL#1003]
**Describe the bug**
AutoRotationComponent with smoothing rotates the wrong way around when the entity keeps turning clockwise or counterclockwise.

**To Reproduce**
Implement a player entity with WASD controls and an AutoRotationComponent withSmoothing (preferably also a sprite that allows you to see your orientation)
Run in small circles with WASD
Watch as the player rotates the wrong way around after a few rotations.

**Expected behavior**
The player keeps rotating in the same direction.

**Runtime info:**
 - OS and version: Windows 10 version 10.0
 - FXGL-11.14 (01.03.2021 16.59) on WINDOWS (J:15.0.2 FX:15)

**Additional context / possible fixes**
I've found the source of the problem and a solution: 
In onUpdate() in AutoRotationComponent.kt, a choice is made between 3 target angles, to select the one nearest to the previous angle. Because of this, the resulting angle is allowed to drift up or down (depending on the direction you're turning), out of the range that is corrected for.
My solution is to instead alter the previous angle to be close to the angle you want. This way the resulting angle is always converging to an angle between 0-360 degrees and you don't get funky rotations anymore.
I've implemented this change locally through a Java class I named [AlternativeAutoRotationComponent](https://github.com/AlmasB/FXGL/files/6292425/AlternativeAutoRotationComponent.txt) and it solved the problem for me.

Note: Thanks again for making this project open-source, because of that I was able to solve the problem for myself.

**Comment by OLedelay** [comment]
Optionally, it's also possible to incorporate the `double tpf` from `onUpdate(double tpf)` in the calculation for how much to rotate, to make behaviour more consistent across different framerates. 
Then instead of `0.9*oldAngle + 0.1*newAngle` it could be `oldAngle * Math.max(0, 1 - rotationalSpeed * tpf) + newAngle * Math.min(1, rotationalSpeed * tpf)` with a parameterized rotationalSpeed. (It could be set to 6 to end up with 0.1 at 60fps as before.)

I also wanted to make it so that it doesn't just hop back to the default orientation when the entity stops moving, but I haven't found a very clean way to do that yet. Right now I just have 
```
if(Math.sqrt(Math.pow(prevX - currentX, 2) + Math.pow(prevY - currentY, 2)) > 0.001){
    prevX = currentX;
    prevY = currentY;
}
``` 

But both these things are outside the scope of the aforementioned issue.

**Comment by AlmasB** [comment]
Thanks for raising this and the proposed fixes, I'll take a look

**Comment by OLedelay** [comment]
I've just been trying to implement something of this sort but using a PhysicsComponent instead of a TransformComponent, and stumbled upon a different solution (still a WIP) which is to allow the drifting to happen and give newAngle the same offset in rotations as oldAngle, and choose newAngle from the 3 angles surrounding that offset newAngle
Example: 
oldAngle is 750 degrees, targetAngle is -170 degrees
oldAngleOffset is 2 full rotations, so 720 degrees [FXGLMath.floor((oldAngle-targetAngle)/360)]
targetAngle = -170 + 720 = 550
choosing between equivalent angles, the closest targetAngle is 910 degrees (with a distance of 160)

For a dynamic PhysicsComponent I can't just set the angle to whatever I like, so instead of setting the angle I adjust the angle by adding some angular velocity, relying on angular damping to keep the player from spinning out of control.

I'm going to have to find a good way to work around the fact that PhysicsComponent rounds the X and Y locations.

**Comment by OLedelay** [comment]
I've finished the PhysicsComponent-based version, here it is: [PhysicsAutoRotationComponent](https://github.com/AlmasB/FXGL/files/6336656/PhysicsAutoRotationComponent.txt)

The different solution is implemented now.
There's still a little bit of wobble at low velocities, but that's an unavoidable consequence of the snap grid PhysicsComponent uses. 
My workaround is that half the coordinates used to calculate the desired angle are only updated if the current coordinates are 5 pixels or more away from the previous coordinates.

EDIT; refactored code to make it more readable, fixed a bug, added reduction of mass to 0.1f to make rotation-induced bounces less dramatic.

**Comment by OLedelay** [comment]
PhysicsAutoRotationComponent works best with a circular hitbox, otherwise the edges of your hitbox can snag on other things and launch you off them due to your rotational inertia and slow-to-change target angle.

**Comment by AlmasB** [comment]
I've reproduced the issue and working to write a test for it.

**Comment by AlmasB** [comment]
I've added a test to cover this edge case and fixed the behaviour based on your proposed approach (keep the angle within a specified range). Please can you check this works correctly for your use case. Many thanks for identifying and proposing a fix for this.

To get the latest build, you can use this:
```
<dependencies>
    <dependency>
        <groupId>com.github.almasb</groupId>
        <artifactId>fxgl</artifactId>
        <version>dev-SNAPSHOT</version>
    </dependency>
</dependencies>

<repositories>
    <repository>
        <id>oss.sonatype.org-snapshot</id>
        <url>http://oss.sonatype.org/content/repositories/snapshots</url>
    </repository>
</repositories>
```
