### ISSUE TITLE
Allow user to set global cursor / default cursor

### ISSUE THREAD

**Issue by chengenzhao** [AlmasB/FXGL#1023]
**Please discuss the feature ideas on [Gitter](https://gitter.im/AlmasB/FXGL) first. Then please describe the feature**
Allow users to set global cursor e.g. in initSettings method of GameApplication 
users may use settings.setCursor(Cursor cursor) to set the global cursor

**Describe alternatives you've considered (optional)**
set cursor in all scenes
StartupScene, IntroScene, LoadingScene, GameScene etc.

**Comment by AlmasB** [comment]
Thanks, `initSettings()` is called before JavaFX is initialized, so it will probably be something along these lines:

```
settings.setCursor(new LazyValue(() -> ...));
```

The default cursors may not need this, but in general users may want to use something like this:

```
settings.setCursor(new LazyValue(() -> new ImageCursor(FXGL.image("..."))));
```

which will need both FXGL and JavaFX to be initialized

**Comment by AlmasB** [comment]
Closed by [commit](https://github.com/AlmasB/FXGL/commit/d126759275e39b984314673c89a5f6636d03384d)
