### ISSUE TITLE
Make AnimatedTexture use FXGL animation system

### ISSUE THREAD

**Issue by AlmasB** [AlmasB/FXGL#1067]
More discussion [here](https://github.com/AlmasB/FXGL/discussions/1032)

**Comment by chengenzhao** [comment]
Will this feature be available in 11.18 ?

**Comment by AlmasB** [comment]
I've added this to the milestone for now, but I haven't had a chance to properly look at this yet. Will check over the weekend.

**Comment by chengenzhao** [comment]
Is it possible to have a partially animation method, like playTo(int endFrame) method?
and playReverseTo(int endFrame) ?

**Comment by AlmasB** [comment]
@chengenzhao you can define an AnimationChannel that runs to a specific frame. You can play the channel in reverse.
