### ISSUE TITLE
Add embeddedShutdown to decouple fxgl instance from javafx instance

### ISSUE THREAD

**Issue by AlmasB** [AlmasB/FXGL#1075]

**Comment by AlmasB** [comment]
@chengenzhao please check this works as intended, there is a sample attached to the commit to help with the API.

To get the latest build, you can use this:
```
<dependencies>
    <dependency>
        <groupId>com.github.almasb</groupId>
        <artifactId>fxgl</artifactId>
        <version>dev-SNAPSHOT</version>
    </dependency>
</dependencies>

<repositories>
    <repository>
        <id>oss.sonatype.org-snapshot</id>
        <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    </repository>
</repositories>
```

**Comment by chengenzhao** [comment]
@AlmasB Cool 
It works, thanks a lot

**Comment by chengenzhao** [comment]
Hmm...
Interesting thing is it takes some time to start the game 
so if we use embeded start every time, there is a black scene during the start
I tried to set intro scene,  startup scene, loading scene and set background color to fxgl pane but still get the black scene
seems like we need to find a way to custom the scene during the start

**Comment by chengenzhao** [comment]
It would be nice to have a transparent background color by default for embeded mode

**Comment by AlmasB** [comment]
The black comes from the FXGLPane rendering color. There is no public API
to change it at the moment.

Please open a separate issue and it will be fixed.

**Comment by chengenzhao** [comment]
Cool thx
Submitted here
https://github.com/AlmasB/FXGL/issues/1085
