### ISSUE TITLE
--illegal-access=permit is removed from JDK 17 and kotlinc should not need this walkaround  for compilation

### ISSUE THREAD

**Issue by chengenzhao** [AlmasB/FXGL#1084]
**Describe the bug**
In the file .github/workflows/maven.yml, there is a walkaround for kotlinc: --illegal-access=permit
Kotlin 1.5 should not need --illegal-access=permit, 
kotlinc should fix this in 1.5-m1
https://youtrack.jetbrains.com/issue/KT-43704
and --illegal-access=permit is removed from JDK 17 
https://openjdk.java.net/jeps/403
so this environment variable in .github/workflows/maven.yml
 could be error-prone in future?

**Additional context / possible fixes**
Remove this option should work fine for kotlin 1.5.10

**Comment by AlmasB** [comment]
Thanks. Kotlin's incremental compilation appears to be problematic still. Since illegal access workaround is no longer honored, it was removed from 17-ea build and incremental compilation disabled.

Closed by [commit](https://github.com/AlmasB/FXGL/commit/f37eaf40c632e5447094a4975234891e153a24fb)
