### ISSUE TITLE
Allow developers to customize FXGL pane rendering color 

### ISSUE THREAD

**Issue by chengenzhao** [AlmasB/FXGL#1085]
**Please discuss the feature ideas on [Gitter](https://gitter.im/AlmasB/FXGL) first. Then please describe the feature**
Allow developers to customize FXGL pane rendering color 
Currently the default rendering color is black and no public api to change it
so hope we could have a public api allow developers to change it

More discuss:
https://github.com/AlmasB/FXGL/issues/1075

**Comment by AlmasB** [comment]
`pane.setRenderFill( ... )` should do the trick. Let me know if this works, so we can close this.

**Comment by chengenzhao** [comment]
Good Afternoon @AlmasB 
It works
I tried use 
```java
fxglPane.setRenderFill(Color.TRANSPARENT);
```
then the black scene doesn't appear
