### ISSUE TITLE
getInput().mockKeyPress(KeyCode.ESCAPE)) doesn't display Game Menu

### ISSUE THREAD

**Issue by DieterHolz** [AlmasB/FXGL#1088]
**Describe the bug**
Pressing the ESCAPE-Key will display the Game-Menu by default.

When sending a mockKeyPress this doesn't happen. The mockKeyPress is silently ignored.

**To Reproduce**
For example in DropApp (from Template Project) change 

`    @Override
    protected void initPhysics() {
        onCollisionBegin(Type.BUCKET, Type.DROPLET, (bucket, droplet) -> {

            // code in this block is called when there is a collision between Type.BUCKET and Type.DROPLET

            // remove the collided droplet from the game
            droplet.removeFromWorld();

            // play a sound effect located in /resources/assets/sounds/
            play("drop.wav");
            getExecutor().startAsyncFX(() -> getInput().mockKeyPress(KeyCode.ESCAPE));
        });
    }`

Now, when the first drop hits the bucket the game menu should be displayed. Of course this doesn't make any sense. It's just to show the bug.

What I want to achieve is to use a Picade Console as input and mock a FXGL-KeyPress when one of physical buttons is pressed. This works fine for KeyCode.LEFT for example.

**Expected behavior**

**Screenshots**
mockKeyPress(KeyCode.ESCAPE) should trigger the same action as hitting the ESC-key.

**Runtime info(please complete the following information):**
 - I'm using Raspberry Pi OS, 32 bit, but on Mac there's the same issue.

**Comment by AlmasB** [comment]
I've skimmed through the implementation and the menu key (in this case ESC) is an edge case to avoid transition issues. Hence, it is not routed through the same input handling.

To open the game menu (from the game scene), you can call this instead:

```
getExecutor().startAsyncFX(() -> getController().gotoGameMenu());
```
