### ISSUE TITLE
Choice Dialog Button Text

### ISSUE THREAD

**Issue by milimetron** [AlmasB/FXGL#1094]
Make it possible to select the text for choice dialog buttons instead of having to create a custom dialog to replace yes or no

The only other solution i fought of is creating a custom dialog other wise it's stuck with yes or no

**Comment by AlmasB** [comment]
Instead of modifying the confirmation box, I'm thinking we could have a dedicated choice box:

```
public abstract <T> void showChoiceBox(String message, Consumer<T> resultCallback, T... options);
```

The implementation would produce a box with up to 3 buttons and if `options.size > 3`, then produce a ChoiceBox.
