### ISSUE TITLE
Can FXGL be used in conjunction with another game library?

### ISSUE THREAD

**Issue by jfelrod1960** [AlmasB/FXGL#1096]
I would like to use FXGL for the UIs in my game.

Thanks
Jeff

**Comment by AlmasB** [comment]
Hi, if the library is based on JavaFX, then yes. Otherwise, no, since FXGL uses the JavaFX rendering pipeline.

**Comment by jfelrod1960** [comment]
Thanks for replying.  The other library uses OpenGL.
