### ISSUE TITLE
Roll in JavaFX 17 with current version of FXGL that relies on Java 11

### ISSUE THREAD

**Issue by mokun** [AlmasB/FXGL#1107]
Currently v11.17 pulls JavaFX 16 from maven repo.

![image](https://user-images.githubusercontent.com/1168584/134953742-925911d7-df30-4c52-960c-d8f6550a9462.png)

Now that JavaFX 17 (OpenJFX 17) is out, it has quite a bit of fixes and has a newer webkit version. See [1](https://gluonhq.com/products/javafx/openjfx-17-release-notes/) and [2](https://openjfx.io/highlights/17/).

Are there any roadblock in simply adopting JavaFX 17 (to be used with Java 11) ahead of time ? without having to sort out all those potential issues when transitioning from Java 11 to Java 17, which would be more time consuming.

btw, I use Eclipse and Maven as my platform for development and not Gradle. If I roll in JavaFX 17 as a maven artifact at the same time while using FXGL 11.17, Eclipse would complain as having two conflicting libraries and flag it as a problem and I would be unable to import either version of JavaFX (16 or 17) at all. So I can't make Eclipse to choose Java 17. 

Even if I do, I suspect FXGL 11.17's intricate reliance on JavaFX 16 would probably break. I don't know how backward compatible JavaFX 17 is.

**Comment by AlmasB** [comment]
Thanks, happy to upgrade to fx 17, which will be usable with the dev
snapshot version 11+dev-SNAPSHOT

**Comment by AlmasB** [comment]
Once the CI build successfully completes, should be usable via:

```
<dependencies>
    <dependency>
        <groupId>com.github.almasb</groupId>
        <artifactId>fxgl</artifactId>
        <version>11+dev-SNAPSHOT</version>
    </dependency>
</dependencies>

<repositories>
    <repository>
        <id>oss.sonatype.org-snapshot</id>
        <url>http://oss.sonatype.org/content/repositories/snapshots</url>
    </repository>
</repositories>
```
