### ISSUE TITLE
Add support for video cutscenes

### ISSUE THREAD

**Issue by AlmasB** [AlmasB/FXGL#1120]
- [x] Design API (aligned with existing API) for high-level use by developers.
- [x] Possibly add support for loading .mp4 in AssetLoaderService (via JavaFX Media)

The above items should be discussed in this thread before attempting implementation.

**Comment by mukulsethi22** [comment]
Can I work on this issue?

**Comment by AlmasB** [comment]
Sure, go for it. Please provide your design here so we can agree on API

**Comment by mukulsethi22** [comment]
I am new to this, can you provide which files need changes for this and if possible a basic roadmap to solve this issue.
Thanks.
