### ISSUE TITLE
kotlin.UninitializedPropertyAccessException: lateinit property engine has not been initialized

### ISSUE THREAD

**Issue by reflqct** [AlmasB/FXGL#1121]
**Describe the bug**
When attempting to run a game made with FXGL, this error pops up. It says it is housed where I wrote `FXGL.getGameWorld().setEntityFactory(new LevelLoader())`. The code the error is reffering to is as follows, in `FXGL.kt`.

```
private final lateinit var app: com.almasb.fxgl.app.GameApplication 
```

**To Reproduce**
1. Set an entity factory, use reflection in that entity factory or set a tiled map (`FXGL.setLevelFromMap()`)
2. Run

**Expected behavior**
The game runs smoothly, and my tiled level loads.

**Screenshots**
- - - -

**Runtime info(please complete the following information):**
MacOS Big Sur

**Attach log associated with the bug (can be found in "logs/")**
There doesnt seem to be a log file.

**Additional context / possible fixes**
- - - -

**Comment by reflqct** [comment]
Oh, should've also mentioned I'm using Java, and not Kotlin.

**Comment by AlmasB** [comment]
Closed by https://github.com/AlmasB/FXGL/discussions/1124
