### ISSUE TITLE
Add dungeon generator

### ISSUE THREAD

**Issue by AlmasB** [AlmasB/FXGL#1130]
Unlike, maze generation, which is very specific to maze-like layouts, a dungeon provides greater flexibility for exploration and is not meant to be convoluted (like mazes).

@Shylexx to explore this further

First, the API should be proposed from the game developer perspective, then we can discuss implementation details. I suspect it will be along the lines of extending a `Cell` in some way and generating a 2D grid of them...

**Comment by keziah480** [comment]
This challenge would likely have a similar approach to some of the procedural generation I have used in my computing project. 

I will write a solution and discuss it with you in the lab next Monday, before submitting if that's alright.
