### ISSUE TITLE
NotificationService seems not to be affected by setting text and background color.

### ISSUE THREAD

**Issue by ghost** [AlmasB/FXGL#1143]
**Describe the bug**
NotificationService seems to not be affected by setting text-color and background-color properties. Despite being changed before showing up the popup, it looks the same as the default popup with default colors.

**To Reproduce**
I managed to produce this bug by running this code:
```java
public class TestApp extends GameApplication { 
    public static void main(String[] args) throws IOException {
        launch(args);
    }

    @Override
    protected void initInput() {
        onKeyDown(KeyCode.SPACE, () -> {
            final var ns = FXGL.getNotificationService();
            ns.setTextColor(Color.VIOLET);
            ns.setBackgroundColor(Color.BLACK);
            ns.pushNotification("Hello world!");
        });
    }
    
    @Override
    protected void initSettings(GameSettings settings) { }
}
```

**Expected behavior**
I would like to be able to change the colors of the notification.

**Screenshots**
![image](https://user-images.githubusercontent.com/98128117/150429438-991ef7ce-a0dc-410a-985a-58aaacff238a.png)

**Runtime info(please complete the following information):**
Windows 10 and Ubuntu 20.04

**Attach log associated with the bug (can be found in "logs/")**
N/A

**Additional context / possible fixes**
N/A

**Comment by AlmasB** [comment]
Thanks for this, should be fixed now.

To get the latest build, you can use this:
```
<dependencies>
    <dependency>
        <groupId>com.github.almasb</groupId>
        <artifactId>fxgl</artifactId>
        <version>17+dev-SNAPSHOT</version>
    </dependency>
</dependencies>

<repositories>
    <repository>
        <id>oss.sonatype.org-snapshot</id>
        <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    </repository>
</repositories>
```
