### ISSUE TITLE
Viewport improvements

### ISSUE THREAD

**Issue by AlmasB** [AlmasB/FXGL#1168]
> Hi:

> Is there any way to extend effects on viewport?
currently there are only 3 ways of viewport effect: shake, fade and flash which works perfectly nice
and is it possible for developers to create their own viewport effect?
like if the protagonist gets hit the viewport border becomes red and then fade out to warn the player
we read the source code and seems like we have to get the camera first
but camera is the internal variable so it can't be used outside the viewport class
<img width="446" alt="截屏2022-04-09 下午12 23 11" src="https://user-images.githubusercontent.com/5525436/162556126-9b0c40fd-306f-4952-999a-ad394049bafc.png">
is it possible to provide a public method to allow developer to extend the effect then add in the camera view components?

Thanks

_Originally posted by @chengenzhao in https://github.com/AlmasB/FXGL/discussions/1165_

**Comment by chengenzhao** [comment]
This features seems like is a easy modification to make it happened
so will this feature catch up the next release?

**Comment by AlmasB** [comment]
All done, see if it works for you.

To get the latest build, you can use this:
```
<dependencies>
    <dependency>
        <groupId>com.github.almasb</groupId>
        <artifactId>fxgl</artifactId>
        <version>17+dev-SNAPSHOT</version>
    </dependency>
</dependencies>

<repositories>
    <repository>
        <id>oss.sonatype.org-snapshot</id>
        <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    </repository>
</repositories>
```

**Comment by chengenzhao** [comment]
Cool
 It works great
Thanks a lot
<img width="893" alt="截屏2022-07-10 下午1 49 06" src="https://user-images.githubusercontent.com/5525436/178133060-0bde18c4-0219-4514-a623-20e09df9e18b.png">
