### ISSUE TITLE
customLaunch to load an FXGL Application into an FX scene  doesn't work anymore

### ISSUE THREAD

**Issue by benjimusmaximus** [AlmasB/FXGL#1169]
I tried to solve this cunstomLaunch but the feature doesn't exists animore

**Comment by AlmasB** [comment]
@benjimusmaximus please see [the full sample](https://github.com/AlmasB/FXGL/blob/ff2586975ec51eaff8b39556883b52b92d483a21/fxgl-samples/src/main/java/advanced/EmbeddedSample.java) using the latest version
