### ISSUE TITLE
Adjust the offset of the key frame

### ISSUE THREAD

**Issue by ngcin** [AlmasB/FXGL#1181]
Since the image size of each frame is different, I want to align the image of each frame by adjusting the offset of the key frame. If I modify the image, the workload is relatively large. I want to adjust it from the code level. Is there a good way?

**Comment by AlmasB** [comment]
Hmm, that's a good question. As far as I can remember, FXGL does not support offsets for each frame. Sounds like a very useful feature to have. Can you provide a simple (ideally, minimal) demo with an appropriate sprite sheet and I'll see if we can implement this relatively soon...

**Comment by ngcin** [comment]
Thanks for your reply, I submitted a simple demo at [https://github.com/ngcin/fani](https://github.com/ngcin/fani) which includes a monster's attack animation. The animation structure description is a json file (/assets/data/monster.json), and the "res" node describes each frame image position in sprite sheet, "frames" describes the offsets of the frame .

**Comment by AlmasB** [comment]
Thanks, I've had a quick look. 

If I understand correctly, we can potentially solve this by:

1. adding `offsetX/Y` to `FrameData` with 0 values as default.
2. inside `AnimatedTexture::updateImage()` use `offsetX/Y` to offset the image:

```
    private fun updateImage() {
        val frameData = animationChannel.getFrameData(currentFrame)

        image = animationChannel.image
        fitWidth = frameData.width.toDouble()
        fitHeight = frameData.height.toDouble()
        viewport = frameData.viewport

        // offset here
    }
```

Would that work for your (and also general) use case?

**Comment by ngcin** [comment]
Yes, entirely accurate! This is exactly what I thought, this function is very helpful for us to use existing texture materials, thank you!

**Comment by AlmasB** [comment]
Demo here: https://twitter.com/AlmasBaim/status/1546529789946773506

To get the latest build, you can use this:
```
<dependencies>
    <dependency>
        <groupId>com.github.almasb</groupId>
        <artifactId>fxgl</artifactId>
        <version>17+dev-SNAPSHOT</version>
    </dependency>
</dependencies>

<repositories>
    <repository>
        <id>oss.sonatype.org-snapshot</id>
        <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    </repository>
</repositories>
```
