### ISSUE TITLE
新版Tilde地图编辑器1.9.0 对象层类名由type更改为class，导致加载失败

### ISSUE THREAD

**Issue by 17722797729** [AlmasB/FXGL#1182]
[
![image](https://user-images.githubusercontent.com/43561533/178100312-c701a794-639f-4646-9ce1-067aa5354106.png)
](url)

[
![image](https://user-images.githubusercontent.com/43561533/178100319-8977d6e3-43ba-41e3-866d-104e28140989.png)
](url)

**Comment by AlmasB** [comment]
Hi, 

不好意思，我的汉语不好。我觉得 Tiled 1.9.0- 用了 "type"，但是 1.9.0+ 现在用 "class" 。我要看看，谢谢。

If I understood correctly, it seems "type" has now been replaced with "class" in Tiled 1.9.0+. To adapt to this, whilst maintaining backwards-compatibility, I think the fix could be rather simple:

```
in TMXLevelLoader:

put("type", tiledObject.type)

// ++ put("type", tiledObject.typeClass)
```

I'll take a look at 1.9.0, thanks.

**Comment by AlmasB** [comment]
To get the latest build, you can use this:
```
<dependencies>
    <dependency>
        <groupId>com.github.almasb</groupId>
        <artifactId>fxgl</artifactId>
        <version>17+dev-SNAPSHOT</version>
    </dependency>
</dependencies>

<repositories>
    <repository>
        <id>oss.sonatype.org-snapshot</id>
        <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    </repository>
</repositories>
```

See if it works for your use case.

**Comment by 17722797729** [comment]
understand correctly

**Comment by 17722797729** [comment]
感谢老铁

**Comment by 17722797729** [comment]
爱你

**Comment by AlmasB** [comment]
Done in 17.2
