### ISSUE TITLE
a problem  about physicsComponent

### ISSUE THREAD

**Issue by Xiaobaishushu25** [AlmasB/FXGL#1209]
Hello, I encountered a problem about physical components. My goal is to play a displacement animation when an entity is added. After the animation, add a physical component to it so that it can fall freely and have a speed. Now I have a problem that I can't set the speed after adding physical components. Maybe I can add physical components in the entitybuilder of this entity, but I don't know how to play a displacement animation easily.
this is my code:
``` kotlin

  override fun onAdded() {
        entity.zIndex = -1
       
 val type = entity.getString("type")
        entity.viewComponent.addChild(texture("map/item/$type.png"))
        val node = entity.viewComponent.children[0]
        val keyValue = KeyValue(node.translateYProperty(), node.layoutY -25.0)
        val keyFrame = KeyFrame(Duration.seconds(1.2), keyValue)
        val timeline = Timeline(keyFrame)
        timeline.play()
        timeline.setOnFinished {
            entity.zIndex = 0
            val physicsComponent = PhysicsComponent().apply {
                setBodyType(BodyType.DYNAMIC)
                addGroundSensor(HitBox("GROUND_SENSOR",  BoundingShape.box(37.0,37.0)))
                setFixtureDef(FixtureDef().friction(0.0f))
            }
            entity.addComponent(physicsComponent)
            entity.getComponent(PhysicsComponent::class.java).velocityX=50.0
        }
    }
```
this is the error:
java.lang.IllegalStateException: Physics not initialized yet! Use setOnPhysicsInitialized() instead
	at com.almasb.fxgl.entity@17.2/com.almasb.fxgl.physics.PhysicsComponent.getPhysicsWorld(PhysicsComponent.java:59)
	at com.almasb.fxgl.entity@17.2/com.almasb.fxgl.physics.PhysicsComponent.getLinearVelocity(PhysicsComponent.java:239)
	at com.almasb.fxgl.entity@17.2/com.almasb.fxgl.physics.PhysicsComponent.getVelocityY(PhysicsComponent.java:220)
	at com.almasb.fxgl.entity@17.2/com.almasb.fxgl.physics.PhysicsComponent.setVelocityX(PhysicsComponent.java:208)
	at SuperMaLi/xbss.components.ItemComponent.onAdded$lambda-2(ItemComponent.kt:52)
how can i handle this problem?Thanks!

**Comment by chengenzhao** [comment]
```kotlin
override fun onAdded() {
entity.zIndex = -1

val type = entity.getString("type")
entity.viewComponent.addChild(texture("map/item/$type.png"))
val node = entity.viewComponent.children[0]
val keyValue = KeyValue(node.translateYProperty(), node.layoutY -25.0)
val keyFrame = KeyFrame(Duration.seconds(1.2), keyValue)
val timeline = Timeline(keyFrame)
timeline.play()
timeline.setOnFinished {
entity.zIndex = 0
val physicsComponent = PhysicsComponent().apply {
setBodyType(BodyType.DYNAMIC)
addGroundSensor(HitBox("GROUND_SENSOR", BoundingShape.box(37.0,37.0)))
setFixtureDef(FixtureDef().friction(0.0f))
}
entity.addComponent(physicsComponent)
entity.getComponent(PhysicsComponent::class.java).velocityX=50.0
}
}
```

**Comment by AlmasB** [comment]
Hi,
```
entity.getComponent(PhysicsComponent::class.java).setOnPhysicsInitialized {
    // code to run with physics
}

```
