### ISSUE TITLE
AStar pathfinder support 8 directions move, include diagonal cell

### ISSUE THREAD

**Issue by NanaLearnCoding** [AlmasB/FXGL#1213]
i find AStarMoveComponent  moveToCell only support 4 directions (up down left right)，so when the cell moving, it looks a little stiff. 
the code show that:
`Note: returned cells are in the grid (i.e. bounds are checked). Diagonal cells are not included. The order is left, up, right, down.`
so, could  it  support 8 directions move?  
thank u

**Comment by AlmasB** [comment]
Currently no. Though it would be a good idea. Thanks for the suggestion.

**Comment by AlmasB** [comment]
Link to #1339
