### ISSUE TITLE
Viewport.unbind bug

### ISSUE THREAD

**Issue by AlmasB** [AlmasB/FXGL#1253]
### Discussed in https://github.com/AlmasB/FXGL/discussions/1228

<div type='discussions-op-text'>

<sup>Originally posted by **chengenzhao** February 14, 2023</sup>
Hi:

The implementation of viewport.unbind seems like a bug
cause it only unbind the zoom property
if we bind the viewport to an entity and then unbind it and also set the x property then it won't work
like:
```java
viewport.bindToEntity(player);
viewport.unbind();
viewport.setX(1000);//it doesn't work
```
and I checked the source code the proper way of real unbind should be:
```java
viewport.bindToEntity(player);//bound
viewport.bindToEntity(viewport.getCamera(),0,0);//unbound
viewport.getCamera().setX(1000);
```
so is it a bug of the code?

Thanks</div>

**Comment by chengenzhao** [comment]
Hi:

This bug should be easy to fix
probably all we need to do is just add
```java
boundX.unbind()
boundY.unbind()
```
to the method of unbind
then it should work

cheers

**Comment by AlmasB** [comment]
Should be completed by [commit](https://github.com/AlmasB/FXGL/commit/76cdf21f723876973d1d34435d5008480b7bce61). Please can you check @chengenzhao when the build's ready

**Comment by chengenzhao** [comment]
It works
thx
