### ISSUE TITLE
Does fxgl supports graalvm native image in windows

### ISSUE THREAD

**Issue by wuguowei19880907** [AlmasB/FXGL#1275]
I build a fxgl demo with graalvm native image , it can build success.
But when i run the demo.exe, it run errors.
![image](https://github.com/AlmasB/FXGL/assets/19338820/2398ae78-aeae-4cde-bfff-2dbed0f9c952)

java code is:
```
import com.almasb.fxgl.app.GameApplication;
import com.almasb.fxgl.app.GameSettings;
import com.almasb.fxgl.dsl.FXGL;
import javafx.scene.paint.Color;
import javafx.scene.shape.Rectangle;

public class BasicGames extends GameApplication {
    @Override
    protected void initSettings(GameSettings settings) {
        settings.setWidth(800);
        settings.setHeight(600);
        settings.setTitle("BasicGameSample");
    }

    @Override
    protected void initGame() {
        FXGL.entityBuilder()
                .at(150, 150)
                .view(new Rectangle(40, 40, Color.BLUE))
                .buildAndAttach();
    }

    public static void main(String[] args) {
        launch(args);
    }
}
```

graalvm info is:
`graalvm-ce-java17-22.3.1`

**Comment by AlmasB** [comment]
Hi, it certainly used to work on mac before, I don't remember testing on windows. Can you provide a link to build instructions and I'll try to replicate. Thanks.

**Comment by wuguowei19880907** [comment]
> Hi, it certainly used to work on mac before, I don't remember testing on windows. Can you provide a link to build instructions and I'll try to replicate. Thanks.

https://github.com/wuguowei19880907/sangame.git

**Comment by AlmasB** [comment]
You will need a different graalvm distribution (the one that works with javafx): [here](https://github.com/gluonhq/graal/releases)

Here's the [plugin](https://github.com/gluonhq/gluonfx-maven-plugin) that allows using it. 

The [samples](https://github.com/gluonhq/gluon-samples) on how to build and run, with instructions available [here](https://docs.gluonhq.com/#platforms_windows).

1. Run `mvn gluonfx:run` to check the environment works
2. Run `mvn gluonfx:runagent` to collect reflection data
3. Finally, `mvn gluonfx:build` will build an .exe

![Screenshot 2023-06-20 22 19 55](https://github.com/AlmasB/FXGL/assets/3594742/be5b47e5-3190-403c-bc8f-9e98bb0bb041)

**Comment by wuguowei19880907** [comment]
ok, thanks!
