### ISSUE TITLE
How to add the full-screen function of F11 games using FXGL version 17.3?

### ISSUE THREAD

**Issue by MYXK** [AlmasB/FXGL#1285]
@Override
    protected void initInput() {
        getInput().addAction(new UserAction("Toggle Fullscreen") {
            @Override
            protected void onActionBegin() {
                //Full Screen

                System.out.println("F11");
            }
        }, KeyCode.F11);
    }

**Comment by MYXK** [comment]
Resolved

**Comment by AlmasB** [comment]
In case anyone needs this in the future:

```
// in settings -- initSettings(GameSettings settings)
settings.setFullScreenAllowed(true);

// later when need to set fullscreen
FXGL.getSettings().getFullScreen().set(true);
```
