### ISSUE TITLE
Can't build with jdk 20

### ISSUE THREAD

**Issue by Cabbage0211** [AlmasB/FXGL#1293]
Empty project.
![Snipaste_2023-09-25_21-31-35](https://github.com/AlmasB/FXGL/assets/116654539/dfa64370-ba3d-4ed3-af03-5ef9afb8b80b)
![Snipaste_2023-09-25_21-31-57](https://github.com/AlmasB/FXGL/assets/116654539/bc91e59c-1e4c-4775-b8e2-51ab8a65d4f2)

**Comment by AlmasB** [comment]
The project builds fine with jdk 21, [example build](https://github.com/AlmasB/FXGL/actions/runs/7741496775/job/21108621585)

Perhaps upgrading the IDE to latest can solve this? Can be reopened if the issue persists.
