### ISSUE TITLE
Provide direct access to all scenes and subscenes

### ISSUE THREAD

**Issue by AlmasB** [AlmasB/FXGL#1315]
Currently, only the GameScene object can be easily obtained. References to others are obscured.

**Comment by chengenzhao** [comment]
Yeah, this is an important function we should have

**Comment by DeathPhoenix22** [comment]
Agreed! I've created a work around in my case by adding a listener on the "Scene changed". This way, I can access them all by gradually storing them at runtime ;) But having access to core scenes would be ideal. Obviously, you have access to yours ;) Food for thoughts, we could have a "FXGL.getScene(Class) method that would return it if it's currently added to the JavaFX root.

**Comment by AlmasB** [comment]
Hi both, please see the attached commit.

**Comment by chengenzhao** [comment]
> Hi both, please see the attached commit.

Is it possible to have a method to get the list of all SubScenes? 
including custom GameSubScene instances pushed by the getSceneService().pushSubScene(scene) method?
