### ISSUE TITLE
Moving the viewport down in AnimationChannel class

### ISSUE THREAD

**Issue by TMPJOE** [AlmasB/FXGL#1316]
I'm starting a to learn FXGL using the wiki and some videos, but when building an entitiy with "AnimationComponent" using the basic example in the wiki i faced a problem, the sprites i'm using are in vertical.
this is a problem because the viewPort move left to righy and my frames are up to down, i'm only seeing the frame '0' every 1 second so I think it's just a matter of giving the 2 options depending on the sprites that the person wants to use, since many of us are not artists or we do not have the knowledge to edit the images so that they remain horizontal and work, it is not like "fair" either that I have to use other sprites, I know that if I look for some horizontally I would have no problems and everything would work but I wanted to see if that can be solved easily or would it be a waste of time or unnecessary.

**Comment by DeathPhoenix22** [comment]
Agreed! I've created a work around in my case by adding a listener on the "Scene changed". This way, I can access them all by gradually storing them at runtime ;) But having access to core scenes would be ideal. Obviously, you have access to yours ;) Food for thoughts, we could have a "FXGL.getScene(Class<FXGLScene>) method that would return it if it's currently added to the JavaFX root.

**Comment by DeathPhoenix22** [comment]
Hi @TMPJOE ,
This can be achieved with the use of an AnimationChannel. The channel will define how to "read/use" the Sprite. Here's a simple code snippet from my game:

```
    return new AnimationChannel(
            FXGL.image(textureSpec.getPath()),  // Load you Sprite texture
            stack.getFramePerRow(),  // In you case, this is "1" because your animation is vertically stored in the Texture
            textureSpec.getFrameWidth(),  // Each frame width
            textureSpec.getFrameHeight(),  // Each frame width
            animationTime,  // 1.0 since you said your animation last for 1 second
            stack.getStartFrame(), // 0, unless you have many different animations stored in that Texture
            stack.getEndFrame() // X, which is the number of frames - 1 (it's an array index, so it's count - 1)
        );
```

Does that help?
Have a nice day :)

**Comment by DeathPhoenix22** [comment]
And in case you missed it, here is where the documentation related to AnimationChannel is:
https://github.com/AlmasB/FXGL/wiki/Adding-Sprite-Animations-(FXGL-11)
