### ISSUE TITLE
Can not found LevelParsingFactorySample.java

### ISSUE THREAD

**Issue by demon90s** [AlmasB/FXGL#1360]
I read about this toturial, https://github.com/AlmasB/FXGL/wiki/Building-Levels-Using-Tiled-Map-Editor-%28FXGL-11%29

and goto the link of the example code(in the end of Text Format section): LevelParsingFactorySample.java

which page is not found

**Comment by AlmasB** [comment]
Thanks for pointing this out. It has now been updated, please check it works.
