### ISSUE TITLE
How to turn off the default logging feature and use a logging framework such as logback?

### ISSUE THREAD

**Issue by huayunliufeng** [AlmasB/FXGL#1371]
The latest version of the default log printing does not meet the requirements, and there are too many cut files. How to close it or configure it in third-party logging frameworks such as logback? Currently, there are two coexisting situations, which is not what I want.

**Comment by AlmasB** [comment]
Hi,

This might help:

```
Logger.removeAllOutputs()
```

In theory, this should remove all default / internal logging.

If you just want to format it differently, then after removing all outputs, you can try adding your own:

```
Logger.addOutput(custom logger output, log level)
```

**Comment by huayunliufeng** [comment]
thanks
