### ISSUE TITLE
If I want to use  javafx.application.Application How to add some custom code to the start method of Application, that is, rewrite this method, in the 21 version of fxgl?

### ISSUE THREAD

**Issue by huayunliufeng** [AlmasB/FXGL#1372]
Because I want to use the Atlantafx framework（ https://github.com/mkpaz/atlantafx ）To use it, you must add code similar to the following in the start method:
`public class Launcher extends Application {

    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage stage) {
        // find more themes in 'atlantafx.base.theme' package
        Application.setUserAgentStylesheet(new PrimerLight().getUserAgentStylesheet());
        Application.setUserAgentStylesheet(new PrimerDark().getUserAgentStylesheet());

        // the rest of the code ...
    }
}`

**Comment by AlmasB** [comment]
Hi, you can use FXGL with its embedded mode. See [sample](https://github.com/AlmasB/FXGL/blob/10ee77c01791be7c9e6c81ed1ccf187b651e07b4/fxgl-samples/src/main/java/advanced/EmbeddedSample.java#L38) where the top level is just a normal JavaFX application.

**Comment by huayunliufeng** [comment]
Thank you very much. After using your solution, my problem has been resolved.
