### ISSUE TITLE
ReflectionFunctionCaller add call() for Objects, not just Strings

### ISSUE THREAD

**Issue by AlmasB** [AlmasB/FXGL#1389]
In addition to:

```
fun call(functionName: String, args: List<String>): Any {
        return call(functionName, args.toTypedArray())
    }
```

val data = SomeClass()
call(fName, data)

**Comment by Whalios** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)
