### ISSUE TITLE
Exception when run game on version 0.2.0

### ISSUE THREAD

**Issue by domeOo** [AlmasB/FXGL#146]
When run game with library version 0.2.0 occur following error :

> run:
> Exception in thread "JavaFX Application Thread" Exception in thread "main" java.lang.reflect.InvocationTargetException
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
> Caused by: java.lang.NullPointerException
> 	at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:383)
> 	at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
> 	... 5 more
> java.lang.NoClassDefFoundError: com/almasb/ents/EntityWorldListener
> 	at java.lang.ClassLoader.defineClass1(Native Method)
> 	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
> 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
> 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
> 	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
> 	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
> 	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	at java.lang.ClassLoader.defineClass1(Native Method)
> 	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
> 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
> 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
> 	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
> 	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
> 	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	at java.lang.Class.forName0(Native Method)
> 	at java.lang.Class.forName(Class.java:348)
> 	at com.sun.javafx.application.LauncherImpl.lambda$launchApplicationWithArgs$153(LauncherImpl.java:352)
> 	at com.sun.javafx.application.LauncherImpl$$Lambda$44/1463801669.run(Unknown Source)
> 	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$172(PlatformImpl.java:326)
> 	at com.sun.javafx.application.PlatformImpl$$Lambda$45/1327763628.run(Unknown Source)
> 	at com.sun.javafx.application.PlatformImpl.lambda$null$170(PlatformImpl.java:295)
> 	at com.sun.javafx.application.PlatformImpl$$Lambda$48/29040367.run(Unknown Source)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at com.sun.javafx.application.PlatformImpl.lambda$runLater$171(PlatformImpl.java:294)
> 	at com.sun.javafx.application.PlatformImpl$$Lambda$47/1535128843.run(Unknown Source)
> 	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
> 	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
> 	at com.sun.glass.ui.win.WinApplication.lambda$null$145(WinApplication.java:101)
> 	at com.sun.glass.ui.win.WinApplication$$Lambda$36/1323468230.run(Unknown Source)
> 	at java.lang.Thread.run(Thread.java:745)
> Caused by: java.lang.ClassNotFoundException: com.almasb.ents.EntityWorldListener
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	... 40 more
> BUILD STOPPED (total time: 2 minutes 23 seconds)

**Comment by AlmasB** [comment]
What build tool are you using? Note that the jar in Releases only contains the library itself without dependencies

**Comment by domeOo** [comment]
hi thanks for your quick reply. To build the library I use maven

**Comment by AlmasB** [comment]
Please refer to this example POM which you can use in Maven. It just requires renaming the package and the name of the main class.

**Comment by AlmasB** [comment]
If you have further problems with setting up the library please refer to this [video](https://www.youtube.com/watch?v=ZM2NuvMG4cg)
