### ISSUE TITLE
Music with a CycleCount > 1 removed from activeMusic, but not stopped

### ISSUE THREAD

**Issue by Ergo21** [AlmasB/FXGL#208]
In FXGLAudioPlayer.kt:onUpdateEvent()
The following code has several issues,

activeMusic.filter { it.mediaPlayer.getCurrentTime() == it.mediaPlayer.getTotalDuration() }
.forEach { it.isStopped = true }

1. The test checks if the music has ended, but does not check if the music will cycle. Hence, if the music does cycle it is removed from the activeMusic, but continues to play.
2. The result marks the music as stopped, but does not set it as stopped. Hence, an inconsistent state can occur i.e. Music marked as stopped, but not stopped.

Suggested Fix

activeMusic.filter { (it.mediaPlayer.getCurrentTime() == it.mediaPlayer.getTotalDuration() && 
                             it.mediaPlayer.getCurrentCount() == it.mediaPlayer.getCycleCount()) }
.forEach { 
      it.mediaPlayer.stop(); 
      it.isStopped = true; 
}

**Comment by Ergo21** [comment]
Though it occurs to me you could probably remove the check,
it.mediaPlayer.getCurrentTime() == it.mediaPlayer.getTotalDuration() 
in favour of the Count check.

**Comment by AlmasB** [comment]
it.mediaPlayer.getCurrentTime() == it.mediaPlayer.getTotalDuration() takes into account all cycles, [javadoc](http://download.java.net/jdk8/jfxdocs/javafx/scene/media/MediaPlayer.html#getTotalDuration--) Do you have a minimal test example I can run?

**Comment by Ergo21** [comment]
No, I don't have a minimal test example. But, it can easily be checked for by adding a music with a CycleCount > 1 and adding to onUpdateEvent(),
System.out.println("Active Music: " + activeMusic.size() + " | " + activeMusic.toString));

**Comment by AlmasB** [comment]
I mistakenly thought that current time would also (as total duration) take into account cycles. Apparently it does not, so thanks for pointing this out to me.

**Comment by AlmasB** [comment]
Added in a few extra checks to ensure state consistency. Your fix was spot on, I just replaced `totalDuration` with `cycleDuration` since we are now checking the cycles ourselves and weakened the cycle check to `>=` because the cycle count could've been extended at runtime.

The commit is attached above, feel free to close the issue if the commit resolves it.

**Comment by Ergo21** [comment]
Seems good. Closing now.
