### ISSUE TITLE
Allow setting custom image for any menu background

### ISSUE THREAD

**Issue by AlmasB** [AlmasB/FXGL#222]
Let users choose their games' splash image for menu background while being able to use one of our pre-defined menu styles. This will enable them to quickly set up our menus with their flavor.

**Comment by AlmasB** [comment]
This can be done via overriding initSceneFactory() and providing your implementation of createBackgroundView. done in 0.2.7

**Comment by mortensen** [comment]
How is this done in a current version?

**Comment by AlmasB** [comment]
Here's an example for StartupScene, but can reuse for a menu:

https://github.com/AlmasB/FXGL/blob/38aa7c087b13982c6948457cd292507c0d4e52fc/fxgl-samples/src/main/java/intermediate/CustomStartupSample.java

Here's a more complex example for main menu:

https://github.com/AlmasB/FXGLGames/blob/master/GeometryWars/src/main/java/com/almasb/fxglgames/geowars/menu/GeoWarsMainMenu.java

Essentially, you want:

```
Node node = ... some node image or view
getContentRoot().getChildren().add(node);
```

**Comment by mortensen** [comment]
Thank you very much! I thought I had to play around with Background and BackgroundImage. But adding simply an ImageView to the content Root children before adding the buttons works fine. Thanks for your patience and help!
