### ISSUE TITLE
Add shadow plugin to FXGL-Gradle

### ISSUE THREAD

**Issue by AlmasB** [AlmasB/FXGL#335]
The example maven projects generate a standalone executable jar with assets. Add same to [gradle projects](https://github.com/AlmasB/FXGL-Gradle)

**Comment by dejan2609** [comment]
@AlmasB: I'll try to squeeze this one.

**Comment by AlmasB** [comment]
@dejan2609 Cheers! Let me know how you get on

**Comment by dejan2609** [comment]
I have made some progress, but I'm kind of stuck with shadowJar output folder (re)location.... links below are mental note to my self:

- http://imperceptiblethoughts.com/shadow/#controlling_jar_content_merging
- https://stackoverflow.com/questions/45255986/how-to-set-the-output-path-of-the-gradle-shadowplugin
- https://github.com/johnrengelman/shadow/tree/2.0.1/src/main/groovy/com/github/jengelman/gradle/plugins/shadow/transformers
- https://maven.apache.org/plugins/maven-shade-plugin/examples/resource-transformers.html

**Comment by AlmasB** [comment]
Can you give me a quick rundown the issue. Does the plugin generate fat jar and place it somewhere else or ?

**Comment by dejan2609** [comment]
@AlmasB scratch my previous comment, I had some issues with my **_<userHome>.gradle folder_** (I got them resolved after I nuked **_.gradle_** folder).

See pull request, I managed to start new game like this:
```
./gradlew sJ
cd build/libs/
java -jar FXGL-Gradle-all.jar
```

**Comment by AlmasB** [comment]
what's `sJ` for? I used `build` and it seems to be working

**Comment by AlmasB** [comment]
Also, does the same trick work with kotlin? The repo for kotlin is [here](https://github.com/AlmasB/FXGL-GradleKt). It'd be great if you could update that too

**Comment by dejan2609** [comment]
`sJ` is a shorthand for `shadowJar` task. `build` task also does the trick (i.e. creates shadow Jar and all other distributions: tar, zip, shadow.tar and shadow.zip).

I'll check kotlin repo tomorrow, I guess it should not be hard.

**Comment by AlmasB** [comment]
Awesome 👍

**Comment by dejan2609** [comment]
@AlmasB try Kotlin PR, please.

**Comment by AlmasB** [comment]
@dejan2609 Great job, all works! Your help is much appreciated
