### ISSUE TITLE
Self moving backgrounds

### ISSUE THREAD

**Issue by AlmasB** [AlmasB/FXGL#342]
Now that we have parallax backgrounds it would be useful to allow certain layers move on their own, i.e. without dependency on the viewport.

Example: clouds in a platformer, they should keep moving regardless of player movement

**Comment by jvondermarck** [comment]
Hi, so how do we do have a moving background ?
Thank you.

**Comment by AlmasB** [comment]
@jvondermarck Hi, I couldn't find the exact sample code for this, but here's a sandbox sample: https://github.com/AlmasB/FXGL/blob/dev/fxgl-samples/src/main/java/sandbox/ScrollingBackgroundSample.java

Just replace the scrolling view with:

`new SelfScrollingBackgroundView(image, width, height, Orientation.HORIZONTAL, moveSpeed);`

If any issues, please let me know.

**Comment by jvondermarck** [comment]
Thank you so much, I hope it will help for my project. 
I'll keep you in touch if I have any issues.

**Comment by JavaGitHubber** [comment]
Hi Almas,
In 0.5.3 I really liked the parallaxing background capability. 
My code was:

getGameWorld().addEntityFactory(new ParallaxBgd_EntityFactory());
...
List<ParallaxTexture> bgdArray = new ArrayList<>();
for (int i=10; i>=0; i--) { 
     double speed = (10-i)/10.0;
     ParallaxTexture t = new ParallaxTexture(
           getAssetLoader().loadTexture("bg_"+i+".png"), speed);
     bgdArray.add(t);
}
getGameScene().addGameView(new ParallaxBackgroundView(bgds, Orientation.HORIZONTAL));
getGameScene().getViewport().bindToEntity(player, 640, 0); 
...

This worked really fine and we got a realistc deep view with moving with the player, but unfortunatelly this is gone wit 11, 17 and 21,
Or, what might be possible, it is my fault - don't blame me :-))

I tried this in FXGL 17 and 21:
getGameWorld().addEntityFactory(new ParallaxBgd_EntityFactory());
player = spawn("player",-2000,0);
...
for (int i=10; i>=0; i--) {
            double speed = (10-i)/10.0;
            String bgImage = "bg_"+i+"_1.png";
            entityBuilder()
                    .view(new SelfScrollingBackgroundView(texture 
                            ("bg_"+i+".png").getImage(),
                            getAppWidth(), getAppHeight(), 
                            Orientation.HORIZONTAL, speed))
                    .buildAndAttach(); }

Viewport viewport = getGameScene().getViewport();
viewport.bindToEntity(player,0, 0);
viewport.setBounds(-2000, 0, 2000, getAppHeight());

Now, there is no perspective view, despite the speed si set individually to the layers. And also the automatic repetition of images is missing.

Hope you can help me in this case, thanks a lot. Cheers
