### ISSUE TITLE
Collision handlers stop when i use the SetLevel(level) function

### ISSUE THREAD

**Issue by Punkliver** [AlmasB/FXGL#346]
I'm making a game based on your towerfall model.
I created a second level and other types of blocks and add a second player. The Trouble came when i try to use the   getGameWorld().setLevel(level), it open, load the entities, but, the collision handlers stop work.
On the first Level, everything works nice. Just when i need to change level.
The arrows dont collide. but the player still colliding. I created a block who kills the player instantly, on the level 1 works fine, but on level 2, the player colide with the block, but don't get killed.

[Player1Platform2Handler - Copia.txt](https://github.com/AlmasB/FXGL/files/1131259/Player1Platform2Handler.-.Copia.txt)
[TowerfallApp - Copia.txt](https://github.com/AlmasB/FXGL/files/1131261/TowerfallApp.-.Copia.txt)

**Comment by AlmasB** [comment]
Thanks for taking time to test FXGL. [Commit](c50cfa0f2b6b2c86eb4f18620c937ae76c219547) fixes this issue. Release for 0.3.5 is due next week

**Comment by AlmasB** [comment]
merged 0.3.5
