### ISSUE TITLE
Help Wanted: Unit Tests

### ISSUE THREAD

**Issue by AlmasB** [AlmasB/FXGL#368]
There is a lot of code that would benefit from having unit tests, non-UI stuff in particular

**Comment by coldwarrl** [comment]
You wanna prioritize a little / give hints (which classes/functionality) in particular ? I guess I can help write some here and there...

**Comment by AlmasB** [comment]
[codecov](https://codecov.io/gh/AlmasB/FXGL/tree/0.4.1/fxgl/src/main) should give you a good idea about what is covered and what isn't. I'd suggest we push those classes / functionality that are near 100% coverage to full 100% because we are somewhat confident these things are used. For those closer to 0% coverage I wouldn't bother for the time being.

**Comment by Simulant87** [comment]
The link you posted is outdated. Here is the entry point into the dashboard overview [https://codecov.io/gh/AlmasB/FXGL](https://codecov.io/gh/AlmasB/FXGL)

**Comment by AlmasB** [comment]
@Simulant87 Many thanks

**Comment by AlmasB** [comment]
Most of the core modules is now tested. Unit tests for specific packages / files will be opened as separate issues as needed.
