### ISSUE TITLE
Allow toggling fullscreen mode

### ISSUE THREAD

**Issue by AlmasB** [AlmasB/FXGL#375]
When fullscreen is off, proceed as normal. When toggled to on, follow:

`If` (target resolution is lower than screen size) scale up to fill the screen (with original ratio). 

`else if` (target resolution is greater than screen size) scale down (with original ratio). 

`else` just enter fullscreen

**Comment by mokun** [comment]
Question, how do we deconflict this new feature with JavaFX's own use of ESC key for its full screen mode ? Or will both work on their own ways without interfering with each other ?

**Comment by AlmasB** [comment]
@mokun FXGL overrides the ESC key for exiting the fullscreen mode. As such the players will only be able to toggle fullscreen on / off from their games or bypass via their OS commands.

**Comment by mokun** [comment]
I'm STILL trying to understand more HOW the full screen mode will impact the application.

In Java2D, there is a full screen exclusive mode. https://docs.oracle.com/javase/tutorial/extra/fullscreen/exclusivemode.html

But in JavaFX, toggling the ESC simply stretch the window size to fit the size of the screen and remove the title bar, the window border, and the top right buttons. 

But this is still NOT quite the "kiosk mode" that some want to have for setting up a kiosk machine with only ONE APPLICATION running.

is this full screen mode in FXGL pretty much the same as a full screen window that is maximized to make use of all real estate of the screen, like JavaFX ?

**Comment by AlmasB** [comment]
Well, FXGL uses JavaFX, so anything we do is subject to support by JavaFX. You can read about JavaFX fullscreen in [doc](https://docs.oracle.com/javase/8/javafx/api/javafx/stage/Stage.html#fullScreenProperty). In short, it seems JavaFX does support exclusive mode and that is what we will try to achieve.
