### ISSUE TITLE
HitBox - generate name automatically if not provided

### ISSUE THREAD

**Issue by AlmasB** [AlmasB/FXGL#386]
Currently `HitBox()` requires `String name`. Most of the time we do not care what the name is, so it can automatically generated if not passed in.

**Comment by SNException** [comment]
Hey, I would like to try and solve this issue.
My current idea is to overload the constructor. This constructor would only take in a BoundingShape object. 
If we do not care what the name is than I would simply use the type of the BoundingShape as the name
if that's fine.

Example:
```java
    public HitBox(BoundingShape shape) {
        this(String.valueOf(shape.type), shape);
    }
```

**Comment by AlmasB** [comment]
A good starting point, but what if we have 2 or more auto generated names, we probably want them to be of the form `type-1`, `type-2`, etc, or something along those lines?

**Comment by AlmasB** [comment]
How about using `shape.hashCode()` and convert that to string? This gives us the uniqueness

**Comment by SNException** [comment]
Ah, you are right. I did not think about the names having to be unique. I like the hashCode proposal. I'll do that. 👍

**Comment by AlmasB** [comment]
Awesome! Looking forward to the pull request, make sure it's done against the development branch, i.e. `0.4.0`

**Comment by AlmasB** [comment]
Thanks, merged.
