### ISSUE TITLE
Questions about background pictures

### ISSUE THREAD

**Issue by OverrideSkywalker** [AlmasB/FXGL#398]
I created a new background image and added it to the scene.
Just like this:
`        getGameScene().addGameView(new ParallaxBackgroundView(Arrays.asList(
                new ParallaxTexture(getAssetLoader().loadTexture("pic.jpg", 1280, 768), 1.0)
 ), Orientation.HORIZONTAL, BG));`

But...
How to control the picture movement by inputting the keys?(W/A/S/D)

**Comment by AlmasB** [comment]
Have a look at [this sample](https://github.com/AlmasB/FXGL/blob/master/fxgl-samples/src/main/java/s10miscellaneous/ScrollingBackgroundSample.java). In short, you don't control the background. You bind the viewport (camera) to some entity (e.g. player) that you control.

**Comment by OverrideSkywalker** [comment]
Ah！The background picture really moved！It's amazing,Thank you
but ,I want to move the picture horizontally and vertically simultaneously
What should I do?
(Forgive me for being a beginner→_→)
Thanks again

**Comment by AlmasB** [comment]
The use case for `ScrollingBackgroundView` is a horizontal or vertical side-scroller. Hence, only one dimension can be used. It appears you have a slightly different use case. If you explain in detail what you are trying to do I can create an issue and the feature might get implemented in future versions.

**Comment by OverrideSkywalker** [comment]
Thank you for your generous help.
I want to develop a game that players can move up and down on the 2D plane,But this background is big enough…So only move the backgroung picture to control the movement of characters…
Uh，I don't know if there's any problem with my mind…
thanks again

**Comment by OverrideSkywalker** [comment]
Ah！I know how to do it！
I do  it with just the following code:
`getGameScene().addGameView(new EntityView(getAssetLoader().loadTexture("pic.jpg")));`
Thank you for your help :-)

**Comment by AlmasB** [comment]
Yes you can use that if you don't need repeating background. Glad it was resolved
