### ISSUE TITLE
Questions about VideoIntro & initializing game

### ISSUE THREAD

**Issue by OverrideSkywalker** [AlmasB/FXGL#406]
I've just been studying the use of the engine for 2 days,I found this engine pretty good.
But I have 2 questions to ask about the author of the engine:
1.When I learned "VideoIntroSample":

`    public static class MySceneFactory extends SceneFactory {
        public IntroScene newIntro() {
            return new VideoIntroScene("1.mp4");
        }
    }`

I don't know which path the MP4 resource is required for "VideoIntroScene"
2.Every time you load a game scene, there will be a progress bar(Black interface),I want to add a picture to the Loading interface(initializing game),what should I do?

Thanks to the handsome and kind-hearted author( ͡° ͜ʖ ͡°)

**Comment by AlmasB** [comment]
No worries, I appreciate your interest and your questions will help me write a better documentation on how to use FXGL.

1. The video file should be placed under `assets/video/`, so in your case it would be `assets/video/1.mp4`.

2. Have a look at [this directory](https://github.com/AlmasB/FXGL/tree/master/fxgl/src/test/java/manual/loading). There are 2 files, one shows to how to design your custom loading scene, the other shows how to use your custom scene.

**Comment by OverrideSkywalker** [comment]
Ah,I got it! It's amazing
Thank you very much

**Comment by lll-hue** [comment]
Hello,handsome author,i am finding this directory,but it is disappear.can u tell me where can i get?and i want to learn how to load video into my game start for introducing the game of backstory,what should i do?

**Comment by lll-hue** [comment]
@AlmasB

**Comment by AlmasB** [comment]
@lll-hue Hi, I've just added the functionality. Here's an example:

```
public class VideoSample extends GameApplication {
    @Override
    protected void initSettings(GameSettings settings) {
        settings.setWidth(1280);
        settings.setHeight(720);
    }

    @Override
    protected void initUI() {
        // testvideo.mp4 must be located in /assets/videos/
        var video = getAssetLoader().loadVideo("testvideo.mp4");
        video.setFitWidth(getAppWidth());
        video.setFitHeight(getAppHeight());
        video.getMediaPlayer().play();

        addUINode(video);
    }

    public static void main(String[] args) {
        launch(args);
    }
}
```

You will need the latest dev build to use this:

```
<dependencies>
    <dependency>
        <groupId>com.github.almasb</groupId>
        <artifactId>fxgl</artifactId>
        <version>17+dev-SNAPSHOT</version>
    </dependency>
</dependencies>

<repositories>
    <repository>
        <id>oss.sonatype.org-snapshot</id>
        <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    </repository>
</repositories>
```

**Comment by lll-hue** [comment]
Thanks for your reply，this is helpful to me，i am learning this engine。
Hope you have a good day
