### ISSUE TITLE
Question about map physical collision

### ISSUE THREAD

**Issue by OverrideSkywalker** [AlmasB/FXGL#407]
I'm trying to understand your engine right now,But there are still many problems in the actual coding.
I want to make a simple RPG demo
I built a new background image as a map,I also created new player entity and PlayerControl
There are obstacles on my background picture (map),How do I detect them and avoid obstacles?
I refer to `PhysicsSample`,I think : whether need to add physics entity to the map to Collision detection?
Is there a simpler solution?I asked for some information,
For example, cocos2d,The engine supports the Tiled map editor,Does FXGL support some map editors?
thank you

**Comment by AlmasB** [comment]
Depending on how you are planning to implement collisions, FXGL may or may not be helpful in this situation. Potentially, you could build tiles from a map (.json), then using an object layer for collisions mark tiles that are not "walkable". Finally use [A* search](https://github.com/AlmasB/FXGL/blob/master/fxgl-samples/src/main/java/s08ai/pathfinding/PathfindingSample.java) to move entities.

**Comment by OverrideSkywalker** [comment]
Thank you for giving me ideas.
