### ISSUE TITLE
*.tmx file tile collision

### ISSUE THREAD

**Issue by OverrideSkywalker** [AlmasB/FXGL#409]
According to your suggestion,I've created a new *.tmx file,
So how should FXGL read the *.Tmx files?
How do I control my palyerenitiy to detect these collisions?
thank you

**Comment by AlmasB** [comment]
This is going to take some effort and unfortunately I don't have time for writing tutorials at the moment. Plus, Tiled Map Editor support is very experimental and complicated at this stage, so errors may occur. In future versions I hope to simplify it, but if you want to proceed, here's a rough guide:

1. In Tiled Map Editor assign each collidable object a type, e.g. rock, sand, see [this](https://github.com/AlmasB/FXGLGames/blob/master/Mario/src/main/java/com/almasb/fxglgames/mario/MarioFactory.java)
2. Export your .tmx as .json with **embedded tileset**
3. Create an entity factory for each type (like in the link above)
4. Set the level using [this sample](https://github.com/AlmasB/FXGLGames/blob/master/Mario/src/main/java/com/almasb/fxglgames/mario/MarioApp.java#L101)

At this point all objects should be parsed and part of the game world. Depending on how you want your player to move:

A) **tile based movement**: For each object type, using [this sample](https://github.com/AlmasB/FXGL/blob/master/fxgl-samples/src/main/java/s08ai/pathfinding/PathfindingSample.java) you can generate a 2D grid with walkable and unwalkable nodes.

B) Natural (WSAD movement): Extend a `Control` to move your player, when moving left / right / up / down, first move the player, check for collision using `BoundingBoxComponent`, if colliding, step back.
