### ISSUE TITLE
Include the Kotlin sources in the Maven sources JAR

### ISSUE THREAD

**Issue by mikehearn** [AlmasB/FXGL#416]
Thanks for the nice library!

I often like to alt-click things to view their sources. This doesn't work for anything written in Kotlin in FXGL because for some reason the Kotlin code isn't being bundled up into the sources JAR. I bet it's a one-liner in Maven to fix but I don't know what it is.

**Comment by AlmasB** [comment]
Thanks for this. Indeed, it would be useful if users could browse the Kotlin code. I wonder though whether this technically possible... I'll look into this and see what I can dig up

**Comment by AlmasB** [comment]
When you get a chance, could you try the following using `0.4.0-SNAPSHOT` for FXGL version
```
    <repositories>
        <repository>
            <id>oss.sonatype.org-snapshot</id>
            <url>http://oss.sonatype.org/content/repositories/snapshots</url>
        </repository>
    </repositories>
```

See if the Kotlin code comes up. The sources are definitely there now, but IntelliJ IDEA seems to open only some of them at random

**Comment by mokun** [comment]
See the issue below in eclipse : 

![fxgl kotlin maven plugin m2e errors](https://user-images.githubusercontent.com/1168584/33051212-b083db8e-ce1d-11e7-813a-f8866ef54324.png)

**Comment by AlmasB** [comment]
@mokun sorry I'm not very familiar with Eclipse m2e, what's the issue exactly?

**Comment by mokun** [comment]
When I set up my forked FXGL 0.4.0's repo in Eclipse 4.7.1, all pom.xml files have issues and are labelled red.

![kotlin maven plugin pom xml errors](https://user-images.githubusercontent.com/1168584/33095437-89223b08-ceb8-11e7-8aac-471d51f8535f.png)

**Comment by AlmasB** [comment]
The only development IDE that is guaranteed to work is Intellij IDEA. See [Contribution](https://github.com/AlmasB/FXGL/blob/master/CONTRIBUTING.md#development) for details on setup. I could never set up Eclipse properly to work with Kotlin, so unfortunately I can't be of much help there. Though, I hear that Kotlin Eclipse plugin has improved lately

**Comment by mokun** [comment]
Also,

The following two imports cannot be recognized in the AttractorSample class in s03entities in fxgl-samples : 

import com.almasb.fxgl.entity.component.AttractableComponent;
import com.almasb.fxgl.entity.control.AttractorControl;

**Comment by mokun** [comment]
ok i'll switch to using intellij when tinkering with fxgl.
