### ISSUE TITLE
Benchmark demo

### ISSUE THREAD

**Issue by AlmasB** [AlmasB/FXGL#417]
Something like [DemoFX](https://github.com/chriswhocodes/DemoFX) utilizing most core FXGL features for ~2mins with FPS stats at the end.

**Comment by chriswhocodes** [comment]
Hi @AlmasB 
The basic idea behind DemoFX is that all effects extends an AbstractEffect subclass which has a start and stop time.
The demos programmatically set up the start and stop times for each effect to form a sequence.
The main loop class extends javafx.animation.AnimationTimer and renders (multiple) effects whose start and stop time span the current time. The class also handles recording the FPS.
Maybe with FXGL you could create scenes that demonstrate different aspects of the framework - collision detection, high sprite count, parallax scrolling, ...
Just a few thoughts.
Cheers,
Chris
