### ISSUE TITLE
Implement game scale based on resizable stage size

### ISSUE THREAD

**Issue by SNException** [AlmasB/FXGL#420]
Hey 😄 
As discussed on your recent FXGL Space Invader YouTube video I am opening this issue.

As my current understanding goes:
FXGL can scale the game down upon screen resoultion on a fixed/constant ratio. The upscale will also be supported in the future (including full screen).

There could be a feature implementation that will also scale the game down or up whenever the user resizes the stage. A possible way to keep the usage of a fixed ratio for this issue would be that we update both width and height of the stage whenever the user resizes it. For instance if the user changes the width of the stage the height will also get updated so the fixed ratio is kept.

I am not sure if this is a good idea but alternatively we could use letterboxing maybe? That does not scale the game content itself but we would give the user the possiblity to resize the window. We don't have to use letterboxing all the time of course. We could use a new game setting option:

```java

@Override
public void initSettings(GameSettings settings){
    // that would make the stage resizable and enable letter boxing.
    setttings.setLetterBoxing(true); 
}
```

I hope I explained this issue well. 😅

**Comment by AlmasB** [comment]
Thanks for this. I think updating width or height to keep the ratio is a good idea. The maximum resize is then going to be capped by the screen resolution.

**Comment by AlmasB** [comment]
@SNException this is now complete. The manual window resize (disabled by default) can be enabled via

```
settings.setManualResizeEnabled(true);
```

The aspect ratio cannot be maintained automatically (I couldn't find a neat way to do that as window events are spawned by the OS). There is a new button now in Menu -> Video options that fixes the ratio if needed.

Both downscale (target size > **screen** size) and upscale (target size < **window** size) should now work as intended
