### ISSUE TITLE
FXGLMath to work with double

### ISSUE THREAD

**Issue by AlmasB** [AlmasB/FXGL#421]
The JavaFX platform works with `double`, would be easier to just use `double` in `FXGLMath`

**Comment by coldwarrl** [comment]
I need that class also and can do it. You may assign me...

**Comment by AlmasB** [comment]
@coldwarrl did you want to complete this for the 0.4.1 milestone (Dec 31st)? If yes, I'll just wait for your PR and postpone the release if needed, otherwise I'll start release preparation and you can complete it for 0.4.2

**Comment by coldwarrl** [comment]
I plan to do it next week...so 0.42 is better.

**Comment by coldwarrl** [comment]
created pull request https://github.com/AlmasB/FXGL/pull/449
A lot of library functions use float...I've not updated those but only the usages

**Comment by AlmasB** [comment]
Thanks for this
