### ISSUE TITLE
how to programmatically close a window

### ISSUE THREAD

**Issue by mokun** [AlmasB/FXGL#427]
I'm transiting a JavaFX application to run on FXGL. 

At the beginning, a FXGL window is created for hosting the game menu. If a user follows through the steps, at the end, the code will end/close the initial FXGL window and spawn a JavaFX's stage where the game will run on.

How do I close the initial FXGL window without terminating the application while running the second window (a JavaFX stage) ? 

My way of creating the initial FXGL window is briefly as follows :  
```
       Group root = new Group();
       root.getChildren().add(applicationArea);
       root.getChildren().add(stackPane);
       root.getChildren().add(closeApp);
       root.getChildren().add(rootPane);
       
       gameScene.addUINode(root);
```

Currently, I have to manually close the FXGL window by clicking on the close button at the top right hand corner.

If everything were done In JavaFX, I call `firstStage.close()` to close the first window and instantiate the second window with `secondStage = new Stage()`.

After fully converting my game to run under FXGL in future, I would not need the second window (secondStage) at all.

For now, how do I close the FXGL window but without exiting the app ?

Appreicate any help!

**Comment by AlmasB** [comment]
You could obtain a JavaFX `Window / Stage` from the game scene (something like):
```
Stage fxglStage = (Stage) getGameScene().getRoot().getScene().getWindow();
```

FXGL was designed to be a framework that wraps user code. I understand that you use it as part of a larger framework, hence some things are not trivial.

**Comment by mokun** [comment]
That works! Thought it would be a lot harder. Thanks!

**Comment by mokun** [comment]
How do I programmatically trigger the resume/exit menu to pop up in FXGL ? 

I used to write my own dialog box in jfoenix but I'd like to switch to calling whatever method that's already built-in in FXGL to make it show up (normaly by hitting ESC).

Also, can that resume/exit menu be styled differently by css, etc. to match whatever theming style I have in mind ?

**Comment by AlmasB** [comment]
Currently, it isn't possible to do this directly from outside FXGL. However, you can trick FXGL into thinking that the menu key (ESC by default) was pressed:

```
Input input = FXGL.getInput();
input.mockKeyPress(KeyCode.ESCAPE);
input.mockKeyRelease(KeyCode.ESCAPE);
```

Some notes regarding FXGL states.
The `input` object is from `PLAY` state and the menu key (e.g. ESC) will respond only if called from `PLAY` state. When you've called the above, FXGL will enter `PAUSED` state, which runs in its own loop (each state has its own timer, input, view, loop, etc.).

As for styling, the issue #329 is about that mostly and hasn't been implemented yet.
