### ISSUE TITLE
borderless window

### ISSUE THREAD

**Issue by mokun** [AlmasB/FXGL#429]
How do I make my window borderless ?

In JavaFX, I can do `stage.initStyle(StageStyle.UNDECORATED)` to make the title bar and the top right buttons go away in the stage

Similarly, I try to do `((Stage)gameScene.getRoot().getScene().getWindow()).initStyle(StageStyle.UNDECORATED)`. But 
I have a NullPointerException.

>        root = new Group();
>        root.getChildren().add(applicationArea);
>        root.getChildren().add(stackPane);
>        root.getChildren().add(closeApp);
>        root.getChildren().add(rootPane);              
>        gameScene.addUINode(root);
>        ((Stage) gameScene.getRoot().getScene().getWindow()).initStyle(StageStyle.UNDECORATED);

**Comment by AlmasB** [comment]
`initStyle` (I think) only works before the window is shown, as such currently there is no way to achieve that. The feature is not enabled by design, as I can't see a use case (yet). When in window mode, the controls will be available, so the game can be closed from the OS. When the fullscreen mode is supported, the game will enter fullscreen and either be scaled up or down.

**Comment by AlmasB** [comment]
If you do need undecorated stage, how about hiding the stage then settings style and finally showing the stage again?

**Comment by mokun** [comment]
> hiding the stage...

I have a game menu that implements its own close button and mouse events for dragging. It's still within a window. So I painstakingly get rid of the "squared" window border and create a round border. See pic below :

![mainmenuroundborder](https://user-images.githubusercontent.com/1168584/32865307-61ffecfa-ca17-11e7-98e6-6513e89fc68d.png)

But if I use FXGL with `gameScene.addUINode(root)`  instead of instantiating a new Scene and Stage in JavaFX , the normal square border of FXGL would be behind the main menu. See pic below :

![mainmenusquareborder](https://user-images.githubusercontent.com/1168584/32865453-13804358-ca18-11e7-9d73-a50523384492.png)

That's why I want to get rid of the border in FXGL if there's a way to do it.

**Comment by mokun** [comment]
> The feature is not enabled by design, as I can't see a use case (yet). 

I can think of the case for a game menu in which I only need to design how to nicely arrange the placement of various items inside a redefined 1024 x 768 box.

It will add a lot more work for me to write codes to programmatically rearrange all the items inside the game menu when the game menu's window is going to be stretched to whatever user's monitor's resolutio.

**Comment by AlmasB** [comment]
I see. `initStyle` can be called only before the stage is visible. FXGL will make it visible from the start, so what you can try and use as a workaround for now:

1. Obtain a reference to FXGL stage, I think you already have it
2. call `stage.hide()`
3. call `stage.initStyle( undecorated ...)`
4. call `stage.show()`

I do not know if this will work, but I'm happy to add borderless window as a feature.

> stretched to whatever user's monitor's resoluti

1024 x 768 would be scaled, **not** stretched

**Comment by mokun** [comment]
Unfortunately, I get NullPointerException on the value of scene. 
I tested its value and it did print `scene is null`.
Originally, I have `Scene scene = new Scene(root); ` But with FXGL, it's not needed and is replaced by `gameScene.addUINode(root)`

```
root.getChildren().add(rootPane);              
gameScene.addUINode(root);
Scene scene = (Scene) gameScene.getContentRoot().getScene();
if (scene == null) System.out.println("scene is " + scene);
javafx.stage.Window window = scene.getWindow();
Stage stage = (Stage) window;
stage.hide();
stage.initStyle(StageStyle.UNDECORATED);
...
...
...
stage.show();
```

**Comment by mokun** [comment]
> initStyle can be called only before the stage is visible.

True. In my app with FXGL, I never need to call stage.show() to show the window. It's done automatically after calling `gameScene.addUINode(root);`

At what point will the value of scene become not null ?

**Comment by AlmasB** [comment]
Just before the stage is shown. Anyway, I think the best course of action is to wait for this issue to be resolved, rather than spending time on workarounds. I'll see if I can fix this by end of today. Cheers

**Comment by AlmasB** [comment]
@mokun please use the latest build of the snapshot and you can use:
```
settings.setStageStyle(StageStyle.UNDECORATED);
```

**Comment by mokun** [comment]
Thanks. I'm using `settings.setStageStyle(StageStyle.UNDECORATED) ` now to get rid of the default window border. 

However, I'm still NOT able to create a drop shadow around the window or even a round border style of my choice.

Normally, the first thing I do is to set `scene.setFill(Color.TRANSPARENT)` but in FXGL I have  NullPointerException.

How do I style the border of the stage or window in FXGL ? 

In JavaFX, I can do it in two ways, by coding it in javafx or by css.

Below, I'm trying to do it using the css using the main.css from https://pixelduke.wordpress.com/2012/09/09/style-a-stage-in-a-minimalist-way/ 

```
getGameScene().addUI(fxmlUI);
Scene scene = getGameScene().getRoot().getScene();
scene.setFill(Color.TRANSPARENT);
scene.getStylesheets().add(this.getClass().getResource("main.css").toExternalForm());
```

It looks like I also have trouble loading the css file. How do I do that ?

**Comment by AlmasB** [comment]
@mokun you can use `getGameScene().appendCSS(getAssetLoader().loadCSS("main.css"));`. `main.css` must be placed in `assets/ui/css/`. If you want to override FXGL styling completely, you can probably do something like (did not check):
```
CSS css = getAssetLoader().loadCSS("main.css");
getGameScene().getRoot().getStylesheets().setAll(css.getExternalForm());
```
