### ISSUE TITLE
Resume button not working on the exit dialog

### ISSUE THREAD

**Issue by mokun** [AlmasB/FXGL#432]
I just tested using mockKeyPress() and mockKeyRelease() on the ESC key from [issue #427](https://github.com/AlmasB/FXGL/issues/427) and it works. Thanks!

However, I encounter two issues :  
(1). [Minor] The exit button would shut down the UI part of the app but it doesn't do a CLEAN exit because it doesn't call  `System.exit(0)` to quit the app..
(2). [Major] The resume button doesn't work well.

For (1), I'm testing if calling `Platform.setImplicitExit(true)` when initializing the app would work. This way, the behavior of JavaFX runtime will be changed to implicitly shutdown when the last window is closed.

I'm looking at GameApplication's exit() and it does have `Platform.exit()` but you may have the reason not to include System.exit(0) if there are background tasks that are not finished. In my app's exit dialog box, I have both.

```
    /**
     * Exit the application.
     */
    protected final void exit() {
        log.debug("Exiting game application");
        exitListeners.forEach(ExitListener::onExit);
        log.debug("Shutting down background threads");
        getExecutor().shutdownNow();
        if (getSettings().isProfilingEnabled()) {
            profiler.print();
        }
        log.debug("Exiting FXGL");
        FXGL.destroy();
        log.debug("Closing logger and exiting JavaFX");
        Logger.close();
        Platform.exit();
    }
```

On (2), if I hit the ESC again while the exit dialog is on display, the app will resume normally.

However, when I click on the resume button, the app doesn't resume properly, namely, the FXGL main thread would pause and a JavaFX's Timeline instance would actually be paused (instead of being resumed). 

I would actually have to hit ESC to bring up the FXGL's exit dialog again and hit resume button again to resume the main thread and the timeline.

`Timeline timeline = new Timeline(new KeyFrame(Duration.millis(TIME_DELAY), ae -> updateTimeLabels()));
`

I'm looking at AppStateMachine.java and it seems there's a bug that cause the resume button to do just the opposite thing.

I'm hoping that hitting the resume should be no different than hitting the ESC again while the exit dialog is on display as the app will resume normally this way.

**Comment by AlmasB** [comment]
1) FXGL cleans up after itself, so when users write code with FXGL as a framework they do not need to worry about `System.exit();`. I highly recommend that you use FXGL executors / async capabilities to avoid the need for explicit system shutdown. Let me know if this is not an option for you, preferably with a use case.

2) I have tried it and it works normally in both mocked version and natural. Can you provide a minimal example that I can run?

**Comment by mokun** [comment]
My fault. The resume button does work the way it's supposed to. I just have to comment out a block of codes responsible for detecting the ESC and pausing the app. Appreciate. Issues closed.
