### ISSUE TITLE
Extract all hardcoded text into localized strings and add translations

### ISSUE THREAD

**Issue by AlmasB** [AlmasB/FXGL#446]
- [ ] Extract hardcoded text
- [ ] Translate text to other languages (need people who speak **French** and **German**), translations to other languages are also welcome

**Comment by ZacharyDSturtz** [comment]
Hello, @AlmasB !

My name is Zach, and I would like to start contributing to FXGL. I've decided that I should start with a smaller issue before slowly building up both my credibility and experience, and this seems like a good start. While not being a native German speaker, I have taken 2 semesters of German in university, thus granting me some modicum of experience in that regard.

This being the case, I have taken a look at german.properties in fxgl-base/resources/assets/properties/languages, and I have confidence to translate that file to some semblance of reasonable German. While the translation would not be perfect, it should be enough to get the message across to any German users. However, this issue states "extract all hardcoded text into localized strings." What hard-coded text, exactly? Would this include things such as the hard-coded text in the following lines?

        Text textMusic = FXGL.getUIFactory().newText("Music Volume: ");
        Text textSound = FXGL.getUIFactory().newText("Sound Volume: ");
        (FXGLMenu.java lines 390 and 397)

If so, how would I go about extracting said text into localized strings? I just started familiarizing myself with the system not too long ago, so I'm not quite sure about that yet.

Note: This would only be the German translations, for I have absolutely no ability to speak/understand French.

**Comment by AlmasB** [comment]
Hi, 

Yes these are examples of hardcoded text which need to be extracted and replaced. [An example](https://github.com/AlmasB/FXGL/blob/master/fxgl-base/src/main/java/com/almasb/fxgl/scene/FXGLMenu.java#L376) of a correct way to handle these strings.

Updating [german.properties](https://github.com/AlmasB/FXGL/blob/master/fxgl-base/src/main/resources/assets/properties/languages/german.properties) would be a good start. Then, identify all places where there's hardcoded text, like you've done above. Finally, come up with good symbolic names, e.g. (just an example) `menu.text.music.volume` and start replacing one by one. Let me know if this works for you.

**Comment by ZacharyDSturtz** [comment]
Okay, thank you. I'll start on translating german.properties and get to work on finding and extracting all localized strings I can find. Every time I add a new element to the german.properties file, would it be alright if I added that same element to the other .properties file but left it in English for someone else to translate later? That way we can avoid having odd errors for missing text.

**Comment by AlmasB** [comment]
I suggest the following plan:

1. Update german.properties only as it is and make this a single commit
2. Identify places where there's hardcoded text and dump all in the info with links or files and numbers (however you prefer) in this thread, so we can see what we're working with.
3. Together we can come up with new symbolic names
4. You can then start extracting strings and updating other .properties accordingly, which will make a second commit.
5. Make a pull request

**Comment by ZacharyDSturtz** [comment]
Okay, I'll do that. Thank you!

**Comment by ZacharyDSturtz** [comment]
I'm on the last word to translate in the german.properties file, and I have a quick question. Under what context is "restore" used? There are many different meanings that it can hold, so I need to know for a proper translation.

**Comment by AlmasB** [comment]
restore default settings

**Comment by ZacharyDSturtz** [comment]
Okay, thanks.

**Comment by ZacharyDSturtz** [comment]
Hey, so here are all of the hard-coded text entries I found by systematically looking through each file, excluding any intended for debugging, throwing errors and function calls such as toString(), throw new Exception(""), and log.warning(""), and "onDeath."

First, here are all of the entries I found that already have translations in the .properties files, but I don't think the translations are implemented properly. (If they are and I just missed the translation, then ignore this section)

        Button btnContinue = createActionButton("CONTINUE", this::fireContinue);
        Button btn1 = createActionButton("NEW GAME", this::fireNewGame);
        Button btn2 = createContentButton("LOAD", this::createContentLoad);
        Button btn3 = createContentButton("OPTIONS", () -> new MenuContent(makeOptionsMenu()));
        Button btn4 = createContentButton("EXTRA", () -> new MenuContent(makeExtraMenu()));
        Button btn5 = createActionButton("ONLINE", this::fireMultiplayer);
        Button btn6 = createActionButton("LOGOUT", this::fireLogout);
        Button btn7 = createActionButton("EXIT", this::fireExit);
        (CCTRMenu.java lines 84-91)

        Button btnContinue = createActionButton("RESUME", this::fireResume);
        Button btn1 = createActionButton("SAVE", this::fireSave);
        Button btn2 = createContentButton("LOAD", this::createContentLoad);
        Button btn3 = createContentButton("OPTIONS", () -> new MenuContent(makeOptionsMenu()));
        Button btn4 = createContentButton("EXTRA", () -> new MenuContent(makeExtraMenu()));
        Button btn5 = createActionButton("MAIN MENU", this::fireExitToMainMenu);
        (CCTRMenu.java lines 134-139)

        Button btnGameplay = createContentButton("GAMEPLAY", this::createContentGameplay);
        Button btnControls = createContentButton("CONTROLS", this::createContentControls);
        Button btnVideo = createContentButton("VIDEO", this::createContentVideo);
        Button btnAudio = createContentButton("AUDIO", this::createContentAudio);
        (CCTRMenu.java lines 166-169)

        Button btnCredits = createContentButton("CREDITS", this::createContentCredits);
        Button btnTrophies = createContentButton("TROPHIES", this::createContentAchievements);
        (CCTRMenu.java lines 175 and 176)

        ToggleButton tb1 = new ToggleButton("MAIN MENU");
        ToggleButton tb2 = new ToggleButton("OPTIONS");
        ToggleButton tb3 = new ToggleButton("EXTRA");
        (GTAVMenu.java lines 102-104)

        Button btnContinue = createActionButton("CONTINUE", this::fireContinue);
        Button btnNew = createActionButton("NEW GAME", this::fireNewGame);
        Button btnLoad = createContentButton("LOAD GAME", this::createContentLoad);
        Button btnLogout = createActionButton("LOGOUT", this::fireLogout);
        Button btnExit = createActionButton("EXIT", this::fireExit);
        (GTAVMenu.java lines 133-137)

        Button btnResume = createActionButton("RESUME", this::fireResume);
        Button btnSave = createActionButton("SAVE", this::fireSave);
        Button btnLoad = createContentButton("LOAD", this::createContentLoad);
        Button btnExit = createActionButton("EXIT", this::fireExitToMainMenu);
        (GTAVMenu.java lines 145-148)

        Button btnGameplay = createContentButton("GAMEPLAY", this::createContentGameplay);
        Button btnControls = createContentButton("CONTROLS", this::createContentControls);
        Button btnVideo = createContentButton("VIDEO", this::createContentVideo);
        Button btnAudio = createContentButton("AUDIO", this::createContentAudio);
        (GTAVMenu.java lines 154-157)

        Button btnCredits = createContentButton("CREDITS", this::createContentCredits);
        Button btnTrophies = createContentButton("TROPHIES", this::createContentAchievements);
        (GTAVMenu.java lines 163 and 164)

        val itemContinue = createActionButton("CONTINUE", { fireContinue() })
        val itemNewGame = createActionButton("NEW GAME", { fireNewGame() })
        val itemExit = createActionButton("EXIT", { fireExit() })
        (Warcraft3Menu.kt lines 93-95)

        val btnDelete = FXGL.getUIFactory().newButton("DELETE")
        (MenuEventHandler.kt line 283)

        val btnResume = FXGL.getUIFactory().newButton("RESUME")
        (PauseMenuSubState.kt line 102)

        val btnExit = FXGL.getUIFactory().newButton("EXIT")
        (PauseMenuSubState.kt line 108)

Those are all of the entries with existing translations that I found. The next section is entries intended for the "developer," I'm not quite sure if we still want this translated, so I'm recording it here for you to decide upon.

        app.getDisplay().showConfirmationBox("Exit?", yes -> { ... }
        (DeveoperMenuBarController.java line 62)

        MDIWindow window = new InGameWindow("Add Entity", InGameWindow.WindowDecor.ALL);
        (DeveoperMenuBarController.java line 71)

        MDIWindow window = new InGameWindow("Edit Entity", InGameWindow.WindowDecor.ALL);
        (DeveoperMenuBarController.java line 81)

        MDIWindow window = new InGameWindow("Color Adjust", InGameWindow.WindowDecor.ALL);
        (DeveoperMenuBarController.java line 96)

Next are the entries without translations that I don't think are intended for the developer, but I'm not quite sure if they need translating at all. Are these hard-coded strings used for another purpose than display?

         .bbox(new HitBox("LEFT",  new Point2D(-thickness, 0), box(thickness, h)))
         .bbox(new HitBox("RIGHT", new Point2D(w, 0), box(thickness, h)))
         .bbox(new HitBox("TOP",   new Point2D(0, -thickness), box(w, thickness)))
         .bbox(new HitBox("BOT",   new Point2D(0, h), box(w, thickness)))
        (Entities.java lines 56-59)

        .then(n -> FS.writeDataTask(Collections.singletonList("This directory contains user profiles."), 
              PROFILES_DIR + "Readme.txt"))
        (SaveLoadManager.java line 51)

        .then(n -> FS.writeDataTask(Collections.singletonList("This directory contains save files."), saveDir() +                    
              "Readme.txt"))
        (SaveLoadManager.java line 150)

Next are the entries without translations that I am almost positive require them.

         .runAsyncFXWithDialog(new ProgressDialog("Loading save files"));
        (SaveLoadManager line 91)

        app.getDisplay().showConfirmationBox("Settings will be restored to default", yes -> {
        (FXGLDefaultMenu.java line 213)

        Text text = FXGL.getUIFactory().newText("PRESS ANY KEY", 24);
        (FXGLMenu.java line 301)

        Button btnFixRatio = FXGL.getUIFactory().newButton("Fix Ratio");
        (FXGLMenu.java line 359)

        vbox.getChildren().add(new HBox(25, FXGL.getUIFactory().newText("Fullscreen: "), cbFullScreen));
        (FXGLMenu.java line 372)

        Text textMusic = FXGL.getUIFactory().newText("Music Volume: ");
        (FXGLMenu.java line 390)

        Text textSound = FXGL.getUIFactory().newText("Sound Volume: ");
        (FXGLMenu.java line 397)

        credits.add("Powered by FXGL " + FXGL.getProperties().getString(FXGL_VERSION));
        credits.add("Author: Almas Baimagambetov");
        (FXGLMenu.java lines 427 and 428)

        FXGL.getUIFactory().newText("Choose your feedback method", Color.WHEAT, 18),
        (FXGLMenu.java line 462)

        .runAsyncFXWithDialog(ProgressDialog("Loading..."))
        (MenuEventHandler.kt line 79)

        .runAsyncFXWithDialog(ProgressDialog("Saving data: $saveFileName"))
        (MenuEventHandler.kt line 93)

        app.display.showInputBoxWithCancel("Enter save file name", InputPredicates.ALPHANUM, Consumer                     
              { saveFileName ->
        (MenuEventHandler.kt line 97)

        app.display.showConfirmationBox("Overwrite save [$saveFileName]?", { yes ->
        (MenuEventHandler.kt line 103)

        app.display.showConfirmationBox("Load save [${saveFile.name}]?\nUnsaved progress will be lost!", { 
              yes ->
        (MenuEventHandler.kt line 115)

        .runAsyncFXWithDialog(ProgressDialog("Loading: ${saveFile.name}"))
        (MenuEventHandler.kt line 121)

        app.display.showConfirmationBox("Delete save [${saveFile.name}]?", { yes ->
        (MenuEventHandler.kt line 127)

        .runAsyncFXWithDialog(ProgressDialog("Deleting: ${saveFile.name}"))
        (MenuEventHandler.kt line 132)

        app.display.showConfirmationBox("Log out?", { yes ->
        (MenuEventHandler.kt line 138)

        app.display.showConfirmationBox("Exit to Main Menu?\nUnsaved progress will be lost!", { yes ->
        (MenuEventHandler.kt line 160)

        .onFailure { error -> log.warning("Failed to save profile: ${profileName.value} - $error") }
        (MenuEventHandler.kt line 243)

        val btnHost = FXGL.getUIFactory().newButton("Host")
        (MenuEventHandler.kt line 251)

        .runAsyncFXWithDialog(ProgressDialog("Hosting Game"))
        (MenuEventHandler.kt line 257)

        val btnConnect = FXGL.getUIFactory().newButton("Connect...")
        (MenuEventHandler.kt line 260)

        app.display.showInputBox("Enter Server IP", {
        (MenuEventHandler.kt line 262)

        .runAsyncFXWithDialog(ProgressDialog("Connecting to Game"))
        (MenuEventHandler.kt line 266)

        app.display.showBox("Multiplayer Options", FXGL.getUIFactory().newText(""), btnHost, btnConnect)
        (MenuEventHandler.kt line 270)

        val btnNew = FXGL.getUIFactory().newButton("NEW")
        val btnSelect = FXGL.getUIFactory().newButton("SELECT")
        (MenuEventHandler.kt lines 280 and 281)

        app.display.showInputBox("New Profile", InputPredicates.ALPHANUM, Consumer { name ->
        (MenuEventHandler.kt line 287)

        app.display.showErrorBox("Profile is corrupted: $name", { showProfileDialog() })
        app.display.showErrorBox("Profile is corrupted: $name\nError: $error", { this.showProfileDialog() })
        (MenuEventHandler.kt lines 306 and 317)

        .runAsyncFXWithDialog(ProgressDialog("Loading last save file"))
        (MenuEventHandler.kt line 313)

        .runAsyncFXWithDialog(ProgressDialog("Loading Profile: $name"))
        (MenuEventHandler.kt line 319)

        .runAsyncFXWithDialog(ProgressDialog("Deleting profile: $name"))
        (MenuEventHandler.kt line 328)

        app.display.showBox("Select profile or create new", profilesBox, btnSelect, btnNew, btnDelete)
        app.display.showBox("Select profile or create new", profilesBox, btnSelect, btnNew, btnDelete)
        (MenuEventHandler.kt lines 339 and 344)

        .runAsyncFXWithDialog(ProgressDialog("Loading profiles"))
        (MenuEventHandler.kt lines 346)

        FXGL.getNotificationService().pushNotification(if (ok) "Screenshot saved" else "Screenshot failed")
        (SystemActions.kt line 40)

        pushNotification("You got an achievement! ${event.achievement.name}")
        (NotificationServiceProvider.kt line 54)

        pushNotification("Achievement " + event.achievement.name + "\n"
        + "Progress: " + (event as AchievementProgressEvent).value + "/" + event.max)
        (NotificationServiceProvider.kt lines 56 and 57)

Those are all of the hard-coded entries that might need translations that I could find. However, I did not look through the sample files because I believe they are intended for testing purposes only and therefore do not need translations.

**Comment by AlmasB** [comment]
This is very impressive! I appreciate you being thorough. Yes, you are right fxgl-samples module is just for demo purposes. I think we should start from the bottom list, as it indeed features text that needs to be extracted. I'm happy for you to have a go at coming up with symbolic names, which (once ready) we could go through together. For example, starting with item number 1 in your bottom list:

```
 .runAsyncFXWithDialog(new ProgressDialog("Loading save files"));
    (SaveLoadManager line 91)
```

could be:

```
loading.save.files = Loading save files
```

Unless you want to propose a different approach

**Comment by ZacharyDSturtz** [comment]
Okay, I've finished adding the new translation entries to the german.properties file without actually providing translations. What do you think?

#
# FXGL - JavaFX Game Library. The MIT License (MIT).
# Copyright (c) AlmasB (almaslvl@gmail.com).
# See LICENSE for details.
#

#
# Dialog text (as translated by Google)
#

dialog.exitGame = Beenden?
dialog.yes = JA
dialog.no = NEIN
dialog.ok = OK
dialog.cancel = ABBRECHEN

#
# Menu text (as translated by Zach)
#

menu.language = SPRACHE
menu.continue = FORTFAHREN
menu.resume = FORTSETZEN
menu.newGame = NEUES SPIEL
menu.save = SPEICHERN
menu.load = LADEN
menu.extra = EXTRA
menu.online = ONLINE
menu.video = VIDEO
menu.audio = AUDIO
menu.credits = CREDITS
menu.options = OPTIONEN
menu.logout = ABMELDEN
menu.exit = BEENDEN
menu.mainMenu = HAUPTMENÜ
menu.restore = WIEDERHERSTELLEN
menu.gameplay = SPIEL
menu.controls = KONTROLLEN
menu.trophies = TROPHÄEN
menu.feedback = RÜCKMELDUNG
menu.back = ZURÜCK
menu.delete = LÖSCHEN
menu.difficulty = SCHWIERIGKEIT
# everything above this is already translated, everything below needs review so it has yet to be translated.
menu.music = Music Volume
menu.sound = Sound Volume
menu.fullscreen = Fullscreen
menu.fixRatio = Fix Ratio
menu.settingsRestore = Settings will be restored to default

#
# UNKNOWN CATEGORY text, please assign to categories!
#

unknown.exit = Exit to Main menu?
unknown.logOut = Log out?

#
# Miscellaneous text
#

miscellaneous.unsavedProgress = \nUnsaved progress will be lost! <-- misc because used in 2 categories
miscellaneous.feedback = Choose your feedback method
miscellaneous.poweredBy = Powered by
miscellaneous.author = Author
miscellaneous.pressAnyKey = PRESS ANY KEY

#
# Multiplayer text
#

multiplayer.new = NEW
multiplayer.select = SELECT
multiplayer.options = Multiplayer Options
multiplayer.connect = Connect...
multiplayer.connecting = Connecting to Game
multiplayer.host = Host
multiplayer.hosting = Hosting Game
multiplayer.enterIp = Enter Server IP

#
# File text
#

file.load = Load save
file.loading = Loading...
file.loadingSingle = Loading
file.loadingMulti = Loading save files
file.loadingLast = Loading last save file
file.delete = Delete save
file.deleting = Deleting
file.overwrite = Overwrite save
file.enterSaveName = Enter save file name
file.saving = Saving data

#
# Profile text
#

profile.selectOrCreate = Select profile or create new
profile.loading = Loading profile
profile.loadingMulti = Loading profiles
profile.deleting = Deleting profile
profile.corrupted = Profile is corrupted
profile.new = New profile
profile.failedSave = Failed to save profile

#
# Screenshot text
#

screenshot.saved = Screenshot saved
screenshot.failed = Screenshot failed

#
# Achievement text
#

achievement.achievement = Achievement
achievement.progress = Progress
achievement.receive = You got an achievement!

**Comment by AlmasB** [comment]
Please see below, I've removed a few and renamed a few so that it's clearer from the symbolic name alone. I'm happy for this to proceed to the implementation stage if you are happy with the changes.

```
dialog.exitGame = Beenden?
dialog.yes = JA
dialog.no = NEIN
dialog.ok = OK
dialog.cancel = ABBRECHEN




menu.language = SPRACHE
menu.continue = FORTFAHREN
menu.resume = FORTSETZEN
menu.newGame = NEUES SPIEL
menu.save = SPEICHERN
menu.load = LADEN
menu.extra = EXTRA
menu.online = ONLINE
menu.video = VIDEO
menu.audio = AUDIO
menu.credits = CREDITS
menu.options = OPTIONEN
menu.logout = ABMELDEN
menu.exit = BEENDEN
menu.mainMenu = HAUPTMENÜ
menu.restore = WIEDERHERSTELLEN
menu.gameplay = SPIEL
menu.controls = KONTROLLEN
menu.trophies = TROPHÄEN
menu.feedback = RÜCKMELDUNG
menu.back = ZURÜCK
menu.delete = LÖSCHEN
menu.difficulty = SCHWIERIGKEIT
menu.music.volume = Music Volume
menu.sound.volume = Sound Volume
menu.fullscreen = Fullscreen
menu.fixRatio = Fix Ratio
menu.settingsRestore = Settings will be restored to default
menu.exitMainMenu = Exit to Main menu?
menu.logOut = Log out?
menu.unsavedProgress = Unsaved progress will be lost!
menu.feedback = Choose your feedback method
menu.pressAnyKey = PRESS ANY KEY



multiplayer.new = NEW
multiplayer.select = SELECT
multiplayer.options = Multiplayer Options
multiplayer.connect = Connect...
multiplayer.connecting = Connecting to Game
multiplayer.host = Host
multiplayer.hosting = Hosting Game
multiplayer.enterIp = Enter Server IP

file.load = Load save
file.loading = Loading
file.loadingSaveFiles = Loading save files
file.loadingLast = Loading last save file
file.deleteSave = Delete save
file.deleting = Deleting
file.overwrite = Overwrite save
file.enterSaveName = Enter save file name
file.savingData = Saving data

profile.selectOrCreate = Select profile or create new
profile.loadingProfile = Loading profile
profile.loadingProfiles = Loading profiles
profile.deletingProfile = Deleting profile
profile.corrupted = Profile is corrupted
profile.new = New profile
profile.failedToSave = Failed to save profile


dev.screenshotSaved = Screenshot saved
dev.screenshotFailed = Screenshot failed


achievement.achievement = Achievement
achievement.progress = Progress
achievement.receive = You got an achievement!
```

**Comment by ZacharyDSturtz** [comment]
Alright. I'll start implementing with those changes.

**Comment by ZacharyDSturtz** [comment]
Hey, I have a quick question. The "Fix Ratio" button, what ratio is it talking about? Aspect ratio, or something else?

**Comment by ZacharyDSturtz** [comment]
Additional question, I've been translating as if the system is "informally" speaking to the user. Should I instead write formal translations?

**Comment by ZacharyDSturtz** [comment]
Okay, I just finished adding all of the entries into the other language files along with the proper German translations in german.properties. While not perfect, I believe a typical German should be able to understand what I have written. I do, however, recommend that you find someone that can fluently speak German to review my work.

Next up I shall focus on actually implementing the translations in the files I have referenced above. Once done, I'll commit and make a pull request.

**Comment by AlmasB** [comment]
Great! Sounds good. Note that we don’t always need localizedStringProperty,
it is only for things that are pre made, like menu items text. For text
that is only shown briefly, like “saving data” progress dialog, it’s
probably better to use getLocalizedString, as this doesn’t create an
observable property

**Comment by ZacharyDSturtz** [comment]
pushNotification is presumably also brief. In that case, should I use getLocalizedString there also?

**Comment by ZacharyDSturtz** [comment]
Okay, so for every ProgressDialog and pushNotification I've been writing getLocalizedString() and everything else I've been writing localizedStringProperty(). Is that what you had in mind? 

When input/error boxes come up, I leave that as localizedStringProperty even though it's temporary because it can stay on the screen theoretically indefinitely. Should I instead use getLocalizedString()? 

For menu buttons I always use localizedStringProperty().

Here's an example of a new function with the extracted hard-coded strings:

    private fun showMultiplayerDialog() {
        val btnHost = FXGL.getUIFactory().newButton(FXGL.localizedStringProperty("multiplayer.host").value)
        btnHost.setOnAction {
            FXGL.getNet()
                    .hostMultiplayerTask()
                    .onSuccess { onNewGame() }
                    .onFailure { app.display.showErrorBox(it) }
                    .runAsyncFXWithDialog(ProgressDialog(FXGL.getLocalizedString("multiplayer.hosting")))
        }

        val btnConnect = FXGL.getUIFactory().newButton(FXGL.localizedStringProperty("multiplayer.connect").value)
        btnConnect.setOnAction {
            app.display.showInputBox(FXGL.localizedStringProperty("multiplayer.enterIp").value, {
                FXGL.getNet()
                        .connectMultiplayerTask(it)
                        .onSuccess { onNewGame() }
                        .runAsyncFXWithDialog(ProgressDialog(FXGL.getLocalizedString("multiplayer.connecting")))
            })
        }

        app.display.showBox(FXGL.localizedStringProperty("multiplayer.options").value, FXGL.getUIFactory().newText(""), btnHost, btnConnect)
    }

Do you see any problems?

**Comment by ZacharyDSturtz** [comment]
So, for buttons, rather than 

            Button btnFixRatio = FXGL.getUIFactory().newButton(FXGL.localizedStringProperty("menu.fixRatio"));

I should write

            Button btnFixRatio = FXGL.getUIFactory().newButton("Fix Ratio");
            btnFixRatio.textProperty().bind(FXGL.localizedStringProperty("menu.fixRatio"));

Is this correct?

**Comment by AlmasB** [comment]
You can create another function for newButton that takes property, similar
to newText. I will review these after work today. Thanks

**Comment by ZacharyDSturtz** [comment]
Hey, so I finished implementing it and, as far as I can tell with the limited samples, everything works beautifully. Almost. There's one small problem with the German translations,

![dialogproblem](https://user-images.githubusercontent.com/31866633/40192339-e1b377ba-59b8-11e8-8533-38711b35951b.png)

As you can see, the umlauts (Ü, ü, Ö, ö, Ä, ä), and presumably the Eszett (ß), do not register properly as text, but rather as question mark symbols. How should we go about rectifying this?

**Comment by AlmasB** [comment]
I think the issue is related to what encoding is used. In UTF-8 it should be fine, I'd say check your IDE first

**Comment by ZacharyDSturtz** [comment]
Okay! I thought I had it set to UTF-8, which is why I was confused. I'll check again, thanks.

After this works, then I think I'll be just about ready to make a pull request.

**Comment by ZacharyDSturtz** [comment]
Alright, it's working now.

![mainmenucreditsssample](https://user-images.githubusercontent.com/31866633/40193776-1d059f10-59bd-11e8-97cd-4f4bf0313547.png)


![creditssampleworks](https://user-images.githubusercontent.com/31866633/40193735-0097ce0c-59bd-11e8-8870-53158f5bbdf9.png)

I'm now going to make the pull request so you can review it at your leisure.

**Comment by AlmasB** [comment]
Done in #542
