### ISSUE TITLE
Reuse of FXGL unit tests in applications

### ISSUE THREAD

**Issue by coldwarrl** [AlmasB/FXGL#451]
Currently, it is not possible to use any artifact in FXGL's test package in your own (game) application unit test code.
The default maven build does not include those, see [https://maven.apache.org/plugins/maven-jar-plugin/examples/create-test-jar.html](url) for details.

It should be checked:

- Shall FXGL include an API for leveraging unit tests in applications (e.g. for mocking, see [FXGLMock](https://github.com/AlmasB/FXGL/blob/bb5063baab7026c2d4d4e69beae0c1b4515d0ce3/fxgl/src/test/kotlin/com/almasb/fxgl/app/FXGLMock.kt))
- If so probably an own test project should be extracted, that is the sources of the test package would be moved to an own maven project (see linked maven docu)
- The wiki shall include in any case a best practice guidance for writing unit tests in applications, since unit tests are required for any non-trivial, long-term game development implementations

**Comment by AlmasB** [comment]
[This answer](https://stackoverflow.com/questions/174560/sharing-test-code-in-maven) seems useful

**Comment by AlmasB** [comment]
Done via test classifiers. To pull in deps:
```
        <!-- Pull in common test classes from fxgl-core -->
        <dependency>
            <groupId>com.github.almasb</groupId>
            <artifactId>fxgl-core</artifactId>
            <version>${fxgl.version}</version>
            <classifier>tests</classifier>
            <type>test-jar</type>
            <scope>test</scope>
        </dependency>
```
