### ISSUE TITLE
Javadoc

### ISSUE THREAD

**Issue by AndrewUTTroyes** [AlmasB/FXGL#453]
Hi !
I have a project with your framework and differents files in java/kotlin.
I use java 9 and I can't create the javadoc/KDoc with dokka.
I would like to know how did you do if it's possible.

Kind regards

**Comment by AlmasB** [comment]
Hi, during the build fxgl only runs the maven-javadoc tool, Kotlin doc is not included. However, Kotlin sources are, essentially carrying the doc with them (I hope), but no I haven't managed to unify them, yet and I don't know what form they will take.
