### ISSUE TITLE
Support TMX XML format

### ISSUE THREAD

**Issue by gabre** [AlmasB/FXGL#454]
It would be good to support TMX XML format as it is more widely used than JSON.

**Comment by AlmasB** [comment]
[Official tmx parser](https://github.com/bjorn/tiled/tree/master/util/java/libtiled-java) as a good starting point. I'll see if this can be done for 0.4.3

**Comment by AlmasB** [comment]
The majority of the format is now supported. Please see if your use case is covered. You can use `0.4.3-SNAPSHOT` early access.

The tmx file must be under `/assets/tmx/` with any tilesets under `/assets/textures/`

**Comment by AlmasB** [comment]
This is completed in 0.4.3
