### ISSUE TITLE
Add support for latest version of Tiled and extra tags

### ISSUE THREAD

**Issue by AlmasB** [AlmasB/FXGL#457]
The Tiled [website](http://www.mapeditor.org/). Current support is limited to basic tags, better support is covered by this issue.

**Comment by bturner1273** [comment]
I NEED THIS^^^ 
Tiled doesn't have macOS versions of the earlier releases available, therefore it is kind of hard to use tiled maps at all if you are developing on a mac

**Comment by AlmasB** [comment]
What about [1.0.1](https://github.com/bjorn/tiled/releases/tag/v1.0.1)

**Comment by bturner1273** [comment]
Nope no macOS release. I have been sending the .json files from a separate windows computer

**Comment by bturner1273** [comment]
there is a problem with the infinite tag that tiled introduced, FXGL isn't ignoring it

**Comment by AlmasB** [comment]
Ok. This is easier to manage. I'll see if I can get it done for 0.4.2 release

**Comment by bturner1273** [comment]
You’re fantastic keep it up!

**Comment by AlmasB** [comment]
Can you provide a minimal example of the Tiled .json file, so I can reproduce the issue and fix it. I don't think you need to add tilesets for this, probably an empty map from the latest Tiled will do. Thanks

**Comment by AlmasB** [comment]
@bturner1273 I have pushed `0.4.2-SNAPSHOT` to central. Can you update to this new version to see if you can use latest Tiled json format. Please note that new tags are still unsupported, they are just ignored, as I think the new format is incompatible with existing one. So the update would need to be planned carefully.

**Comment by bturner1273** [comment]
I am going to be completely honest in saying I have no clue how to set up
FXGL with the .xml I have been using the uber jars. Would I just copy the
pom.xml you have into mine? Also here is a .json from a new version of
tiled:

**Comment by AlmasB** [comment]
@bturner1273 You can find the latest build of 0.4.2-SNAPSHOT uber jar [here](https://github.com/AlmasB/builds/tree/master/fxgl). Let me know if it works with the latest Tiled .json, as well as with current .json that you already have.

**Comment by bturner1273** [comment]
@AlmasB works perfect for me! I appreciate the support!

**Comment by AlmasB** [comment]
@bturner1273 #454 is now also complete, in case you need up-to-date TMX support for Tiled. The latest build is [here](https://github.com/AlmasB/builds/blob/master/fxgl/fxgl-0.4.3-SNAPSHOT-uber.jar)

**Comment by bturner1273** [comment]
much appreciated!!
