### ISSUE TITLE
Get rid of profile select Dialog in custom menu

### ISSUE THREAD

**Issue by Polkasa** [AlmasB/FXGL#458]
Hello! How i can get rid of profile select dialog in custom menu ? It always appear, and i dont want to have this in my game
![przechwytywanie](https://user-images.githubusercontent.com/7520445/35480916-6df325ae-0419-11e8-9c39-8559783e6b98.PNG)

in scene factor i had example code:
```
    @NotNull
    @Override
    public FXGLMenu newMainMenu(GameApplication app) {
        return new FXGLMenu(app,MenuType.MAIN_MENU) {
            @Override
            protected Button createActionButton(String s, Runnable runnable) {
                return new FXGLButton("TEST");
            }

            @Override
            protected Node createBackground(double v, double v1) {
                return new Canvas();
            }

            @Override
            protected Node createTitleView(String s) {
                return new TextArea("test");
            }

            @Override
            protected Node createVersionView(String s) {
                return new TextArea("test");
            }

            @Override
            protected Node createProfileView(String s) {
                return new Button("test");
            }
        };
    }
```

**Comment by AlmasB** [comment]
Hi, profile selection is a core part of the menu, so if you enable menus, the profile dialog will be present. Currently, there is no way around that (except turning off menus).

I doubt we can remove profile selection as a whole, as the entire saving / loading mechanism is built on users having profiles (e.g. two or more people using the same PC). However, if you want the last used profile selected automatically, essentially speeding up the menu process, I'm happy to consider it.

**Comment by Polkasa** [comment]
Hi! Thanks for the answer! But in my case what should i do? My game is focus on multiplayer so i dont need save, load, profile selection, and also start game should have two inputs login and password. Is there a way to create a blank menu? I wanted to use this framework, because it is simply and clear for me :)

**Comment by AlmasB** [comment]
I would say this: turn off menus. This way fxgl will enter the "play state" immediately, which you can use as your start for the menu. So, essentially you are going to create a menu as part of the game, rather than use the built-in menu system, as clearly, it doesn't (cannot) do what you want. In addition, this approach gives you a lot of freedom to modify your menu in any way you want. I hope this is helpful.

**Comment by Polkasa** [comment]
Thank you very much for the answer :). I will  do it that way :)
