### ISSUE TITLE
Set InGamePanel to "disabled" when hidden

### ISSUE THREAD

**Issue by Polkasa** [AlmasB/FXGL#459]
I wanted to change the default action for key "Escape", how i can do this ?

**Comment by AlmasB** [comment]
You can replace ESC with a different menu key: `settings.setMenuKey(...)`. Then you should be able to assign an action to ESC normally through `getInput().addAction(...)`

**Comment by Polkasa** [comment]
Ok so i make setMenuKey to KeyCode.F10, and after that i do:
```
		input.addAction(new UserAction("Open/Close Main Menu") {
			@Override
			protected void onActionBegin() {
				System.out.println("DDD");
				if (mainMenuPanel.isVisible())
					mainMenuPanel.setVisible(false);
				else
					mainMenuPanel.setVisible(true);
			}
		}, KeyCode.ESCAPE);
```
But sadly when i click ESC key then nothings happen, when i change key for example to KeyCode.P then everythngs works fine, did is it a bug or i still doing something wrong?

**Comment by AlmasB** [comment]
It may be possible that ESC is reserved internally. I will check this some time today.

**Comment by Polkasa** [comment]
Ok, thanks! I will be waiting for your respnse

**Comment by AlmasB** [comment]
I've just checked, it works fine. Here's a minimal example (DSLkt is just a shortcut, behaves exactly the same input.addAction()):
```
public class EscSample extends GameApplication {

    @Override
    protected void initSettings(GameSettings settings) {
        settings.setWidth(800);
        settings.setHeight(600);
        settings.setTitle("EscSample");
        settings.setVersion("0.1");
        settings.setMenuKey(KeyCode.K);
    }

    @Override
    protected void initInput() {
        DSLKt.onKeyDown(KeyCode.ESCAPE, "escape", () -> System.out.println("print"));
    }

    public static void main(String[] args) {
        launch(args);
    }
}
```

**Comment by Polkasa** [comment]
Ok, so the problem is:
I had InGamePanel with colorpicker,  this colorpicker is visible(but panel is hidden outside of viewport). But sadly colorpicker took keyboard shortcuts(esc) because, app thinks that colorpicker is visible :). I suggest you to improve library by setting this InGamePanel to visible false, so then all components on panel will not collide with inputs. I hope you understood what i wrote ;)

**Comment by AlmasB** [comment]
I think I get the general idea of what you mean. Please provide a minimal example that I can run to see the issue, and hopefully fix it.

**Comment by Polkasa** [comment]
Hello! Sorry for long response, but im away from my computers last time. Ok so here is a minimal example:

```
import com.almasb.fxgl.app.GameApplication;
import com.almasb.fxgl.input.UserAction;
import com.almasb.fxgl.settings.GameSettings;
import com.almasb.fxgl.ui.InGamePanel;
import javafx.scene.control.ColorPicker;
import javafx.scene.input.KeyCode;

public class PanelBug extends GameApplication {
    private InGamePanel panel;
    private ColorPicker InGamePanelcolorPicker = new ColorPicker();

    @Override
    protected void initSettings(GameSettings settings) {
        settings.setWidth(800);
        settings.setHeight(600);
        settings.setTitle("PanelBug");
    }

    @Override
    protected void initInput() {
        getInput().addAction(new UserAction("Open/Close Panel") {
            @Override
            protected void onActionBegin() {
                if (panel.isOpen())
                    panel.close();
                else
                    panel.open();
            }
        }, KeyCode.TAB);
    }

    @Override
    protected void initUI() {
        panel = new InGamePanel();
        panel.getChildren().add(InGamePanelcolorPicker);
        getGameScene().addUINode(panel);
    }

    public static void main(String[] args) {
        launch(args);
    }
}
```

When u click "space" after example started then u can see that colorpicker opens, and i think it shouldnt happend. I fixed this in my app by adding diabled for panel when it is hidden

**Comment by AlmasB** [comment]
Ok. It is clear to me now. Yes I agree, it should be disabled when it's hidden.

**Comment by AlmasB** [comment]
Done in 0.4.3, you can use early access via `0.4.3-SNAPSHOT`
