### ISSUE TITLE
Freeze Rotation Not Available for Entity Physics Component

### ISSUE THREAD

**Issue by bturner1273** [AlmasB/FXGL#460]
Say I am making a platformer like mario, I need to constantly poll my player Entities rotation and negate it which gives it a wobbly PID controller-like effect. Is there a better solution to make sure mario wouldn't rotate in the physics simulation?

**Comment by AlmasB** [comment]
You should be able to obtain `body` using `getBody()` when the physics is ready and use `setFixedRotation(true)`. You can also do that before physics is set via `setBodyDef` and pass your specific body definition. Let me know if any of this works for you

**Comment by bturner1273** [comment]
^^The above method works!

**Comment by AlmasB** [comment]
If you think this issue has been solved, please close it. Thanks
