### ISSUE TITLE
How to enter next level?

### ISSUE THREAD

**Issue by Thom9521** [AlmasB/FXGL#463]
Hey I have followed your mario tutorial on youtube with Tiled. I want to load the next map(level 2) when my player touches the door. I'm guessing it's supposed to happen in the collisionhandler but im only able of loading the map without my player follows. 
Do you have any tips? :)

**Comment by AlmasB** [comment]
During level parsing, as it is a new level, all existing entities get removed from the world. To avoid this you can add `IrremovableComponent` to entities you do want removed, e.g. player in your case.

**Comment by Thom9521** [comment]
Ah thanks, now I came through the door with my player but without starting at the spawn position. I litterally spawn at the point where my door is from level 1. I have tried player.setPosition(); but without luck.

**Comment by AlmasB** [comment]
Please see [this](https://github.com/AlmasB/FXGL/wiki/Physics-World#repositioning-an-entity-with-physics)
