### ISSUE TITLE
Sticking to walls, box2d physics

### ISSUE THREAD

**Issue by Thom9521** [AlmasB/FXGL#467]
Hello. It's possible for my player to climb the walls and just sit at a point by keeping walking into it. Is there any way to change this? 

Example:

<img width="357" alt="eksempel" src="https://user-images.githubusercontent.com/31951107/35907817-48213ab8-0bef-11e8-9629-37c03b066929.png">

**Comment by AlmasB** [comment]
Hi, the issue lies in the box2d engine. Please see some links related to this issue:

- [objects sticking](http://box2d.org/forum/viewtopic.php?t=2630)
- [sticking to walls](https://stackoverflow.com/questions/5381399/how-can-i-prevent-a-ball-from-sticking-to-walls-in-box2d)
- [wall physics](https://gamedev.stackexchange.com/questions/10922/why-are-my-objects-becoming-permanently-stuck-to-walls-using-box2d)

Let me know if you figure out how to fix this using box2d, if FXGL API doesn't allow doing this, I'm happy to open an issue for it

**Comment by Thom9521** [comment]
Every post want's me to change b2_velocityThreshold to 0. But i have never heard of this. Do you know where I can find this? 😄

**Comment by AlmasB** [comment]
Everything related to box2d is [here](https://github.com/AlmasB/FXGL/tree/master/fxgl/src/main/java/com/almasb/fxgl/physics/box2d). See if you can run a search for that variable.

**Comment by Thom9521** [comment]
Yes right here in line 125 https://github.com/AlmasB/FXGL/blob/bb5063baab7026c2d4d4e69beae0c1b4515d0ce3/fxgl/src/main/java/com/almasb/fxgl/physics/box2d/common/JBoxSettings.java . But how do I change it tho?

**Comment by AlmasB** [comment]
Since it's public, you can change it just by:
```
JBoxSettings.velocityThreshold = 0;
```

**Comment by Thom9521** [comment]
Hmm it's not helping. Am I supposed to put the code a specific place?
(I have followed your mario tutorial on youtube, so I pretty much have the same Classes as you).

**Comment by AlmasB** [comment]
No, any place should do, e.g. in `initGame()`. See if you can find any more info on box2d forums.

**Comment by Thom9521** [comment]
Hi again. I haven't fixed my issue yet, but some forums want me to change the friction. But since it's a final class it's not possible for me. Do you know how I can change it? 
https://github.com/AlmasB/FXGL/blob/5a4d60401f5413c452ae1d365b316f93857faba0/fxgl/src/main/java/com/almasb/fxgl/physics/box2d/dynamics/FixtureDef.java

**Comment by AlmasB** [comment]
You don't need to change anything in FXGL code. It's an object, so `FixtureDef fd = new FixtureDef()`. Set appropriate values for its fields, then `physicsComponent.setFixtureDef(fd)`

**Comment by Thom9521** [comment]
Hi again. I haven't fixed my issue yet, but some forums want me to change the friction. But since it's a final class it's not possible for me. Do you know how I can change it? 
https://github.com/AlmasB/FXGL/blob/5a4d60401f5413c452ae1d365b316f93857faba0/fxgl/src/main/java/com/almasb/fxgl/physics/box2d/dynamics/FixtureDef.java

**Comment by Thom9521** [comment]
Thanks I will try it out :)

**Comment by AlmasB** [comment]
Has this been fixed? If yes, please can you post your solution here, so that others won't have to solve this again. Thanks

**Comment by Thom9521** [comment]
I wasen't able to find any solution. 😢

**Comment by AlmasB** [comment]
Ok. I'll keep this open, so I can refer to it if I find time to try and fix it.

**Comment by Thom9521** [comment]
Alright. Thanks for all you help though. I finished my study-project with the help of you tutorials and guiding. I listed you in my ReadMe so you got the credits 😃

**Comment by AlmasB** [comment]
This can be fixed by setting fixture def friction to 0 on the object being controlled, e.g. player.

```
PhysicsComponent comp = new PhysicsComponent();
comp.setFixtureDef(new FixtureDef().friction(0.0f));

...
```
