### ISSUE TITLE
Add ColoredTexture

### ISSUE THREAD

**Issue by AlmasB** [AlmasB/FXGL#468]
Sometimes it's useful to have a `texture` that is filled with a certain color:

```
new ColoredTexture(int width, int height, Color color);
```

**Comment by Valdar-Soft** [comment]
I think here we need a width and height parameter too.

**Comment by AlmasB** [comment]
Yes, good point. Updated example

**Comment by AlmasB** [comment]
Closed by [commit](https://github.com/AlmasB/FXGL/commit/c575bdc9af77b055c664ebf0c8c0c7592a0fd582). Thanks!
