### ISSUE TITLE
Mouse Hover

### ISSUE THREAD

**Issue by bturner1273** [AlmasB/FXGL#469]
How would I be able to tell if the mouse is hovering over something? My input.getMousePosition functions don't seem to be working so I can't hard code it. I have if statements in my initInput to check if w or the primary mouse button is held with print statements in them and the print statements never execute. Is there a way to tell if the mouse is colliding?

**Comment by bturner1273** [comment]
if I print the mouse position it prints it at the start of program execution and it is always 0,0. It never prints after that

**Comment by AlmasB** [comment]
1) `getInput().get ..` works, you must be creating a new Input object

2) `entity.getView().setOnMouse ...` - use javafx API, there is no FXGL wrapper since there is no clear advantage. If you can provide a use case and a strong argument towards such an API, I'm happy to open an issue for it.
