### ISSUE TITLE
Drawing

### ISSUE THREAD

**Issue by bturner1273** [AlmasB/FXGL#470]
How would I go about drawing things. For instance python has a turtle library where you can write pen up to stop drawing, pen down to start drawing and then give the "turtle" positions to go to kind of like a pen on paper. Is there an equivalent in fxgl? If there isn't I can just use the javafx line class and hard code some stuff but it seems like it might be a feature.

**Comment by AlmasB** [comment]
`getGameScene().getGraphicsContext()` which gives you access to the javafx 2d context. There is no need to wrap such an API as we don't have any extra or add new features, hence we end up with duplicated code.

**Comment by ram0973** [comment]
Is getGameScene().getGraphicsContext() exists today ?

**Comment by AlmasB** [comment]
In the latest version it no longer exists, however, it is easy to add:

```
Canvas c = new Canvas(w, h);
getGameScene().addUINode(c);

var g = c.getGraphicsContext();

// draw on g
```
