### ISSUE TITLE
RenderLayer problem

### ISSUE THREAD

**Issue by Polkasa** [AlmasB/FXGL#471]
OK, so i discovered that setRenderLayer function dont work for "addComponent" with "BiConsumer<GraphicsContext, Entity> drawing = (g2D, entity) -> {", with "setView" it works perfectly. Is there any solution to fix this? I need to use BiConsumer.

For example i add some entity at BACKGROUND and then another Entity on TOP(not setView, only addComponent with biconsumer) but unfonutley entity on top is before entity in background

PS in biconsumer i used drawImage, of course i remeber to add save and then restore betweeen drawImage, so what im doing wrong ?

**Comment by AlmasB** [comment]
It sounds like a bug + maybe a limitation. Entities that use views are drawn in the scene graph. Entities that are `Drawable` are drawn onto the graphics context, which sits in a `Canvas` after the entire scene graph. So we can observe that there is no way to mix them with this design.

We can't keep many `Canvas` nodes as it will result in a huge performance loss. So I think you've found a limitation in the FXGL rendering architecture.

Here's what you can do:

1) If your drawing to `GraphicsContext` is static, you can snapshot it into a `Node`, which you can use as a view.

2) Draw only using `GraphicsContext`. Currently, render layers are ignored (I think), so if you go down this approach, there's still this bug that needs to be fixed. I'll open an issue for it shortly.

Let me know if any of these approaches can work for you.

**Comment by Polkasa** [comment]
Sorry for long response. I refactored my code and used setView instead of addComponent and my problems are gone. Thanks for the answer

BTW.
FXGL is good work 👍
