### ISSUE TITLE
Tiled map - tile layer render performance

### ISSUE THREAD

**Issue by AlmasB** [AlmasB/FXGL#474]
This should probably be a single View with a Canvas (currently the only way I can think of we can relatively fast draw subsections of an Image). Then combine all tile layers into a single image. Bind that entity x and y to viewport. Finally, draw parts of the Image using viewport coordinates.

This may look similar to scrolling backgrounds, possible code reuse?

**Comment by ShowYourSkill** [comment]
Sorry for my shitty code :(
[RPG_Example.zip](https://github.com/AlmasB/FXGL/files/1741471/RPG_Example.zip)

**Comment by AlmasB** [comment]
Implementation notes and todo list:

- [ ] Merge multiple layers into one image data
- [ ] If the entire layer data is within max texture size (8192x8192?) generate the entire image and keep in memory (as currently done)
- [ ] It seems `WritableImage` offers better performance when clearing / copying image data. We still need to clear / draw transparent pixels when tile value is 0
- [ ] Optimization: If previous and current viewport areas overlap then copy image data from current buffer else redraw the buffer completely
