### ISSUE TITLE
Particle effects vs Image exploding

### ISSUE THREAD

**Issue by bturner1273** [AlmasB/FXGL#475]
So I am trying to make a brick breaker style game with boxes that actually break and explode. I have seen in one of your videos that you can do this in FXGL but I have not yet figured out how. I have an actual image I want to break into smaller pieces and have those pieces possibly break into pieces and go radially outward

**Comment by AlmasB** [comment]
[this](https://github.com/AlmasB/FXGL/blob/b7f1457851e7c40d047a07fe158315e5a3654833/fxgl-samples/src/main/java/sandbox/towerfall/TowerfallApp.java#L185) is the sample you are talking about. See if you can salvage any of the code from there
