### ISSUE TITLE
Replace null values with AppState.EMPTY

### ISSUE THREAD

**Issue by AlmasB** [AlmasB/FXGL#477]
GameApplication - Line 275 needs updating with EMPTY

and

AppStateMachine::getIntroState() and other methods needs updating as they currently check against null, i.e. they now need checking against EMPTY.

**Comment by Hanzallah** [comment]
Hi I am looking into this issue

**Comment by Hanzallah** [comment]
Can you assign this to me?

**Comment by AlmasB** [comment]
Sure, but GitHub doesn't allow assignees without push access as far as I'm aware.

**Comment by Hanzallah** [comment]
Thanks! I'm on it
