### ISSUE TITLE
Implement specific style class FXGLScrollPane

### ISSUE THREAD

**Issue by AlmasB** [AlmasB/FXGL#492]
We use JavaFX vanilla ScrollPane and restyle. We shouldn't alter vanilla classes and instead add a specific style class.

To solve this:

- [X] Create a class FXGLScrollPane
- [X] Update assets/ui/css/fxgl_dark.css accordingly 
- [X] Also for Spinner

**Comment by AlmasB** [comment]
- [ ] Also for Spinner

**Comment by Valdar-Soft** [comment]
And according to the CSS we need to create a custom FXGLScrollBar too.
