### ISSUE TITLE
Mobile: The file system implementation is not mobile friendly

### ISSUE THREAD

**Issue by jperedadnr** [AlmasB/FXGL#502]
The current file system implementation is not mobile friendly.

There are two main problems: 
 - The use of `java.nio` packages doesn't work on Android until version 26 (Android 8.0), so older devices (most of the Android devices actually), won't be able to use it.

 - Even if `java.nio` works, the Paths are related to a desktop file system, and this doesn't work on mobile, as the app is installed in a sandbox and you need to get the reference of that entry point.

For that, Gluon Charm Down provides the [storage service](http://docs.gluonhq.com/charm/javadoc/4.4.1/com/gluonhq/charm/down/plugins/StorageService.html), so you can start by getting the root path of your app like:

```
public static File root;
    {
        try {
            root = Services.get(StorageService.class)
                    .flatMap(StorageService::getPrivateStorage)
                    .orElseThrow(() -> new IOException("No private storage found"));
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
```

As a first step, we can add the service and get the `root` path:

```
dependencies {
    compile 'com.gluonhq:charm-down-plugin-storage:3.7.0'
    androidRuntime 'com.gluonhq:charm-down-plugin-storage-android:3.7.0'
    desktopRuntime 'com.gluonhq:charm-down-plugin-storage-desktop:3.7.0'
    iosRuntime 'com.gluonhq:charm-down-plugin-storage-ios:3.7.0'
}
```

As a second step, we can remove `java.nio` and use just `java.io.File`.

**Comment by AlmasB** [comment]
Does this mean if we use `java.io.File` only, no need for storage service?

**Comment by jperedadnr** [comment]
We need it anyway, as you need to access the path of your app in the mobile environment. That uses native code and the Storage Service provides that for you with a neutral Java API.

**Comment by AlmasB** [comment]
Ok, in which case I'd like to make both versions as compatible as possible, simply to avoid rewriting some parts

**Comment by jperedadnr** [comment]
That makes sense. Removing nio will help in both versions. 
And you can use StorageService in both versions as well, since it provides a Desktop implementation. Note that this one defaults to `user.home`.
