### ISSUE TITLE
iOS: Add AudioService implementation

### ISSUE THREAD

**Issue by jperedadnr** [AlmasB/FXGL#503]
On mobile, JavaFXPorts doesn't port the JavaFX Media API, so all the Sound calls will fail.

The Charm Down [video](http://docs.gluonhq.com/charm/javadoc/4.4.1/com/gluonhq/charm/down/plugins/VideoService.html) service provides an implementation for iOS and Android that allows playing mp3 or other audio formats.

We could try to keep the current implementation for Desktop  and use the Video service on mobile. 

```
dependencies {
    compile 'com.gluonhq:charm-down-plugin-video:3.7.0'
    androidRuntime 'com.gluonhq:charm-down-plugin-video-android:3.7.0'
    iosRuntime 'com.gluonhq:charm-down-plugin-video-ios:3.7.0'
}
```

**Comment by AlmasB** [comment]
Since the Charm Down video service is a single instance (we need to be able to play music / sounds simultaneously), a custom service will be implemented in [FXGL-AudioPlugin](https://github.com/AlmasB/FXGL-AudioPlugin)

**Comment by AlmasB** [comment]
Proposed API: (I'm assuming default methods will have to go to some abstract base class). @jperedadnr please review

```
public interface AudioService {

    default void loopMusic(String fileName, double leftVolume, double rightVolume) {
        playMusic(fileName, Integer.MAX_VALUE, leftVolume, rightVolume);
    }

    default void playMusic(String fileName) {
        playMusic(fileName, 1, 1.0, 1.0);
    }

    default void playMusic(String fileName, double volume) {
        playMusic(fileName, 1, volume, volume);
    }
    
    void playMusic(String fileName, int numTimes, double leftVolume, double rightVolume);
    
    void pauseMusic(String fileName);

    void stopMusic(String fileName);

    default void playSound(String fileName) {
        playSound(fileName, 1, 1.0, 1.0);
    }

    default void playSound(String fileName, double volume) {
        playSound(fileName, 1, volume, volume);
    }

    void playSound(String fileName, int numTimes, double leftVolume, double rightVolume);
}
```

Optionally, we might use the following data structures but I'm unsure if we want to include that plugin-audio level, or simply keep in FXGL only:

```
class Sound(val fileName: String)
class Music(val fileName: String)
```

**Comment by jperedadnr** [comment]
Default methods are not supported on mobile. Typically if we want some common code for the different implementations of a service, we use a Default implementation class in the main package, like this [DefaultCacheService.java](https://bitbucket.org/gluon-oss/charm-down/src/11c36e187921b2eac4a3d518cc00ad9108cab89f/plugins/plugin-cache/src/main/java/com/gluonhq/impl/charm/down/plugins/DefaultCacheService.java?at=default&fileviewer=file-view-default).

**Comment by AlmasB** [comment]
This is the final draft of the API:
```
public interface AudioService {

    void setGlobalMusicVolume(double volume);

    /**
     * Loops given music (.mp3) file with default volume (1.0)
     * or using the volume previously set with {@link #setGlobalMusicVolume(double)}.
     * If the music file is paused, it will be resumed,
     * otherwise the playback will begin from the start.
     *
     * @param fileName music file name in the "resources" directory,
     *                 e.g. if the file is "resources/files/test.mp3", then
     *                 fileName is "/files/test.mp3"
     */
    void loopMusic(String fileName);

    /**
     * Plays given music (.mp3) file once with default volume (1.0)
     * or using the volume previously set with {@link #setGlobalMusicVolume(double)}.
     * If the music file is paused, it will be resumed,
     * otherwise the playback will begin from the start.
     *
     * @param fileName music file name in the "resources" directory,
     *                 e.g. if the file is "resources/files/test.mp3", then
     *                 fileName is "/files/test.mp3"
     */
    void playMusic(String fileName);

    /**
     * Plays given music (.mp3) file once with default volume (1.0)
     * or using the volume previously set with {@link #setGlobalMusicVolume(double)}.
     * If the music file is paused, it will be resumed,
     * otherwise the playback will begin from the start.
     *
     * @param fileName music file name in the "resources" directory,
     *                 e.g. if the file is "resources/files/test.mp3", then
     *                 fileName is "/files/test.mp3"
     * @param action callback to be executed after music has finished (or stopped) playing
     */
    void playMusic(String fileName, Runnable action);

    /**
     * Pauses the music file if it is being played,
     * otherwise a no-op.
     */
    void pauseMusic(String fileName);

    /**
     * Stops the music file if it is being played,
     * otherwise a no-op.
     */
    void stopMusic(String fileName);

    /**
     * Plays given sound (.wav) file once with default volume (1.0).
     *
     * @param fileName sound file name in the "resources" directory,
     *                 e.g. if the file is "resources/files/test.mp3", then
     *                 fileName is "/files/test.wav"
     */
    void playSound(String fileName);

    /**
     * Plays given sound (.wav) file once with given volume.
     *
     * @param fileName sound file name in the "resources" directory,
     *                 e.g. if the file is "resources/files/test.mp3", then
     *                 fileName is "/files/test.wav"
     * @param volume in range [0..1]
     */
    void playSound(String fileName, double volume);

    /**
     * Plays given sound (.wav) file once with given volume.
     *
     * @param fileName sound file name in the "resources" directory,
     *                 e.g. if the file is "resources/files/test.mp3", then
     *                 fileName is "/files/test.wav"
     * @param volume in range [0..1]
     * @param action callback to be executed after sound has finished playing
     */
    void playSound(String fileName, double volume, Runnable action);
}
```

**Comment by jperedadnr** [comment]
Why the difference between sound and music? Won't the audio implementation (MediaPlayer) be the same for both, at least on mobile? 
Also it probably makes sense allowing online resources via URL.

**Comment by AlmasB** [comment]
Music is a long audio file, e.g. mp3, sound is a short audio file, .e.g wav. On Android, media player is used for mp3 streaming, while sound pool is better suited for short sounds. So, the implementation is, in fact, different. Similarly, for the desktop back-end, the implementation will be different.

RE: URL resources, do you think we should use a data structure like `Sound`, `Music`, which will store the information about file name or resource name. That way the API will take a `Sound` object and allows us to future proof it, in case we want to add more functionality in the future via these objects, e.g. pitch, balance, rate, etc.

**Comment by jperedadnr** [comment]
Ok, maybe if we go with one single object `Audio`, that has an enum type `Sound` or `Music`, and other fields like `fileName`, `URL`, `metaData`, `duration`,... we won't need to duplicate API, just `playAudio(Audio audio)` will be enough?

**Comment by AlmasB** [comment]
I think so, also thought of that

**Comment by AlmasB** [comment]
How about this:

```
public interface AudioService {

    /**
     * @param volume in range [0..1]
     */
    void setMusicVolume(double volume);

    /**
     * @param volume in range [0..1]
     */
    void setSoundVolume(double volume);

    void playAudio(Audio audio);

    void pauseAudio(Audio audio);

    void stopAudio(Audio audio);
}
```

**Comment by AlmasB** [comment]
We could also store volume per audio object inside it, then we get rid of the setVolume() methods

**Comment by jperedadnr** [comment]
I'd have one single volume method: `void setVolume(Audio audio, double volume);`
No more loops or runnable?

**Comment by AlmasB** [comment]
Looping: `audio.setCycleCount(int);`
Runnable: `audio.setOnFinished( Runnable );`

**Comment by jperedadnr** [comment]
Ok, makes sense.

**Comment by AlmasB** [comment]
```
public interface AudioService {

    void setVolume(Audio audio, double volume);

    void playAudio(Audio audio);

    void pauseAudio(Audio audio);

    void stopAudio(Audio audio);
}
```

So we basically force clients to keep the references to audio, which I think is good, because we can do: `audio.dispose()` to release native resources

**Comment by AlmasB** [comment]
Here's the latest version:

```
public interface AudioService {

    Audio newAudio(AudioType type, URL url);

    void releaseAudio(Audio audio);
}
```

This allows us to provide native implementations against Audio, rather than keeping them as "managers". So `play`, `pause` and `stop`, etc. move to underlying implementations

**Comment by jperedadnr** [comment]
I'm not fond of "newXXX", maybe `createAudio()`?
About using `URL` and not `String`, I prefer the latter, as you can refer your resources directly, and only if the string is a valid URL address, process it.

**Comment by AlmasB** [comment]
Yep, createAudio is fine. So is String. I'm happy with both changes

**Comment by AlmasB** [comment]
```
public interface AudioService {

    Audio createAudio(AudioType type, String resourceName);

    void releaseAudio(Audio audio);
}
```

We could move `release` to `Audio` too, but I quite like the symmetric API design, so currently sticking to this

**Comment by AlmasB** [comment]
The Android/Desktop implementations are now complete at [FXGL-AudioPlugin](https://github.com/AlmasB/FXGL-AudioPlugin). The FXGL integration is also done in 0.4.4-SNAPSHOT.

**Comment by AlmasB** [comment]
this issue is obsolete since charm down is no longer used. With Attach, we'll have to figure out a way to handle this, but not here
