### ISSUE TITLE
Mobile: Listen for pause / resume events

### ISSUE THREAD

**Issue by AlmasB** [AlmasB/FXGL#505]
The [Lifecycle Charm Down service](http://docs.gluonhq.com/charm/javadoc/4.4.1/com/gluonhq/charm/down/plugins/LifecycleService.html).

Do the same as with minimize / maximize on desktop to pause resume main loop. We must also pause the super state #404  when it is implemented

**Comment by ms12r** [comment]
This would also resolve the music continuing to play in the background even when the user pauses the game or could that be done manually?

**Comment by AlmasB** [comment]
The music won’t stop automatically, but with this new listener you’ll know
when the game is paused / resumed, so you can pause/resume music and sounds
using AudioPlayer.
