### ISSUE TITLE
Mobile: Handle possible orientation changes

### ISSUE THREAD

**Issue by AlmasB** [AlmasB/FXGL#507]
[Orientation service](http://docs.gluonhq.com/charm/javadoc/4.4.1/com/gluonhq/charm/down/plugins/OrientationService.html)

**Comment by AlmasB** [comment]
@jperedadnr is it possible to force the application to open and stay in a specific orientation. I seem to remember seeing something like this in configurations, maybe info.plist and android manifest file?

**Comment by jperedadnr** [comment]
Yes, you can enforce one single orientation, for both platforms.
See for instance MyDevxx app for [Android](https://github.com/devoxx/MyDevoxxGluon/blob/master/DevoxxClientMobile/src/android/AndroidManifest.xml#L61) or [iOS](https://github.com/devoxx/MyDevoxxGluon/blob/master/DevoxxClientMobile/src/ios/Default-Info.plist#L45).

**Comment by AlmasB** [comment]
Info now in [wiki](https://github.com/AlmasB/FXGL/wiki/Code-Snippets#locking-screen-orientation-on-mobiles), currently no use cases requiring orientation service
