### ISSUE TITLE
Particle System Slowing Down the Whole Thread

### ISSUE THREAD

**Issue by bturner1273** [AlmasB/FXGL#509]
I have explosion emitters going off when a bullet hits an asteroid in my space invaders game and when the emitter goes off it freezes everything moving across the screen for a second than everything jumps to where it should be. I would just throw it on another thread using the executor but it says not to change the game scene on a different thread.

**Comment by AlmasB** [comment]
This is a known issue and is linked to #494 In short we are trying to be clever about drawing and only engage the graphics context when there are particles. Hence, the immediate slow down in drawing. We might be able to off-load the particle drawing to a background thread but this is not trivial as there are potential synchronization issues. The solution to this needs to be carefully designed but generally it is of the following form:

1. Detect when drawing of this frame has finished.
2. Take the canvas off the active scene graph and give it to a bg thread.
3. Async: Clear and draw particles
4. Wait for async to finish and insert the canvas back into the active scene graph.

Also, I wonder if we can keep two buffers and keep swapping them for performance...

**Comment by AlmasB** [comment]
This was fixed and merged into 0.5.0
