### ISSUE TITLE
Mobile: Clean up Java 1.8 API in favor of 1.7 to support Android API 21+ (5.0+)

### ISSUE THREAD

**Issue by AlmasB** [AlmasB/FXGL#510]
IDEA, inspection -> Usage of API above 1.7. [Android ref](https://developer.android.com/reference/java/lang/Iterable.html) also seems informative

Alternatively, use Kotlin to compile to Java 7 compatible bytecode

**Comment by jperedadnr** [comment]
Note that Android 24+ allows (most of) Java 1.8, like Streams. Other features like nio.Path were added on Android 26.

So if you want to keep compatibility to older versions (like 21+), you need a "Java 7" style (including lambdas and Method references from Java 8).
