### ISSUE TITLE
Change loading screen

### ISSUE THREAD

**Issue by Polkasa** [AlmasB/FXGL#511]
Hello!
Is there anyway to change FXGL loading screen(always showed at start application) ? I mean replace image or animation or replace whole screen? I wanted to place information about library in "credits" in my custom menu, and on loading i wanted to show logo of my application

**Comment by AlmasB** [comment]
I assume you mean the preloading splash screen. It can't be done at the moment but there is an open issue #361

**Comment by Polkasa** [comment]
Ok, so i close this
