### ISSUE TITLE
Mobile

### ISSUE THREAD

**Issue by Polkasa** [AlmasB/FXGL#512]
Hello! I wanted to ask you one question. Can i use FXGL on mobile ? Or there can be some problems with it ?

**Comment by AlmasB** [comment]
FXGL on mobile is a subproject that was started very recently. While technically you can, some things will be disabled and unstable: sounds, music, file system, annotation processing. So I suggest that you don't the mobile version until it has reached a stable build

**Comment by Polkasa** [comment]
Ok, so i will be waiting for the stable version, for now im implementing my game on desktop
