### ISSUE TITLE
Debug View: Draw all fixtures (not only hitboxes)

### ISSUE THREAD

**Issue by Polkasa** [AlmasB/FXGL#516]
Hello! Is there a way to turn on debug draw in fxgl ? If it is, so how i can do this?

**Comment by AlmasB** [comment]
You can enable debug views in Dev mode via ctrl+0, then select view ->
debug. It only shows hit boxes, nothing else.

Let me know what things you want to be able to see.

**Comment by Polkasa** [comment]
I wanted to see fixtures for player, like on this example (ground sensor):
![test](https://user-images.githubusercontent.com/7520445/37242997-88e1e606-2472-11e8-83cf-bdc835a8a578.png)

**Comment by AlmasB** [comment]
Done in 0.5.2
