### ISSUE TITLE
Physics: allow changing settings for (ground) sensors

### ISSUE THREAD

**Issue by Polkasa** [AlmasB/FXGL#517]
Hello! In my image there is situation with groundSensor, where "p" is player, and "b" is block, Normally it works as my attached screen, but i wanted to be able jump in two situations how i can achieve that ?

![test](https://user-images.githubusercontent.com/7520445/37239431-44191dc2-243c-11e8-8169-c7d059e62963.png)

**Comment by AlmasB** [comment]
Ground sensor is placed directly underneath the player. Let me know what
the API needs to be able to do to achieve your use case.

Also, please can you close your previous issues if they are answered /
solved.

**Comment by Polkasa** [comment]
Hi, i think the fixture(ground sensor) under the player should be on full width(of bounding box), like on this screen i attached
![test](https://user-images.githubusercontent.com/7520445/37242904-3244bcb6-2471-11e8-8eb4-afbf0f84a9a0.png)

Can i achieve that in current version of library ?

**Comment by AlmasB** [comment]
I see. I've renamed the issue, so we can come back to it in future versions. For now, maybe you can try checking the Y velocity and see if it's close to 0?

**Comment by AlmasB** [comment]
- [ ] Ground sensors
- [ ] Adding arbitrary sensors

**Comment by AlmasB** [comment]
Done in 0.5.2
