### ISSUE TITLE
DSL: for each var type add a new Text object generation bound to the var

### ISSUE THREAD

**Issue by AlmasB** [AlmasB/FXGL#520]

**Comment by AlmasB** [comment]
For example, one for int value, another for double value, etc.

**Comment by AahzBrut** [comment]
Hi!

I need some clarification on this issue:
if property, which name was passed to this function, was not found in `PropertyMap` - should this function return some dummy `Text` or should it need to throw some exception?

**Comment by AlmasB** [comment]
Hi, given these are convenience functions to be used mainly for debugging purposes and not in production, I think it's safe to fail-fast. An `IllegalArgumentException` should be suitable, when no key found in `PropertyMap`. I believe `PropertyMap` has `exists()` or similar that you can use to immediately check at the function start and then fail if necessary.

**Comment by AahzBrut** [comment]
Well, i've implemented this function, and tested it in KotlinGameApp, but for now I have difficulty with tests.
To test this function I have to initialize FXGL, and I have no idea for now how to do that :)
To initialize it I need to call FXGL.inject() and provide engine and applications, but its not that simple, so an example would be appretiated :)

**Comment by AlmasB** [comment]
Don't worry about tests, if you have a sample (in `fxgl-samples` under `sandbox`), that is sufficient for now.
