### ISSUE TITLE
Clean up API for better web support via JPro

### ISSUE THREAD

**Issue by AlmasB** [AlmasB/FXGL#523]
Using [JPro](https://www.jpro.one/) tech we can port FXGL to web. There are some API not supported by jpro, e.g. `setCursor` or multiple stages. In addition, it might actually be easier overall to use just a single stage (including the preloading scene) to simplify architecture. We simply need to know the size of the stage on open, or simplify startup routines

- [X] Use single stage (preloading + rest)
- [X] `initStyle` in MainWindow will fail (as stage is shown)
- [X] `setCursor`
- [ ] Error dialog show and wait not supported

**Comment by FlorianKirmaier** [comment]
What is the problem with setCursor? setCursor should work fine with jpro.

If you have any further questions or need help, you can contact us at info@jpro.one .

Soon, I would like to add some [fxgl-samples to the jpro-demo-page](https://www.jpro.one/?page=demos)! :)

**Comment by AlmasB** [comment]
Re: setCursor, I don't know, I haven't done much testing, just wrapped code that was failing during my first experiments with `isDesktop()`. Eventually, I'll investigate the errors.

Cool, thanks!
