### ISSUE TITLE
0.4.3: not buildable with Java 9 ?

### ISSUE THREAD

**Issue by coldwarrl** [AlmasB/FXGL#524]
If I try to clone the current master and execute

`mvn clean install`

I get a lot of errors, like

``
import com.almasb.fxgl.app.FXGL;
[ERROR]                           ^
[ERROR]   symbol:   class FXGL
[ERROR]   location: package com.almasb.fxgl.app
[ERROR] /home/tmp/FXGL/fxgl/src/main/java/com/almasb/fxgl/ui/UIFactory.java:13: error: cannot find symbol
[ERROR] import com.almasb.fxgl.util.EmptyRunnable;
[ERROR]                            ^
[ERROR]   symbol:   class EmptyRunnable
[ERROR]   location: package com.almasb.fxgl.util
``

I assume the root cause is that the fxgl module does not find the framework-root (same issue in IntelliJ). If I switch to Java 8 it works. I am not so familar with the module system in maven and maybe there are conflicts with the new module system in java 9 ?

@AlmasB have you managed to build fxgl on java 9 ? I was able to do so in the past at least...do not know why it does not work anymore

**Comment by coldwarrl** [comment]
wrong alarm....have overseen it that javadoc fails.

install -Dmaven.javadoc.skip=true helps here

**Comment by AlmasB** [comment]
@coldwarrl for future reference, if you have issues with java8/9 builds you can also inspect [travis builds](https://travis-ci.org/AlmasB/FXGL) which always build on oraclejdk8 and 9
