### ISSUE TITLE
Texture images not rendered

### ISSUE THREAD

**Issue by HumanWritesCode** [AlmasB/FXGL#531]
Following the basic tutorial and using Maven, with "brick.png" placed in src/main/resources/assets/textures and player = Entities.builder().at(300,300).viewFromTexture("brick.png").buildAndAttach(getGameWorld()); replacing the former player assignment.

There is no error or exception thrown and everything renders except the brick.png image.  The game takes keyboard input and the pixel counter UI updates. There just isn't a brick texture visible.

On Windows using the Netbeans IDE.

**Comment by AlmasB** [comment]
@HumanWritesCode I seem to remember another user with Netbeans having a similar issue. Can you "refresh" Netbeans in some way or try with a different IDE? I have Netbeans but cannot seem to reproduce the issue

**Comment by AlmasB** [comment]
Did you manage to get textures working?
