### ISSUE TITLE
Fullscreen Issue

### ISSUE THREAD

**Issue by jordancole18** [AlmasB/FXGL#532]
Hi, I am wondering how I could possibly fullscreen on startup as when it tries to fullscreen on startup the Taskbar covers it. (Windows 10). Thanks.

EDIT
Also scene.getWindow() returns null and creates an error. This was going to be my first way of fullscreening on startup.

**Comment by AlmasB** [comment]
During the very first run going full screen immediately is not allowed by FXGL. The typical process is the game starts (for the very first time), the user goes into video submenu and selects fullscreen toggle. After that FXGL will create user settings and full screen should work from startup.

I'll have a look at it in the evening.

**Comment by AlmasB** [comment]
Fullscreen behaves by design as per previous reply.
