### ISSUE TITLE
API, GameWorld: Entities are modifiable

### ISSUE THREAD

**Issue by coldwarrl** [AlmasB/FXGL#533]
In class Gameworld, the API provides mutable access to the entities:

```java
/**
     * List of entities in the world.
     *
     * @return direct list of entities in the world (do NOT modify)
     */
    val entities = ArrayList<Entity>(INITIAL_CAPACITY)
```

The API doc makes clear that it should not be modified but I have overseen it, thus I have wondered why my entities are not gone when I called removeAll on that instance (e.g. the visual artifacts were not deleted)
My proposal: expose only a read-only collection(via the public API), which prevents misuse

Also it would be nice to have an additional function in GameWorld, which allows you to pass a collection of to be deleted entities...

**Comment by AlmasB** [comment]
1. So, you mean `List<>` rather than `MutableList<>`? It won't make any difference to Java though, or do you mean something else?

2. something like this `GameWorld::removeEntities(Collection<Entity>)` ?

**Comment by coldwarrl** [comment]
1. java supports unmodifyable lists: https://docs.oracle.com/javase/1.5.0/docs/api/java/util/Collections.html#unmodifiableList%28java.util.List%29

2. yup

**Comment by AlmasB** [comment]
Yeah, I'm happy with that, feel free to submit a PR

**Comment by coldwarrl** [comment]
oki, will add it to my tasks

**Comment by coldwarrl** [comment]
An issue is that 'entities' is part of the public API. Usually you would keep entities and mark it private / internal and the public read only property you would name usually entitiesView.

That would break existing usages. @AlmasB are you comfortoable if we do this with the next major release (0.6) ?

Another possibilites is to change the semantics, that is 'entities' is the read only view and a entitiesInternal property or whatever is the physical collection and used internally. But I do not like this.

**Comment by AlmasB** [comment]
Yes, we should keep (1) until 0.6, but (2) can be done now if you want.

**Comment by coldwarrl** [comment]
added PR for (2)
