### ISSUE TITLE
Tiled. Tile objects

### ISSUE THREAD

**Issue by demiurg906** [AlmasB/FXGL#534]
Hello

If I understand correctly, FXGL doesn't support "Tile objects" from Tiled, which is sadly.
I looked into source of tmx parser and I founded, that `TiledObject` contains field `gid` that contains info about tile in object, but `TMXParser.parseObjects` doesn't parse that tag. Is that field added for futher implementation or it's a bug that it isn't parsed?

**Comment by AlmasB** [comment]
Hi,

I'm not quite sure what you mean. Can you provide an example with .tmx to support your question

**Comment by demiurg906** [comment]
```  
 <objectgroup name="Слой объектов 1">
<object id="28" type="Player" gid="11" x="48" y="80" width="16" height="16"/>
 </objectgroup>
```

tag `gid` means, what tile mapped to that object. `TMXParser` ignores it and so application doesn't render player

**Comment by AlmasB** [comment]
I think I get it now. That seems like a bug, or perhaps I was targeting a different .tmx version. Can you provide a full .tmx, including tilesets, preferably a very simple example so I can reproduce and eventually fix it. Thanks

**Comment by demiurg906** [comment]
Also parser doesn't parse `rotation` field from objects

**Comment by demiurg906** [comment]
And another strange thing: i have 4 walls, 4 enemies and a player on a level:
![default](https://user-images.githubusercontent.com/14974409/38986153-43edc7be-43d4-11e8-89dc-37c780febdd1.png)

After application initialization enemies and player (but not walls) are being shifted to one cell down.
![default](https://user-images.githubusercontent.com/14974409/38986431-0daa601c-43d5-11e8-8f64-cee1d26857b3.png)

Fuctions, that I use for building entities:
```kotlin
private fun rectangle(data: SpawnData, color: Color) = Rectangle(data.get("width"), data.get("height"), color)

@Spawns("Wall")
fun newWall(data: SpawnData) = Entities.builder()
        .from(data)
        .type(RogueType.Wall)
        .bbox(objectHitBox(data))
        .viewFromNode(rectangle(data, Color.BLANCHEDALMOND))
        .renderLayer(RenderLayer.BOTTOM)
        .build()

@Spawns("Player")
fun newPlayer(data: SpawnData) = Entities.builder()
        .from(data)
        .type(RogueType.Player)
        .with(PlayerControl())
        .bbox(creatureHitBox(data))
        .viewFromNode(rectangle(data, Color.RED))
        .renderLayer(RenderLayer.TOP)
        .build()

// for enemy function same as newPlayer
```

**Comment by AlmasB** [comment]
- [ ] TiledObject gid
- [ ] rotation field
- [ ] shifted objects

**Comment by AlmasB** [comment]
I think I fixed 1 and 3, please can you check. Snapshot repo and version is `0.5.1-SNAPSHOT`

```
    <repositories>
        <repository>
            <id>oss.sonatype.org-snapshot</id>
            <url>http://oss.sonatype.org/content/repositories/snapshots</url>
        </repository>
    </repositories>
```

**Comment by demiurg906** [comment]
It works, thanks a lot
