### ISSUE TITLE
Mobile: pause/resume games according app lifecycle

### ISSUE THREAD

**Issue by jperedadnr** [AlmasB/FXGL#539]
On mobile, the app is not always running on foreground. When going to the background, the game should be paused, and when the app is back on top, the game should be resumed.

The Charm Down Lifecycle service can be used for this purpose.

**Comment by AlmasB** [comment]
I believe this is a duplicate of #505

**Comment by jperedadnr** [comment]
Ups, right, so we can close this as duplicated.
