### ISSUE TITLE
multiple bindings for an event?

### ISSUE THREAD

**Issue by bturner1273** [AlmasB/FXGL#544]
is this a possibility without re-writing user actions?

**Comment by bturner1273** [comment]
for instance i'm porting flappybird to 0.5.1 and I want the spacebar and mousebutton.primary to do action flap

**Comment by AlmasB** [comment]
Currently, as per [Input guide](https://github.com/AlmasB/FXGL/wiki/Input#things-to-remember) we have 1 action - 1 trigger, so you would create two user actions, but they can still call the same code, e.g. `flap()`.

I don't know if this will change, but there is a possibility for that, as in 0.5.2-SNAPSHOT you can bind 1 action to 1 real trigger and 1 [virtual trigger](https://twitter.com/AlmasBaim/status/997827123627819009)
