### ISSUE TITLE
.setViewFromAnimatedTexture()

### ISSUE THREAD

**Issue by bturner1273** [AlmasB/FXGL#545]
this is only available to an entity when it is being built by Entities.builder()...build(). I am trying to dynamically add animations to spots on the screen which have worked in previous versions but I can't quite figure it out in 0.5.1. I have tried making animated textures from animation channels, doing texture.toAnimatedTexture and adding as a node (getGameScene().addNode()) but it doesn't animate. I have also tried changing the view on the actual player where the node is added but that doesn't animate either unless it is done in builder

**Comment by AlmasB** [comment]
How about `entity.getViewComponent().setAnimatedTexture( ... )`? Will that work for your use case?

**Comment by bturner1273** [comment]
this does work for my case!
