### ISSUE TITLE
HitBox does not scale with view

### ISSUE THREAD

**Issue by bturner1273** [AlmasB/FXGL#546]
![for_almasb](https://user-images.githubusercontent.com/32464706/40441518-4d6ab5d8-5e8f-11e8-860f-7e6bb97772ac.gif)

So i am having some major issues with either the scaling of hitboxes or the collision system. As can be seen there are no objects touching in the video but collisions are registering and that little spec (an animation that hasn't been scaled yet) appears way above the frog and to the left when it is meant to go the the exact center position of the frog. When I hit CTRL+0 and turn hitbox view on it shows what I am expecting for the hitboxes but the position of the animation changes when it is still just replacing the view of the frog. I have no clue why these entities are causing collisions when their hitboxes aren't touching

**Comment by bturner1273** [comment]
the source code and every asset is on my github under the FXGL_OYOCourse_0.5.1 repo

**Comment by bturner1273** [comment]
[https://github.com/bturner1273/FXGL_OYOCourse_0.5.1](url)

**Comment by AlmasB** [comment]
By scaling do you mean the view? Currently, in FXGL there's no way to scale hit boxes, only scaling views is present. So it might be that you are attempting to use a feature that is simply not there? If that is the case, I believe this is a very useful feature: to extract scale transformation from view and make it a separate component. After that, adjust other components, such as view, bbox, position, etc.

**Comment by AlmasB** [comment]
Yes, the hit box view (incorrectly) automatically scales with the view but
the actual bounding box doesn’t scale.

This needs to be fixed but requires a lot more design to have
ScaleComponent. For now a workaround is to build your bbox the size it
needs to be when the view is scaled.

**Comment by bturner1273** [comment]
post scaling

![for_almasb](https://user-images.githubusercontent.com/32464706/40491528-5224c50c-5f3c-11e8-8144-5d81176c7107.gif)

**Comment by AlmasB** [comment]
Scaling “pivot” point is the center of the view, while the bbox origin is
at 0,0. Yes you can change anchor (origin) of the bbox - when you create
your hit box, you can pass Point2D for origin. I’m assuming it’ll be
something like -w/2, -h/2.

**Comment by bturner1273** [comment]
So I got it working with changing the origin but there is still a bunch of fiddling/guess work that went into it. If there could be some sort of GUI in the CTRL+0 menu where it was possible to pause the game and draw hitboxes that translated into the recognized bounding shapes then there would probably be no need to ever mess with hitboxes in the code unless some sort of dynamic scaling was taking place which could just scale the result of the hitbox already drawn.

Thank you for your advice!

**Comment by AlmasB** [comment]
- [ ] Extract debug view from ViewComponent so that view scale does not affect bbox view.
- [ ] When scaling (as it is done from the center and not top-left corner) also reposition the entity, to reflect the correct position, and scale the bbox from top-left corner by the value.

**Comment by AlmasB** [comment]
This will be implemented as part of #258
