### ISSUE TITLE
Mobile: configure scripting engine to function

### ISSUE THREAD

**Issue by ms12r** [AlmasB/FXGL#548]
It appears that there is a problem with the current configuration for JavaScript support on mobile devices. This problem does not persist on Desktop. It may be resolved by using Rhino instead.

I'm receiving an ExceptionInInitializerError in line 19 of ScriptFactory.kt, at AssetLoader.kt:415, ... caused by manager.getEngineByName("nashorn") must not be null at JS.kt 46.

**Comment by ms12r** [comment]
I notice some references use getEngineByName("JavaScript"). Would that be the same as nashorn?

**Comment by AlmasB** [comment]
Given [this proposal](http://openjdk.java.net/jeps/335), I think we should wait until we know what we are dealing with on both desktop and mobile

**Comment by AlmasB** [comment]
Perhaps, in the future we can switch to [kotlin scripts](https://github.com/Kotlin/KEEP/blob/master/proposals/scripting-support.md)

**Comment by AlmasB** [comment]
There is no clear way to add scripting support, even to desktop. This will be considered after the 11.0 refactor
