### ISSUE TITLE
Mobile: Bind touchevents to nodes as input option for adding actions

### ISSUE THREAD

**Issue by ms12r** [AlmasB/FXGL#549]
Would it be possible to perhaps allow for the TouchEvent in conjunction with the node to act as a trigger for Input Mapping?

I've been working on a virtual joystick and ran into an issue with the input being rather difficult as it pertains to handling touchevents, specifically the binding of an action to a node when a touch is held stationary. I've included a minimal working example in a repo of how I've managed to get a "joystick" interface. 

https://github.com/ms12r/FXGL_Touch_Demonstration

However, the touch stationary does not function properly and this may be an issue with the way I've coded it or a JavaFX limitation. It appears that when the user has moved the joystick and then holds it at a certain point, the entity will stop moving. I would say it's a matter of the tick not being there for the eventhandler to dispatch that the joystick is being held steady and to use the same point to keep the entity moving. I have no clue how to implement such a "tick" method. I've recently acquired about TomasMikula/ReactFX which has an API referenced as a State Machine which would allow for this perhaps.

**Comment by AlmasB** [comment]
0.5.2 will bring virtual controller, which does integrate with existing input bindings, e.g.:
```
        getInput().addAction(new UserAction("Jump") {
            @Override
            protected void onActionBegin() {
                player.getComponent(MarioComponent.class).jump();
            }
        }, KeyCode.W, VirtualButton.Y);
```
 Screenshot attached. I believe we can look at this issue, in 0.5.3

**Comment by AlmasB** [comment]
This will be considered after the 11.0 refactor
