### ISSUE TITLE
Allow for alternate build path of tiled map .png tiles file

### ISSUE THREAD

**Issue by bturner1273** [AlmasB/FXGL#550]
![image](https://user-images.githubusercontent.com/32464706/40672050-a94a0c2c-633b-11e8-9943-ca9a1352fdb7.png)

FXGL seems to only look in the default textures folder when loading a tiled map to get the actual tiles to load. Is there any way to supply an alternate local path? Like if I put the map_tiles.png file inside of the Platformer folder inside of textures? I just like dividing my folders into specific game folders so everything is clear and concise.

**Comment by AlmasB** [comment]
This will be considered after the 11.0 refactor
