### ISSUE TITLE
Animation Issues In Component Child Class

### ISSUE THREAD

**Issue by bturner1273** [AlmasB/FXGL#551]
Below is a component class I use to keep track of what animation should be playing when for platformer style movement/animation. 

**Problem 1:** 
This method works:
`public void setIdleImage(AnimatedTexture anim) {
		idle = anim;
	}`
This does not:
`public void setIdleImage(AnimationChannel channel) {
                idle = new AnimatedTexture(channel);
        }`

**Problem 2:** When setting an animated texture for my run image FXGL is not cycling through the frames. I can change the start frame of the channel and the change is reflected but it never loops through the actual animation. I don't think I did anything wrong in the code below and I pass in a correctly initialized AnimatedTexture for run.

I have resorted to changing the images in the initInput method when the right and left keys are down which is not ideal but the rest of the animating works! Idle (AnimatedTexture), and jump up and jump down (textures) all work great but it doesn't like run for some reason!

Here is what it looks like when running, the first frame of the run animation which gets displayed looks a lot like the jump picture but don't be fooled it is actually the first frame of the run animation and not the jump-up picture. The animation is not cycling though and it is written in the same way as idle which works.

Note that this is running using the run if-statements in the component child class. The code I added has entity.setView(run) commented out but in the GIF it is not commented. (it is commented in the code below because I am using the initInput method currently for the run animations which works perfect in combo with my component but I wanted the component to do it all)

![for_almasb](https://user-images.githubusercontent.com/32464706/40741824-7b00e39c-641a-11e8-9c4f-09f470b17528.gif)

`
package Platformer;

import com.almasb.fxgl.app.FXGL;
import com.almasb.fxgl.entity.component.Component;
import com.almasb.fxgl.entity.component.Required;
import com.almasb.fxgl.physics.PhysicsComponent;
import com.almasb.fxgl.texture.AnimatedTexture;
import com.almasb.fxgl.texture.AnimationChannel;
import com.almasb.fxgl.texture.Texture;

import javafx.util.Duration;

@Required(PhysicsComponent.class)
public class PlatformerAnimationComponent extends Component {
	double scalePos, scaleNeg;
	Texture jump_up;
	Texture jump_down;
	Texture idle;
	Texture run;
	double min_run_speed;
	boolean right = true;
	
	@Override
	public void onUpdate(double tpf) {		
		//set left or right
		if(entity.getComponent(PhysicsComponent.class).getVelocityX() < -min_run_speed) {
			setScaleAll(scaleNeg);
			right = false;
		}else if(entity.getComponent(PhysicsComponent.class).getVelocityX() > min_run_speed) {
			setScaleAll(scalePos);
			right = true;
		}
		
		//jump
		if(entity.getComponent(PhysicsComponent.class).getVelocityY() < 0) {
			entity.setView(jump_up);
		}
		else if(entity.getComponent(PhysicsComponent.class).getVelocityY() > 0) {
			entity.setView(jump_down);
		}else {
			
			//THIS IS NOT IN USE CURRENTLY BECAUSE OF AN FXGL BUG
			//run
			if(entity.getComponent(PhysicsComponent.class).getVelocityX() < -min_run_speed ||
					entity.getComponent(PhysicsComponent.class).getVelocityX() > min_run_speed &&
					(entity.getComponent(PhysicsComponent.class).getVelocityY() < 10 && 
					entity.getComponent(PhysicsComponent.class).getVelocityY() > -10)) {
					
					//entity.setView(run);
			}
			//THE REST OF THE CODE IS USED
			
			//idle
			else if(entity.getComponent(PhysicsComponent.class).getVelocityY() < 10 &&
					entity.getComponent(PhysicsComponent.class).getVelocityY() > -10 &&
					entity.getComponent(PhysicsComponent.class).getVelocityX() > -min_run_speed &&
					entity.getComponent(PhysicsComponent.class).getVelocityX() < min_run_speed) {
			
					entity.setView(idle);
		}
		}
	}
	
	public void setMinRunSpeed(double speed) {
		min_run_speed = speed;
	}
	
	public double getMinRunSpeed() {
		return min_run_speed;
	}
	
	public void setJumpUpImage(String image_path) {
		jump_up = FXGL.getAssetLoader().loadTexture(image_path);
	}
	
	public void setJumpUpImage(Texture img) {
		jump_up = img;
	}
	
	public void setJumpDownImage(String image_path) {
		jump_down = FXGL.getAssetLoader().loadTexture(image_path);
	}
	
	public void setJumpDownImage(Texture img) {
		jump_down = img;
	}
	
	public void setRunImage(AnimatedTexture anim) {
		run = anim;
	}
	
	public void setRunImage(Texture img) {
		run = img;
	}
	
	public void setRunImage(String image_path) {
		run = FXGL.getAssetLoader().loadTexture(image_path);
	}
	
	public void setIdleImage(AnimatedTexture anim) {
		idle = anim;
	}

	public void setIdleImage(Texture img) {
		idle = img;
	}
	
	public void setIdleImage(String image_path) {
		idle = FXGL.getAssetLoader().loadTexture(image_path);
	}
	
	public void setScaleAll(double scaler) {
		if(scaler < 0) {
			scaleNeg = scaler;
			scalePos = -scaler;
		}else {
			scaleNeg = -scaler;
			scalePos = scaler;
		}
		jump_up.setScaleX(scaler);
		jump_down.setScaleX(scaler);
		idle.setScaleX(scaler);
		run.setScaleX(scaler);
		
		if(scaler > 0) {
			jump_up.setScaleY(scaler);
			jump_down.setScaleY(scaler);
			idle.setScaleY(scaler);
			run.setScaleY(scaler);
		}
	}
	
	public double getScale() {
		return scalePos;
        }
}
`

**Comment by bturner1273** [comment]
again, full code is up on my github if you want to take a further look, it is in the pinned repo FXGL_OYOCourse_0.5.1

**Comment by AlmasB** [comment]
The animation channels were designed to work with StateComponent, where instead if/else statements in the controlling component, one would utilize states and either loop or play animations once. For example [Robot sample](https://github.com/AlmasB/FXGL/blob/master/fxgl-samples/src/main/java/sandbox/robots/anim/RobotComponent.java#L45). I'm not sure how this translates to your use case, but I think (based on the code running in onUpdate()) your use case is currently not supported.

**Comment by AlmasB** [comment]
[Demo](https://www.youtube.com/watch?v=QTZp5EvmdP0)

**Comment by bturner1273** [comment]
Alrighty I'll try out that approach
