### ISSUE TITLE
Cycling through multiple Tiled Maps

### ISSUE THREAD

**Issue by bturner1273** [AlmasB/FXGL#552]
So in my initGame method I add my entity factory and everything works great when I set level from a tmx map. However, when I hit a door in my level I want to go to the next level and naturally I use set level from map again with another tmx file but it doesn't seem to load properly.

**Comment by AlmasB** [comment]
Can you elaborate on what exactly goes wrong? Also, a minimal example would be good

**Comment by bturner1273** [comment]
So in initGame() I set the level from a tmx map. When I go to try to do the same thing onCollision with the player and door entities it doesn't load the tmx file again. I had some issues with this in the earlier versions too I just never got around to posting the issue

`
public class Platformer_App extends GameApplication {
	Entity player;
	final int PLAYER_SPEED = 400;

	@Override
	protected void initSettings(GameSettings settings) {
		settings.setTitle("Platformer");
		settings.setVersion("");
		settings.setWidth(15*70);
		settings.setHeight(7*70);
	}
	
	@Override
	protected void initPhysics() {
		PhysicsWorld physicsWorld = getPhysicsWorld();
		physicsWorld.addCollisionHandler(new CollisionHandler(Platformer_Types.PLAYER, Platformer_Types.COIN) {
			@Override 
			public void onCollision(Entity player, Entity coin) {
				coin.removeFromWorld();
				getGameState().increment("score", 1);
			}
		});
		
		physicsWorld.addCollisionHandler(new CollisionHandler(Platformer_Types.PLAYER, Platformer_Types.LAVA) {
			@Override
			public void onCollision(Entity player, Entity lava) {
				player.getComponent(HealthComponent.class).setValue(player.getComponent(HealthComponent.class).getValue()-1);
				if(player.getComponent(HealthComponent.class).getValue() == 0) player.removeFromWorld();
				
			}
		});
		
		physicsWorld.addCollisionHandler(new CollisionHandler(Platformer_Types.PLAYER, Platformer_Types.DOOR) {
			@Override
			public void onCollision(Entity player, Entity door) {
				player.removeFromWorld();
				getGameWorld().setLevelFromMap("map_2.tmx");
				spawnPlayer();
			}
		});
	}
	
	protected void spawnPlayer() {
		player = getGameWorld().spawn("player", 100, 100);
	}
	
	@Override
	protected void initGameVars(Map<String, Object> vars) {
		vars.put("score", 0);
	}
	
	@Override
	protected void initUI() {
		getGameScene().setBackgroundColor(Color.LIGHTBLUE);
		Text score = new Text();
		score.setFont(Font.font ("Arial Bold", 35));
		score.textProperty().bind(getGameState().intProperty("score").asString());
		score.setFill(Color.BLACK);
		score.setTranslateX(getWidth()-50);
		score.setTranslateY(getHeight()-15);
		getGameScene().addUINode(score);
		Text score_label = new Text();
		score_label.textProperty().set("Score:");
		score_label.setFont(Font.font ("Arial Bold", 35));
		score_label.setFill(Color.BLACK);
		score_label.setTranslateX(getWidth()-150);
		score_label.setTranslateY(getHeight()-15);
		getGameScene().addUINode(score_label);
		Text health = new Text();
		health.setFont(Font.font ("Arial Bold", 35));
		health.textProperty().bind(player.getComponent(HealthComponent.class).valueProperty().asString());
		health.setFill(Color.BLACK);
		health.setTranslateX(getWidth()-50);
		health.setTranslateY(getHeight()-45);
		getGameScene().addUINode(health);
		Text health_label = new Text();
		health_label.setFont(Font.font ("Arial Bold", 35));
		health_label.textProperty().set("Health:");
		health_label.setFill(Color.BLACK);
		health_label.setTranslateX(getWidth()-165);
		health_label.setTranslateY(getHeight()-45);
		getGameScene().addUINode(health_label);
	}
	
	@Override
	protected void initInput() {
		AnimatedTexture running = new AnimatedTexture(
				new AnimationChannel("Platformer/run_sheet.png", 5, 1535/5, 445, Duration.millis(500), 0, 4));
		AnimatedTexture idle = new AnimatedTexture(
				new AnimationChannel("Platformer/stand_sheet.png", 2, 606/2, 431, Duration.millis(300), 0, 1));
		
		
		Input input = getInput();
		input.addAction(new UserAction("run_right") {
			@Override
			protected void onActionBegin() {
				running.setScaleX(.25);
				running.setScaleY(.25);
				player.getViewComponent().setAnimatedTexture(running, true, false);
			}
			@Override
			protected void onAction() {
				player.getComponent(PhysicsComponent.class).setVelocityX(PLAYER_SPEED);
			}
			@Override
			protected void onActionEnd() {
				idle.setScaleX(.25);
				idle.setScaleY(.25);
				player.getViewComponent().setAnimatedTexture(idle, true, false);
			}
		}, KeyCode.RIGHT);
		
		input.addAction(new UserAction("run_left") {
			@Override
			protected void onActionBegin() {
				running.setScaleX(-.25);
				running.setScaleY(.25);
				player.getViewComponent().setAnimatedTexture(running, true, false);
			}
			@Override
			protected void onAction() {
				player.getComponent(PhysicsComponent.class).setVelocityX(-PLAYER_SPEED);
			}
			@Override
			protected void onActionEnd() {
				idle.setScaleX(-.25);
				idle.setScaleY(.25);
				player.getViewComponent().setAnimatedTexture(idle, true, false);
			}
		}, KeyCode.LEFT);
		
		input.addAction(new UserAction("jump") {
			@Override
			protected void onAction() {
				player.getComponent(PhysicsComponent.class).setVelocityY(-500);
			}
		}, KeyCode.UP);
	}
	
	@Override
	protected void initGame() {
		getGameWorld().addEntityFactory(new Platformer_Factory());
		getGameWorld().setLevelFromMap("map_1.tmx");
		player = getGameWorld().spawn("player", 100, 100);
		getGameScene().getViewport().bindToEntity(player, getWidth()/2-150, getHeight()/2-200);
	}
	
	public static void main(String[] args) {
		launch(args);
	}

}`
![for_almasb](https://user-images.githubusercontent.com/32464706/40917991-0a4fbe54-67d3-11e8-8bce-c0524693add8.gif)

**Comment by bturner1273** [comment]
The level works if I load it initially from the initGame method so it isn't a factory problem or anything

**Comment by bturner1273** [comment]
Also in the previous versions I used .json and it did this too I don't know if that helps with anything, now I am just using tmx

**Comment by AlmasB** [comment]
How do you know that the level isn't loaded? I think your viewport is still bound to the player in level 1, and when you load the next level, your viewport is elsewhere?

**Comment by bturner1273** [comment]
I unbound it and zoomed out on collision as well and it still didn't load the level. I also tried just unbinding the entity in the first place and making the screen width and height larger all to no avail

**Comment by bturner1273** [comment]
![image](https://user-images.githubusercontent.com/32464706/40918670-fee8c2de-67d4-11e8-9f8d-ff3a2c94200a.png)

the tmx parser is being called twice.

**Comment by bturner1273** [comment]
So it looks like the map is loading because I switched from level 2 to level 1 instead and my player is still picking up coins on level one after hitting the door on level 2 but I can't bind the viewport to the player entity again for some reason so I can't see where the map is or what is going on

**Comment by bturner1273** [comment]
I'm stupid, issue closed.
Basically what I didn't realize is that on loading another level FXGL must do some garbage collection because I was having issues when trying to remove the player entity from the world and respawn it as a new entity. When I just spawned a new entity instead of trying to get rid of the old one and just set the player reference to it it worked (I assume because FXGL already collected the old entity because it wasn't being displayed on the canvas?)
