### ISSUE TITLE
Full Tiled Object Layer Support

### ISSUE THREAD

**Issue by bturner1273** [AlmasB/FXGL#555]
currently only square object layer shapes are recognized from tiled, maybe in a future version more could be covered? The circle and polygon object layer tools (mostly the polygon one) would be extremely helpful. Could the polygons in the tiled object layer be directly translated into BoundingShape.chain?

**Comment by AlmasB** [comment]
Definitely a useful feature to have. Polygons would be translated to BoundingShape.polygon()

**Comment by AlmasB** [comment]
- [X] polygon
- [ ] circle
