### ISSUE TITLE
Fix and improve API documentation links

### ISSUE THREAD

**Issue by ianbrandt** [AlmasB/FXGL#556]
There are a few areas of the documentation that could be improved as it relates to API documentation:
* https://github.com/AlmasB/FXGL/wiki/Input links to http://almasb.github.io/FXGL/javadoc/com/almasb/fxgl/input/Input.html, but that 404s.
* The docs shield on the README links to JavaDoc that only includes the com.almasb.fxgl.extra packages
* As the docs shield is an image, a browser text search of the README for "doc" or "api" yields no result.

**Comment by ianbrandt** [comment]
I'm working on a pull request for this.

**Comment by AlmasB** [comment]
PR merged.

For point 1, I have removed the link since there is no javadoc generated for `Input.kt`. We might able to integrated dokka into the workflow for generating doc for Kotlin eventually.
