### ISSUE TITLE
ViewComponent - AnimatedTexture

### ISSUE THREAD

**Issue by AlmasB** [AlmasB/FXGL#578]
the view needs to check if an animated texture was set, then somehow keep it updated, so that we can remove `FXGL.get*` call from AnimatedTexture

**Comment by bturner1273** [comment]
@AlmasB Is this what gives me NullPointerExceptions out of nowhere when animating? I have an animation function that sets an animation channel to an animated texture and adds it to an entity until the end of the loop. I only add the animated texture to the entity if the animated texture != null but somehow I still get null pointer exceptions in the setAnimatedTexture method whenever a bunch of stuff starts exploding on the screen

**Comment by AlmasB** [comment]
Done in 11.0
