### ISSUE TITLE
Ubuntu 18.04 App runs to fast

### ISSUE THREAD

**Issue by gchaperon** [AlmasB/FXGL#579]
I was playing around with the library and the game examples and the games were running to fast. I then found the solution to the problem on Ubuntu 16.04 in the [wiki](https://github.com/AlmasB/FXGL/wiki/Known-Issues) but it did not work in my system.
I am using IntelliJ IDE and I tried adding the option in Run>Edit Configurations>VM options and it didn't work.
Finally I tried running any game from the binaries folder in the FXGLGames repo from the terminal with `java -jar -Dquantum.mutithreaded=false ...` and it also didn't fix the problem.

I was thinking about just running the whole app slower via a global configuration but i couldn't find anything like it in the API.

**Comment by AlmasB** [comment]
I'm afraid there isn't much we can do on our side. I believe it's this [bug](https://bugs.openjdk.java.net/browse/JDK-8181764) in JavaFX.

Alternatively, we can get #343 done, but there are some things that rely directly on the JavaFX pulse being fired at correct times. So, not sure if slowing down the engine will help, I suppose at the very least we could try. Let me know your thoughts and how you want to proceed.

**Comment by GabrielChaperon** [comment]
I tried running `export _JAVA_OPTIONS="-Dquantum.multithreaded=false"` before `java -jar ...` as sugested in the bug report and indeed it fixed the speed problem. Curiously enough it also fixed another minor problem. The stats that appear on the bottom left corner of the screen when using `setProfilingEnabled(true)` were a little of the screen, as shown here
![asd](https://user-images.githubusercontent.com/21991723/43340918-e7a39ac6-91ab-11e8-83f9-54a0179d716b.png)


However some other problems appeared. Some games now run extremely slow (???), some others don't load sound (fail to start completely) and some others now have an extra white border en the side.

Considering all this I will continue my project on Windows, I guess it's the easiest fix for now.
Thank you very much for your time.

**Comment by AlmasB** [comment]
Thank you for your feedback. I have not done any testing on 18.04, only on 16.04. For sound loading problems, if it's "mp3", then it's likely that your environment is missing the required codec.

If working on Windows is a possibility, then it might indeed be a good idea. As for Linux support, it would be great to have someone who uses Linux as a primary platform to contribute some patches.

**Comment by Madave94** [comment]
Is there an update to the fast running game issue i didn't find somewhere? It appears to me that the bug still exists within JavaFX, I ran the current version of the Pong Game and also my own Game, both seems to run way to fast.
I use Linux Mint 19.1.

**Comment by AlmasB** [comment]
@Madave94 Hi, yes the [bug](https://bugs.openjdk.java.net/browse/JDK-8181764) (and its newer openjfx [version](https://github.com/javafxports/openjdk-jfx/issues/483)) still exists. The workaround `-Dquantum.multithreaded=false` works on Ubuntu 16.04, can't say for other platforms. Unfortunately, it isn't something we can fix from this side.

**Comment by Madave94** [comment]
I was able to find a workaround which is unfortunately slightly inconvenient. Adding `System.setProperty("quantum.multithreaded", "false");` to `the public static void main(String[] args)` call before `launch(args);` seems to solve the problem.
The workaround was described [here](https://stackoverflow.com/questions/45812036/javafx-60-fps-frame-rate-cap-doesnt-work). I tested it with the [Mario game](https://github.com/AlmasB/FXGLGames/tree/master/Mario) and my own game. I assume that fix will also work for all other Linux versions based on Ubuntu 18 (bionic).

**Comment by AlmasB** [comment]
Thanks for this. It gives me an idea: launch() goes through some fxgl code
before reaching javafx. We could check the platform and set the false flag
before quantum is initialized. Please can you reopen the issue so I won't
forget to try this

**Comment by Madave94** [comment]
> Please can you reopen the issue so I won't forget to try this

Actually i am not the original owner of this issue so I cannot reopen it ;)
Thanks for your help!

**Comment by AlmasB** [comment]
@Madave94 no problem, managed to get to the PC without forgetting :)

Will try your workaround today afternoon, hopefully you will be able to test it using `dev-SNAPSHOT` version. Will let you know

**Comment by AlmasB** [comment]
@Madave94 when CI finishes building, you can get it at:
```
<dependencies>
    <dependency>
        <groupId>com.github.almasb</groupId>
        <artifactId>fxgl</artifactId>
        <version>dev-SNAPSHOT</version>
    </dependency>
</dependencies>

<repositories>
    <repository>
        <id>oss.sonatype.org-snapshot</id>
        <url>http://oss.sonatype.org/content/repositories/snapshots</url>
    </repository>
</repositories>
```

To test, you will need to remove your own `System.setProperty("quantum.multithreaded", "false");` and see if it works

**Comment by Madave94** [comment]
I made a test with my own game excluding the `System.setProperty("quantum.multithreaded", "false");` and it seems to work. I was not able to test it with the Mario game since some parts of the Viewport API seem to be changed.
Is there any possible use case when multi threading will be useful for the game or does it always run on one core only? (eg. mobile phone android deployment?)

**Comment by AlmasB** [comment]
FXGL always runs in multithreaded mode, e.g. game initialization and loading is done on FXGL background thread, entities have their own thread for preloading, networking has its own thread, etc. 

The above property that is being set to false, as I understand, disables multithreading for the JavaFX quantum renderer, but I'm not sure what implications it has.

**Comment by AlmasB** [comment]
FXGL 11.5 was tested on Ubuntu 16.04 and no changes from client side are necessary (the workaround above is implemented internally).
