### ISSUE TITLE
Logger should have log level trace

### ISSUE THREAD

**Issue by coldwarrl** [AlmasB/FXGL#580]
A common log level, which is currently missing, is 'TRACE'. I would like to use it for very verbose debug msgs. I would volunteer to implement it.

**Comment by AlmasB** [comment]
I believe we already discussed increasing log levels. However, I am quite happy with the variety that exists and suggest that you use `debug()`. If you absolutely need a different identifier, how about function extension:

```
fun Logger.trace(message: String) {
    // ...
}
```

**Comment by coldwarrl** [comment]
The reasoning behind that is that trace messages are usally much more verbose and you seldom configure them. A usecase is for instance to trace a procedural content generator (terrain). If you use the debug level for it, your whole log gets cluttered, although you only need it if you have issues with the generator.

But the extension function is also fine with me...
