### ISSUE TITLE
"import com.almasb.fxgl.settings.GameSettings;" where is "GameSettings"? I can't find it.

### ISSUE THREAD

**Issue by gogoqiu** [AlmasB/FXGL#583]
import com.almasb.fxgl.asset.AssetLoader;
import com.almasb.fxgl.audio.AudioPlayer;
import com.almasb.fxgl.core.logging.*;
import com.almasb.fxgl.entity.GameWorld;
import com.almasb.fxgl.event.EventBus;
import com.almasb.fxgl.gameplay.GameState;
import com.almasb.fxgl.gameplay.Gameplay;
import com.almasb.fxgl.gameplay.notification.NotificationService;
import com.almasb.fxgl.input.Input;

import com.almasb.fxgl.settings.GameSettings;
import com.almasb.fxgl.settings.ReadOnlyGameSettings;

...

**Comment by AlmasB** [comment]
It's [here](https://github.com/AlmasB/FXGL/blob/master/fxgl-base/src/main/kotlin/com/almasb/fxgl/settings/Settings.kt) under `kotlin/com/almasb/fxgl/settings/Settings.kt`
