### ISSUE TITLE
Localisation

### ISSUE THREAD

**Issue by Risa123** [AlmasB/FXGL#585]
I think that it would be great add ability to add more languages than just GERMAN,ENGLISH,FRENCH and etc.

**Comment by AlmasB** [comment]
Agreed, but I haven’t had any contributions for other languages

**Comment by Risa123** [comment]
I mean that Language is enum so i as developer im unable to add more languages.

**Comment by AlmasB** [comment]
I see, you want to be able to add languages at runtime, without modifying the FXGL source code?

**Comment by Risa123** [comment]
yes

**Comment by AlmasB** [comment]
@Risa123 why was this closed? I think it's a nice feature to have - addition of languages at runtime

**Comment by Risa123** [comment]
No new posts.
