### ISSUE TITLE
FXGL 0.5.4 InputMapping problem

### ISSUE THREAD

**Issue by jspink56** [AlmasB/FXGL#586]
I tried playing the SpaceInvaders demo app from the FXGL Games package and the player ship would not move with the A/D keys or shoot with the left mouse button.

I replaced the addInputMapping code with addAction for each of the keys and it works OK now.

**Comment by AlmasB** [comment]
@jspink56 thanks for this. It was [already fixed](https://github.com/AlmasB/FXGL/commit/c696ac82f50dc20464c389cf0596691ce99d2606) for 0.5.5
