### ISSUE TITLE
Migrating from 0.4.0 to 0.5.4

### ISSUE THREAD

**Issue by Polkasa** [AlmasB/FXGL#587]
Hello
I starded migrating my game from 0.4.0 to 0.5.4, can you tell me how to fix this problem right now ?
<img width="425" alt="error" src="https://user-images.githubusercontent.com/7520445/49633143-8eee7d00-f9f8-11e8-9e11-2ea9913aa108.PNG">
<img width="321" alt="error2" src="https://user-images.githubusercontent.com/7520445/49633144-8eee7d00-f9f8-11e8-874e-bf8a02c30f13.PNG">

@edit 1
How about this, last i had:
`getPhysicsWorld().setGravity(0,30);`
But now it seems that my character falls slower, how i can fix this ? Is there some multiplier changed ? How i can get the speed from 0.4.0 ?

**Comment by Polkasa** [comment]
Ok i figured all out. It looks like in my first error that this lines can be commented out. OK, about the last problem i just smpy changed
`getPhysicsWorld().setGravity(0,30);`
to
`getPhysicsWorld().getJBox2DWorld().setGravity(new Vec2(0.0F, -30.0F));`
It might help some ppl :)

**Comment by AlmasB** [comment]
Yes, it's been a while but I think the new unit system is pixels per second rather than meters per second
