### ISSUE TITLE
Building house from sprite with house elements

### ISSUE THREAD

**Issue by PawelSzymanski89** [AlmasB/FXGL#594]
I have great sprite from: https://opengameart.org/

![medieval_building_tiles](https://user-images.githubusercontent.com/26041449/50926170-a89a3e80-1454-11e9-8d4d-bf90a8ce70f2.png)

Im not sure how to build houses from this sprite in game app is it possible? or i have to use gimp for example than add ready building to game as single file?

**Comment by AlmasB** [comment]
there is no built-in support for that. Also I don't think it is viable to provide any sort of implementation as there are many ways to lay out a sprite sheet

**Comment by PawelSzymanski89** [comment]
ok so ill gimp it :D thanks
