### ISSUE TITLE
Create a Kotlin tutorial

### ISSUE THREAD

**Issue by PascalLeMerrer** [AlmasB/FXGL#595]
At first sight, it looks like all learning resources are Java based; Are there any video or written tuto to create a game using Kotlin and not Java?

**Comment by AlmasB** [comment]
Hi, there are no kotlin tutorials, but there are two games in Kotlin - please see [here](https://github.com/AlmasB/FXGLGames#projects-by-difficulty)

**Comment by AlmasB** [comment]
Here's a [first Kotlin tutorial](https://github.com/AlmasB/FXGL/wiki/Kotlin---Basic-Game-Example-(FXGL-11)) using FXGL 11. At the moment it's a very early draft. Once the draft is finalized, the issue will be closed.

**Comment by johanburati** [comment]
@AlmasB how do you compile it on the command line ? 

I tried this but getting errors:

```
$ kotlinc firsttutorial.kt -include-runtime -d firsttutorial.jar 
```

**Comment by AlmasB** [comment]
I haven't used kotlinc directly -- given there are dependencies on FXGL (and transitively on javafx), it's much more convenient to use maven or gradle. See [this project](https://github.com/AlmasB/FXGLGames/tree/master/OutRun) for example

**Comment by johanburati** [comment]
Thanks @AlmasB 
I have installed maven and was able to build [OutRun](https://github.com/AlmasB/FXGLGames/tree/master/OutRun), however when I try to run it I am getting the following, any idea on how to fix that ?

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:49 min
[INFO] Finished at: 2020-01-27T14:25:34+09:00
[INFO] ------------------------------------------------------------------------

$ java -jar target/original-OutRun-0.3.5.jar
no main manifest attribute, in target/original-OutRun-0.3.5.jar
```

**Comment by AlmasB** [comment]
@johanburati `mvn package` should produce two jars. Try the other one and let me know if it works.

**Comment by johanburati** [comment]
Indeed, there is another one, I am getting this when I try to run it:
```
$ java -jar target/OutRun-0.3.5.jar
Error: Main method not found in class com.almasb.fxglgames.outrun.OutRunApp, please define the main method as:
   public static void main(String[] args)
or a JavaFX application class must extend javafx.application.Application
```

**Comment by AlmasB** [comment]
@johanburati this should be fixed now, sorry for delayed fix
