### ISSUE TITLE
RenderLayer dynamic update

### ISSUE THREAD

**Issue by Polkasa** [AlmasB/FXGL#597]
Hello,
I wonder if there is possibility to check if my entity is under another. I mean that i creating game with view from TOP, now all character is on one render layer and some characters steps on another, i wanted to make that when one entity are closing to another, then render layer will change to one up or one down, is there an easy way to achieve that ?

@edit 
This screen shows bad situation
<img width="81" alt="situation" src="https://user-images.githubusercontent.com/7520445/51678302-38ef8c00-1fdc-11e9-9d89-503cbaa1fecd.PNG">

the top character must be above middle, and bottom character must be in front of middle

**Comment by AlmasB** [comment]
Hi,

Unless you track those manually, I don't think there is a way to say go one up or down. Theoretically, if you know the ordering, i.e. you can define what it means to be close or to be far, then maybe you can create a javafx IntegerBinding. If you go by the Y value, then your final render layer is current + Y.

```
// some pseudocode, may or may not work
var finalLayer = Bindings.createIntegerBinding( () -> currentLayer.index + y, entity.yProperty() );
entity.renderLayerProperty().bind(finalLayer);
```

**Comment by Polkasa** [comment]
> Hi,
> 
> Unless you track those manually, I don't think there is a way to say go one up or down. Theoretically, if you know the ordering, i.e. you can define what it means to be close or to be far, then maybe you can create a javafx IntegerBinding. If you go by the Y value, then your final render layer is current + Y.
> 
> ```
> // some pseudocode, may or may not work
> var finalLayer = Bindings.createIntegerBinding( () -> currentLayer.index + y, entity.yProperty() );
> entity.renderLayerProperty().bind(finalLayer);
> ```

Thanks for helping me out 👍 . I increase and decrease render layer by Y position of entity, and this works very well
