### ISSUE TITLE
How to use SensorCollisionHandler

### ISSUE THREAD

**Issue by Polkasa** [AlmasB/FXGL#598]
Hello!
Entity object have method "addSensor(HitBox box, SensorCollisionHandler handler)", so i added one. From debug it looks that the BBOX is visible. I made new SensorCollisionHandler and made simple System.println in method onCollision, but when i run my game and Entity hit other entity then i cannot see the message. How i can use this SensorCollisionHandler?

**Comment by AlmasB** [comment]
Hi, as far as I can remember only onCollisionBegin() and onCollisionEnd() are implemented so far.

**Comment by Polkasa** [comment]
> Hi, as far as I can remember only onCollisionBegin() and onCollisionEnd() are implemented so far.

Can you give me a simple code usage for SensorCollisionHandler, because i cannot find such tutorial and example

**Comment by AlmasB** [comment]
Try calling this `addSensor(HitBox box, SensorCollisionHandler handler)` as before but using `onCollisionBegin()` to print info. Then as far as I can remember, both entities need to have `PhysicsComponent` to be able to trigger the sensor
