### ISSUE TITLE
Assets not found / Project Structure not working properly

### ISSUE THREAD

**Issue by Mauro1337** [AlmasB/FXGL#599]
Hi there, 

I´m trying to make a Mario-like game. Problem now is that the assets won´t be found. I am using uber-jar and ararnged the Directory Structure like described here: https://github.com/AlmasB/FXGL/wiki/Directory-Structure. Even when trying the Structure for Maven it isn´t working. But before it worked. 
The files i´m searching for are located in src/assets/textures and src/assets/json for uber-jar.
Maven: src/main/resources/assets/textures and src/main/resources/assets/json.

Thanks in advance

**Comment by Mauro1337** [comment]
That´s the error Message:

Fatal exception occurred: java.lang.IllegalArgumentException : Failed to load asset: mario.png. Cause: Asset "/assets/textures/mario.png" was not found!
E: com.almasb.fxgl.asset.AssetLoader.loadFailed(AssetLoader.kt:737)
E: com.almasb.fxgl.asset.AssetLoader.loadTexture(AssetLoader.kt:237)
E: com.almasb.fxgl.app.DSLKt.texture(DSL.kt:86)
E: MarioFactory.newMario(MarioFactory.java:26)
E: java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
E: java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
E: java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
E: java.base/java.lang.reflect.Method.invoke(Method.java:564)
E: com.almasb.fxgl.core.reflect.ReflectionUtils.lambda$null$1(ReflectionUtils.java:79)
E: com.sun.proxy.$Proxy5.apply(Unknown Source)
E: com.almasb.fxgl.entity.GameWorld$create$2.invoke(GameWorld.kt:436)
E: com.almasb.fxgl.entity.GameWorld$create$2.invoke(GameWorld.kt:35)
E: com.almasb.fxgl.app.DSLKt.tryCatchRoot(DSL.kt:476)
E: com.almasb.fxgl.entity.GameWorld.create(GameWorld.kt:436)
E: com.almasb.fxgl.entity.GameWorld.spawn(GameWorld.kt:413)
E: com.almasb.fxgl.entity.GameWorld.spawn(GameWorld.kt:401)
E: com.almasb.fxgl.app.DSLKt.spawn(DSL.kt:160)
E: MarioApp.initGame(MarioApp.java:30)
E: com.almasb.fxgl.app.GameApplication.internalInitGame(GameApplication.java:238)
E: com.almasb.fxgl.app.LoadingState$InitAppTask.initGame(AppStates.kt:168)
E: com.almasb.fxgl.app.LoadingState$InitAppTask.call(AppStates.kt:138)
E: com.almasb.fxgl.app.LoadingState$InitAppTask.call(AppStates.kt:127)
E: javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
E: java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
E: java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
E: java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
E: java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
E: java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
E: java.base/java.lang.Thread.run(Thread.java:844)

**Comment by AlmasB** [comment]
Based on what you provided, it seems your IDE is acting up. Try full clean of your project, or create a new project in your IDE and see if it works.

**Comment by Mauro1337** [comment]
Alte

Am 07.02.2019 um 18:39 schrieb Almas Baimagambetov <notifications@github.com<mailto:notifications@github.com>>:


Based on what you provided, it seems your IDE is acting up. Try full clean of your project, or create a new project in your IDE and see if it works.

**Comment by Mauro1337** [comment]
Already did that...

**Comment by Mauro1337** [comment]
Same issue

**Comment by Mauro1337** [comment]
It was actually an issue in the json file generated by tiled

**Comment by ghost** [comment]
I just had this same problem, creating a new project in intelij, with the tickbox to include FXGL in the POM for you. Everything works well, but it can't find the textures unless you open 'module-info.java' and insert:
`opens assets.textures;`
Very annoying 😁

**Comment by Aper-mesa** [comment]
> I just had this same problem, creating a new project in intelij, with the tickbox to include FXGL in the POM for you. Everything works well, but it can't find the textures unless you open 'module-info.java' and insert: `opens assets.textures;` Very annoying 😁

This is even helpful in 2025. Thanks!
