### ISSUE TITLE
Setting render layer of tiled layer

### ISSUE THREAD

**Issue by mikeant42** [AlmasB/FXGL#600]
I would like to change the render layer of a layer in tiled, e.g. to draw the layer over other entities in my game. Is this currently supported?

**Comment by AlmasB** [comment]
I don't think it is supported. I'm happy to add this to todo list for fxgl 11+, but for now if it's viable then you can set a Tiled property to your objects, e.g. `layer = 2`, then using FXGL you can set render layer as appropriate:

```
Entity e = ...
int layer = e.getPropertyInt("layer");
// set render layer
```

**Comment by mikeant42** [comment]
Thanks, this is a feature I'd like to see happen.

For now I can see how drawing tiles in the object layer will work.

**Comment by AlmasB** [comment]
@mikeant42 Hi, I'm currently re-introducing Tiled support to FXGL 11. Can you provide more information on how this is stored in the `.tmx` file and what the behaviour should be. Thanks
