### ISSUE TITLE
Reposition for rotation

### ISSUE THREAD

**Issue by bturner1273** [AlmasB/FXGL#614]
So I am making a flappybird clone and would like to linear interpolate my y-velocity onto my rotation. However, I have a dynamic bodydef on my flappybird and therefore it is acting as a physics object and have to play with its angular velocity instead of its rotation directly. 

Is there a good way at getting around this that doesn't involve me just using translates and making a gravity function? I am using this to teach game engines to kids and would rather not have to take them through implementing gravity with change dy by g, change y by dy if the engine does it for me already.

**Comment by bturner1273** [comment]
also is there a debug mode implemented in the 11 beta yet to view fixtures within the game?

**Comment by AlmasB** [comment]
So the question is, whether you can set rotation directly for a physics controlled entity? At the moment, probably not, but I agree this is a useful functionality. Please confirm that I understood what you want correctly.

You can access the developer menu from the latest build by pressing `1`. Your game needs to be _not_ on release mode.

To access the latest build using maven, use version `dev-SNAPSHOT` and add to pom.xml:

```
    <repositories>
        <repository>
            <id>oss.sonatype.org-snapshot</id>
            <url>http://oss.sonatype.org/content/repositories/snapshots</url>
        </repository>
    </repositories>
```

**Comment by AlmasB** [comment]
Also for clarity, if you could provide a screenshot of what you have and explain what you need, it would be helpful too. Thanks

**Comment by bturner1273** [comment]
![for_fxgl_help](https://user-images.githubusercontent.com/32464706/55975562-3f46e900-5c58-11e9-8c97-cc827d122278.gif)

so I have my rotation function but it is pretty janky:
![image](https://user-images.githubusercontent.com/32464706/55975629-656c8900-5c58-11e9-8ccb-cb748298b7dd.png)

and yeah I am looking to set the rotation directly using entity.setRotation() with a LERP based on my y-velocity

**Comment by bturner1273** [comment]
![for_fxgl_help](https://user-images.githubusercontent.com/32464706/55975562-3f46e900-5c58-11e9-8c97-cc827d122278.gif)

so I have my rotation function but it is pretty janky:
![image](https://user-images.githubusercontent.com/32464706/55975629-656c8900-5c58-11e9-8ccb-cb748298b7dd.png)

and yeah I am looking to set the rotation directly using entity.setRotation() with a LERP based on my y-velocity

**Comment by bturner1273** [comment]
![for_fxgl_help](https://user-images.githubusercontent.com/32464706/55975562-3f46e900-5c58-11e9-8c97-cc827d122278.gif)

so I have my rotation function but it is pretty janky:
![image](https://user-images.githubusercontent.com/32464706/55975629-656c8900-5c58-11e9-8ccb-cb748298b7dd.png)

and yeah I am looking to set the rotation directly using entity.setRotation() with a LERP based on my y-velocity

**Comment by bturner1273** [comment]
![for_fxgl_help](https://user-images.githubusercontent.com/32464706/55975562-3f46e900-5c58-11e9-8c97-cc827d122278.gif)

so I have my rotation function but it is pretty janky:
![image](https://user-images.githubusercontent.com/32464706/55975629-656c8900-5c58-11e9-8ccb-cb748298b7dd.png)

and yeah I am looking to set the rotation directly using entity.setRotation() with a LERP based on my y-velocity

**Comment by AlmasB** [comment]
Great! This is very helpful. I will look into this in the evening, meanwhile can you provide feedback on the developer menu in `dev-SNAPSHOT`. At the moment it only captures hit boxes and game variables and I'm looking for useful things to include in that menu

**Comment by bturner1273** [comment]
the new menu is awesome! The only useful feature I can think to include with it is maybe adding public variables from EntityComponents if that is possible.

like in the menu you could have:

Entity Name (dropdown)
          -> components (dropdown in entity drop down)
                  ->public vars list for specific component in component drop down

Maybe even let the coder play around with the values? This could be totally not feasible and I would get that...

**Comment by AlmasB** [comment]
Yes, this is a very good idea. In terms of implementation this is reasonably simple, though certain variables are likely to be read-only, especially if they are bound to other variables. I can see how powerful this can be.

Please can you open a new issue with what you've included here, so I can keep track of this.

**Comment by AlmasB** [comment]
The new build should have gone through by now. Please can you try `physicsComponent.overwriteAngle()` using the latest `dev-SNAPSHOT` (you may need to tell the IDE to reimport / reupdate dependencies)

**Comment by bturner1273** [comment]
'
       @Override
        protected void initGame() {
                //blah blah blah
                run(() -> {
			rotate();
		}, Duration.millis(100));
	}
	
	private void rotate() {
		flappybird.getComponent(PhysicsComponent.class).overwriteAngle(
				lerp(flappybird.getComponent(PhysicsComponent.class).getVelocityY(),
						-450, 1000, -45, 45));		
	}
	
	private double lerp(double num, double min, double max, double new_min, double new_max) {
		return (((num-min)/(max-min)) * (new_max - new_min)) + new_min;
	}
'

new rotate function is much cleaner and works much better with the new overwriteAngle function! Much appreciated!

![fxgl_overwriteAngle_demo](https://user-images.githubusercontent.com/32464706/56141959-d1f2cb00-5f6b-11e9-95d4-f0579286bedd.gif)
