### ISSUE TITLE
Ragged Sprite Sheet support

### ISSUE THREAD

**Issue by bturner1273** [AlmasB/FXGL#619]
If your sprite sheet isn't square then you kinda run into some issues in FXGL. The simplest way I can think to resolve this is to make an add function for animation channels so that one animation can be split up into multiple stages and just added together into one channel. Is this something that is possible?

**Comment by bturner1273** [comment]
![image](https://user-images.githubusercontent.com/32464706/56509816-f4e62780-64f5-11e9-92c1-b174bf20105f.png)

^^ see how I have a column drop off randomly? If I could just split it up into two different animations and concatenate them then that would be fantastic.

**Comment by AlmasB** [comment]
1. Do all images represent a single animation channel?
2. Do all images have the same size, if not then #414 is a pre-requisite

Assuming 1 and 2 are true, the problem is loading a channel when not all "frames" in the sprite sheet are populated.

A solution may be of form:

```
AnimationChannel(image, number of frames (empty or not) per row, duration of channel, data...)
```

where each `data` would contain `frame width, frame height, start frame, end frame`. I believe this generalizes to uneven image sizes as well. Would this work?

**Comment by bturner1273** [comment]
yeah they are different sizes but I ended up just formatting it so that all the images are in one huge column with a texture packing software called strip generator. Would the data points just be a list of all the blank spaces? If so that would be pretty awesome.

**Comment by AlmasB** [comment]
I was actually thinking the opposite, the data objects would provide info on non-blank frames, plus we are able to specify the size for each frame in case frames have different sizes

**Comment by bturner1273** [comment]
makes sense. I do however feel like the frame sizes usually come in batches so like frame 0-4 might be one size then 5-9 a different size so would there be a way to specify a batch at a time? Data point by data point on every frame might be a bit inefficient to program

**Comment by AlmasB** [comment]
Yes, that's what frame start and end are for

**Comment by AlmasB** [comment]
@bturner1273 , In the latest `dev-SNAPSHOT` we now handle the case where each frame needs to specified in terms of size. This handles the general case
```
AnimationChannel animWalk = new AnimationChannel(FXGL.image("spritesheet.png"), Duration.seconds(1), List.of(
        new Pair<>(0, new FrameData(0, 0, 32, 42)),
        new Pair<>(1, new FrameData(32, 0, 32, 42)),
        new Pair<>(2, new FrameData(32+32, 0, 32, 42)),
        new Pair<>(3, new FrameData(32+32+32, 0, 32, 42))
));
```
where `FrameData ( x, y, width, height )`, `Pair` class is `import kotlin.Pair;`

For convenience, also:
```
AnimationChannel animWalk = new AnimationChannel(FXGL.image("spritesheet.png"), Duration.seconds(1.5), 7, List.of(
        new AnimationChannelData(21, 26, 77, 37),
        new AnimationChannelData(28, 33, 77, 37),
        new AnimationChannelData(35, 40, 77, 37)
));
```

where 7 is frames per row, assuming all frames are same size in the sprite sheet, `AnimationChannelData( frameStart, frameEnd, frameWidth, frameHeight)`

The previous AnimationChannel API remains the same, only the internals have changed. Please have a look at it and see if it works for your use case, when you get a chance

**Comment by AlmasB** [comment]
This has been implemented for some time with example usage [here](https://github.com/AlmasB/FXGL/blob/master/fxgl-samples/src/main/java/sandbox/AnimationComponent.java#L47)
