### ISSUE TITLE
Custom cursor gets overridden by default

### ISSUE THREAD

**Issue by reptar25** [AlmasB/FXGL#633]
It looks like if you try to set a custom cursor from initUI (or any other init method in GameApplication) it gets reset to the default cursor afterwards from the registerScene method in MainWindow.kt class when the main game loop starts.

**Comment by AlmasB** [comment]
Thanks, I'll have a look at it today.

**Comment by AlmasB** [comment]
Fixed in the next release. If you don't want to wait till next release:
```
<dependencies>
    <dependency>
        <groupId>com.github.almasb</groupId>
        <artifactId>fxgl</artifactId>
        <version>dev-SNAPSHOT</version>
    </dependency>
</dependencies>

<repositories>
    <repository>
        <id>oss.sonatype.org-snapshot</id>
        <url>http://oss.sonatype.org/content/repositories/snapshots</url>
    </repository>
</repositories>
```
