### ISSUE TITLE
AssetLoader doesn't have access to assets folder in a modular project

### ISSUE THREAD

**Issue by jperedadnr** [AlmasB/FXGL#644]
When the project is modular, since `AssetLoader` is in a different module, it doesn't have access to the `assets/sound` or `assets/texture` resources folders.

```
Fatal exception occurred: java.lang.IllegalArgumentException : Failed to load asset: brick.png. Cause: Asset "/assets/textures/brick.png" was not found!
E: com.almasb.fxgl.all/com.almasb.fxgl.app.AssetLoader.loadFailed(AssetLoader.kt:628)
E: com.almasb.fxgl.all/com.almasb.fxgl.app.AssetLoader.loadTexture(AssetLoader.kt:158)
E: com.almasb.fxgl.all/com.almasb.fxgl.dsl.FXGL$Companion.texture(FXGL.kt:203)
E: com.almasb.fxgl.all/com.almasb.fxgl.dsl.EntityBuilder.view(EntityBuilder.kt:96)
E: hellofx/org.openjfx.BasicGameApp.initGame(BasicGameApp.java:78)
```

which is caused by:
`GameApplication.FXGLApplication.app?.javaClass?.getResource(name)` being null, in `AssetLoader::getURL.

There are a few options to solve this (using `getClassLoader().getResource()` should do it, and it is the simplest way. Other options involve something more complex like `ModuleLayer.boot().findModule(moduleName)...`)

**Comment by AlmasB** [comment]
I think I tried various approaches. Will check. Does making the end user
module “open” fix that?

**Comment by jperedadnr** [comment]
No, if you do:

```opens assets.sounds;
    opens assets.textures;
    ```
you get:
```Error occurred during initialization of boot layer
java.lang.module.FindException: Error reading module: /.../hellofx/build/classes/java/main
Caused by: java.lang.module.InvalidModuleDescriptorException: Package assets.textures not found in module
```

**Comment by AlmasB** [comment]
I meant

open module bla-bla {
    requires com.almasb.fxgl ...
}

**Comment by jperedadnr** [comment]
Yes, that works. But I wouldn't do it...

**Comment by AlmasB** [comment]
Fair enough. I’ll see if classloader approach works.

**Comment by AlmasB** [comment]
`GameApplication.FXGLApplication.app?.javaClass?.classLoader?.getResource(name)` also fails, is this the right class loader?

**Comment by jperedadnr** [comment]
Could you do a quick check with `GameApplication.FXGLApplication.app?.javaClass?.classLoader?.getResourceAsStream(name)` ?

**Comment by AlmasB** [comment]
Sure

**Comment by AlmasB** [comment]
Also fails, actually I looked at the source of getResourceAsStream(), it's `getResource(name).openStream()`

**Comment by jperedadnr** [comment]
We use that from Gluon Mobile to get access to some configuration files in the user's project (at the root of the resources folder), something like:
```
Configuration.class.getClassLoader().getResourceAsStream("config.json");
```

**Comment by AlmasB** [comment]
Configuration.class is Gluon Mobile's class I presume? Ok ...

**Comment by AlmasB** [comment]
Right, I've got something. I've found one approach, I don't know if it's the only one. It appears that to open a resource, it must be placed in the same package that is open to a different module, e.g.:

module samples.main {
    requires com.almasb.fxgl.all;

    // this is for reflection
    exports basics to com.almasb.fxgl.core;

    // this is for assets
    opens basics to com.almasb.fxgl.all;
}

So brick.png must be under `basics` package in some form: basics/ ... / brick.png

The problem with this is the unified assets directory architecture is ruined since everything needs to be under their respective packages for this to work

**Comment by AlmasB** [comment]
In any case, were you planning to use fxgl to test Gluon client plugin? Because I haven't yet merged changes that allow compile and run to succeed

**Comment by jperedadnr** [comment]
Following that approach, you could always add a dummy class to `assets/textures`, so that package exists and can be opened from the user's module descriptor.

But still the user has to open it. 

It should be better to have a solution that doesn't require fixed package names for resources nor opening them from the user's module descriptor.

About the Client plugin: No, I wasn't (I noticed this issue while I was checking this question https://stackoverflow.com/questions/56931096/fxgl-noclassdeffounderror-when-calling-fxgl-playdrop-wav)

**Comment by AlmasB** [comment]
I think the pragmatic workaround of declaring the module as `open` will have to do. I agree this is not ideal, but I cannot propose anything better at this stage.
