### ISSUE TITLE
NoClassDefFoundError when following basic example

### ISSUE THREAD

**Issue by davsucks** [AlmasB/FXGL#646]
Hello!

I'm interested in checking out this library, but when I follow the [Basic Game Example](https://github.com/AlmasB/FXGL/wiki/Basic-Game-Example-%28FXGL-11%29) I'm faced with an error when running the application.

I'm using gradle with kotlin. My gradle file looks like this: 
```kotlin
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    id("org.jetbrains.kotlin.jvm").version("1.3.31")
    application
}

repositories {
    jcenter()
}

tasks.withType(KotlinCompile::class.java).all {
    kotlinOptions {
        jvmTarget = "1.8"
    }
}

dependencies {
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    implementation("com.github.almasb:fxgl:11.3")
}

application {
    mainClassName = "basicgame.BasicGameAppKt"
}
```

And my application class looks like this:
```kotlin
package basicgame

import com.almasb.fxgl.app.GameApplication
import com.almasb.fxgl.app.GameApplication.launch
import com.almasb.fxgl.app.GameSettings

class BasicGameApp : GameApplication() {
    override fun initSettings(settings: GameSettings) {
        with(settings) {
            width = 600
            height = 600
            title = "Basic Game App"
            version = "0.0.1"
        }
    }
}

fun main(args: Array<String>) {
    launch(BasicGameApp::class.java, args)
}
```

The exception looks like this:
```
Exception in thread "main" java.lang.NoClassDefFoundError: javafx/scene/input/KeyCode
	at com.almasb.fxgl.app.GameSettings.<init>(Settings.kt:134)
	at com.almasb.fxgl.app.GameSettings.<init>(Settings.kt)
	at com.almasb.fxgl.app.GameApplication.takeUserSettings(GameApplication.java:117)
	at com.almasb.fxgl.app.GameApplication.launch(GameApplication.java:96)
	at com.almasb.fxgl.app.GameApplication.launch(GameApplication.java:68)
	at basicgame.BasicGameAppKt.main(BasicGameApp.kt:22)
Caused by: java.lang.ClassNotFoundException: javafx.scene.input.KeyCode
```

It looks like the scene package is missing but I'm not sure why. When I inspect the packages that gradle pulled in it does indeed look like there is no `javafx.scene` package, so I'm not sure what the issue is.

**Comment by AlmasB** [comment]
Hi, please have a look at this [FXGL 11 Gradle](https://github.com/AlmasB/FXGL11-Gradle) minimal example. Also maybe related to [this question](https://stackoverflow.com/questions/56931096/fxgl-noclassdeffounderror-when-calling-fxgl-playdrop-wav).

Please let me know if any of this helps

**Comment by davsucks** [comment]
Ahh, looks like it was the missing javafx gradle plugin, thanks!

**Comment by Inego** [comment]
> Hi, please have a look at this [FXGL 11 Gradle](https://github.com/AlmasB/FXGL11-Gradle) minimal example. Also maybe related to [this question](https://stackoverflow.com/questions/56931096/fxgl-noclassdeffounderror-when-calling-fxgl-playdrop-wav).
> 
> Please let me know if any of this helps

The link is broken.

**Comment by AlmasB** [comment]
@Inego link updated, thanks
