### ISSUE TITLE
Add controller support

### ISSUE THREAD

**Issue by AlmasB** [AlmasB/FXGL#648]
For example, [jamepad](https://github.com/williamahartman/Jamepad) looks interesting for integration

**Comment by AlmasB** [comment]
Jamepad cannot be directly integrated since it is not modular. It should be possible to write an abstraction for us to use in FXGL, which would be implemented on client side via jamepad

**Comment by Tim-Snow** [comment]
Does jamepad's successor [sdl2gdx](https://github.com/electronstudio/sdl2gdx) hold any more promise?

**Comment by AlmasB** [comment]
Thanks for the link, it appears they also use java 8, their `build.gradle` says `sourceCompatibility = 1.8`. Though the repo itself could be a good starting point for a Java 11+ modular port.

**Comment by AlmasB** [comment]
Windows support is complete. #889 and #890 are open for Linux/Mac
