### ISSUE TITLE
Allow fullscreen mode from the start and correctly sync settings / menu

### ISSUE THREAD

**Issue by AlmasB** [AlmasB/FXGL#662]
Thanks for letting me know @megaman248 I'll have a look at it

**Comment by AlmasB** [comment]
@megaman248 there is now a new setting `setFullScreenFromStart(true)` which allows the game to enter FS mode immediately (`setFullScreenAllowed(true)` is required still). Please let me know if this fixes the issues you've been having. If so, we can close this.

To get the latest build, you can use this:
```
<dependencies>
    <dependency>
        <groupId>com.github.almasb</groupId>
        <artifactId>fxgl</artifactId>
        <version>dev-SNAPSHOT</version>
    </dependency>
</dependencies>

<repositories>
    <repository>
        <id>oss.sonatype.org-snapshot</id>
        <url>http://oss.sonatype.org/content/repositories/snapshots</url>
    </repository>
</repositories>
```

**Comment by nunorfidalgo** [comment]
Hello, this worked great for me, but have to update to 11.5, the dev-SNAPSHOT didn't work.
My current problem is in the Component class on the onAdded() method the entity.setView(texture) doesn't exist and my animatation doesnn't work.

**Comment by AlmasB** [comment]
Thanks for letting me know. Updated the animation wiki: https://github.com/AlmasB/FXGL/wiki/Adding-Sprite-Animations-(FXGL-11)

**Comment by nunorfidalgo** [comment]
With works! but now the rectangle isn't transparent 
![Capture](https://user-images.githubusercontent.com/14232056/65701287-fa353880-e078-11e9-95f3-bf9162d681cf.PNG)

**Comment by AlmasB** [comment]
Please can you provide your code and the sprite sheet. Thanks

**Comment by nunorfidalgo** [comment]
yes... but it has working fine on version 11.3, just updated because of the new fullscreen option.

![Capture1](https://user-images.githubusercontent.com/14232056/65706444-68322d80-e082-11e9-80d4-dcad474f854e.PNG)

`	public EpisodeOnePlayerComponent(String type, String gender) {
		
		this.playerType = type;
		
		if(gender.matches("male")) {
			switch(type) {
			  case "Red":
				image = FXGL.image("game/EpisodeOne/boys/boy_sprites_red.png");
				break;
			  case "Blue":
				image = FXGL.image("game/EpisodeOne/boys/boy_sprites_blue.png");
				break;
			  case "Green":
				image = FXGL.image("game/EpisodeOne/boys/boy_sprites_green.png");
				break;
			  case "Yellow":
				image = FXGL.image("game/EpisodeOne/boys/boy_sprites_yellow.png");
				break;
			}
		} else {
			switch(type) {
			  case "Red":
				image = FXGL.image("game/EpisodeOne/girls/girl_sprites_red.png");
				break;
			  case "Blue":
				image = FXGL.image("game/EpisodeOne/girls/girl_sprites_blue.png");
				break;
			  case "Green":
				image = FXGL.image("game/EpisodeOne/girls/girl_sprites_green.png");
				break;
			  case "Yellow":
				image = FXGL.image("game/EpisodeOne/girls/girl_sprites_yellow.png");
				break;
			}
		}
				
		animDown = new AnimationChannel(image, 3, 32, 32, Duration.seconds(0.5), 0, 2);
		texture = new AnimatedTexture(animDown);
		
		animLeft = new AnimationChannel(image, 3, 32, 32, Duration.seconds(0.5), 6, 8);
		texture = new AnimatedTexture(animLeft);
		
		animRight = new AnimationChannel(image, 3, 32, 32, Duration.seconds(0.5), 3, 5);
		texture = new AnimatedTexture(animRight);
		
		animUp = new AnimationChannel(image, 3, 32, 32, Duration.seconds(0.5), 9, 11);
		texture = new AnimatedTexture(animUp);
		
		animIdle = new AnimationChannel(image, 3, 32, 32, Duration.seconds(1), 1, 1);
		texture = new AnimatedTexture(animIdle);

	}

	@Override
	public void onAdded() {
//		entity.setView(texture);
		entity.getTransformComponent().setScaleOrigin(entity.getCenter());
		entity.getViewComponent().addChild(texture);		
	}`

**Comment by nunorfidalgo** [comment]
my player spawns like this:
`@Spawns("PlayerRed")
	public Entity spawnsPlayerRed(SpawnData data) {
		physicsPlayer = new PhysicsComponent();
		physicsPlayer.setBodyType(BodyType.DYNAMIC);
		physicsPlayer.setFixtureDef(new FixtureDef().friction(0.0f));
		return FXGL.entityBuilder()
			.from(data)
			.type(EpisodeOneType.PLAYER_RED)
			.viewWithBBox(new Rectangle(Constants.PLAYER_SIZE, Constants.PLAYER_SIZE))
			.with(physicsPlayer, new CollidableComponent(true))
			.with(new EpisodeOnePlayerComponent("Red", data.get("gender")))
			.build();
	}`

**Comment by AlmasB** [comment]
You no longer need `viewWithBBox(new Rectangle(Constants.PLAYER_SIZE, Constants.PLAYER_SIZE))`. In 11.3 it would be overwritten by the `setView` call. In 11.5 children are not automatically cleared, which allows building complex Views for entities

**Comment by nunorfidalgo** [comment]
Right, that make sense e it works great. 
THx @AlmasB
