### ISSUE TITLE
Tiled: TiledMap loader in TMXLevelLoader

### ISSUE THREAD

**Issue by Madave94** [AlmasB/FXGL#664]
I would like to access the `var map` in [TMXLevelLoader.kt](https://github.com/AlmasB/FXGL/blob/master/fxgl-entity/src/main/kotlin/com/almasb/fxgl/entity/level/tiled/TMXLevelLoader.kt). I tried to use the `parse` method to return the `TiledMap` but I always run into some `java.net.MalformedURLException: no protocol:` error. With something like this or slightly different URL paths:
`TiledMap map = new TMXLevelLoader().parse(new URL( "/main/resources/assets/levels/level0.tmx" ).openStream());`
I was not able to load the `TiledMap`. Is there something I am missing or is there a better way to get access to my map during run time?
I plan to somehow extend the map dynamically during run time (the player will build some stuff), but I want the player to stay in the grid, eg. 70x70 blocks. It would be easiest to access the `layer` part of the tiled map.

**Comment by AlmasB** [comment]
Building URL by hand can be a pain, try this:

```
var map = new TMXLevelLoader().parse(FXGL.getAssetLoader().getStream("/assets/levels/level0.tmx"));
```

For future reference, if you don't want to parse anything using asset loader and just want raw stream access, you can use `getStream()`. It can give an `InputStream` to anything located under `src/main/resources/assets/`

**Comment by Madave94** [comment]
That works! Thank you!
