### ISSUE TITLE
Enable to change the anchor of an entity

### ISSUE THREAD

**Issue by marvinbuff** [AlmasB/FXGL#676]
Currently, the anchor of an entity is its top-left corner, which is in line with JavaFx's approach. However, in a game you usually represent a physical world in which the position of an entity is supposed to be its center. It would be nice to have the option to change the anchor to the center in order to simplify interactions. 

As proposed by @AlmasB this could be implemented using a TransformComponent. By default it will still remain as top-left, but users will be able to set the origin to any point (incl. center).

**Comment by AlmasB** [comment]
@marvinbuff how about adding something like `setCenterPosition(cx, cy)`, which will set the (top-left) `x,y` in a way that the entity center will be located at `cx,cy`? Would that work for your use case?

**Comment by marvinbuff** [comment]
@AlmasB That sounds reasonable to me and is in line with how I implemented my workaround at the moment. 

To give a bit more information. I have entities which are represented by a sprite, where the center of the image representation should be placed directly where the object is in the simulated world. Currently I handle it by defining a center translation which defines the distance from the top left corner to the actual center of the sprite. Now if I want to rotate any other entity to look at this one, I need to consider the adjusted center. And of course, I also have to adjust the rotationOrigin of the transformComponent to be at the center so that I can rotate the sprite correctly.

**Comment by AlmasB** [comment]
Should now be available in version `dev-SNAPSHOT`.

To get the latest build, you can use this:
```
<dependencies>
    <dependency>
        <groupId>com.github.almasb</groupId>
        <artifactId>fxgl</artifactId>
        <version>dev-SNAPSHOT</version>
    </dependency>
</dependencies>

<repositories>
    <repository>
        <id>oss.sonatype.org-snapshot</id>
        <url>http://oss.sonatype.org/content/repositories/snapshots</url>
    </repository>
</repositories>
```

When you get a chance to test it, please let me know if this works as intended.

**Comment by marvinbuff** [comment]
I am unsure about this solution. If I understand it correctly I can now rewrite my code from 

`private fun InvaderComponent.getAdjustedPositionOld() = this.entity.position + center`
to
`private fun InvaderComponent.getAdjustedPositionNew() = this.entity.getPosition(center)`

, which ultimately is not much of an improvement. I still have to store the center and have to remember to use the correct `getPosition` method.
I would prefer if I could define a "setting" when I initialize the Entity which then would modify the standard behavior of set/get position and I can just use it as if the center is actually where I want it to be.

Does something speak against adding one method `setCenter` which would store the translation and would then always apply it on set and get position? It could even be internally be implemented by a generic transformation in order to enable any arbitrary transformation.

**Comment by AlmasB** [comment]
I see.

A lot of internal computation (physics and graphics in particular) relies
on get position being top left. So with current architecture it is not
feasible to modify these. I suppose this could be solved by renaming all
get/set/x/y to return untransformed top left coordinates + replace existing
ones to return transformed coordinates, but this seems a major change.

Storing the local anchor seems the most practical option, though you would
still need to remember to call the correct get/set methods. This addition
means you won't need store the local anchor. Let me know if this is a
suitable workaround given the above constraints.

**Comment by AlmasB** [comment]
The changes would be along the lines of:

1. TransformComponent gets a new field localAnchor: Point2D
2. two methods: get/setAnchoredPosition()
3. Entity gets convenience methods get/setAnchoredPosition() (incl. get/setAnchoredPositionCenter()) to delegate to TransformComponent

**Comment by marvinbuff** [comment]
That sounds reasonable to me. It's practically the work around I use but more integrated and safe to use.

**Comment by AlmasB** [comment]
@marvinbuff all done, please check when possible. Also, is your project open source? It would be beneficial for me to see how this and other APIs are being used in order to improve them.

**Comment by marvinbuff** [comment]
The feature looks good to me. Thanks for the effort.
Only addition I would propose is a convenience function in the EntityBuilder: `atAnchored(position, anchor)`, which would set the anchor and set the position correctly. 

I made my project public: https://github.com/marvinbuff/GalacticCombat. Check it out if you like and if you have a comment, feel free to create an issue. But as a disclaimer, it is still very rough and I don't consider it presentable yet. To see how I used your changes you can check out the latest commit and look at `TowerComponent`.

**Comment by AlmasB** [comment]
Thanks for the feedback. Yes, I'll add the convenience function.

Also thanks for sharing the project, I'll study the FXGL usage there and see if we can improve some of the FXGL API from this side.
