### ISSUE TITLE
Stop FXGL.loopBGM();

### ISSUE THREAD

**Issue by nunorfidalgo** [AlmasB/FXGL#681]
Hello @AlmasB 

How can I stop a FXGL.loopBGM(); on any given time?

Or in alternative use getAudioPlayer():
	
Music music = new Music("game.wav"); // Constructor undefined
FXGL.getAudioPlayer().loopMusic(music);
....
FXGL.getAudioPlayer().stopMusic(music);

Using version 11.5

Thanks
Keep up the good work

**Comment by nunorfidalgo** [comment]
Just figure it out:

```
String gameSong = new String("game.wav");
Music gameMusic = FXGL.getAssetLoader().loadMusic(gameSong);
FXGL.getAudioPlayer().loopMusic(Constants.menuMusic);
...
FXGL.getAudioPlayer().stopMusic(Constants.gameMusic);
```

**Comment by AlmasB** [comment]
Hi, yes, your 2nd post should do it.
