### ISSUE TITLE
Initiate error reporting

### ISSUE THREAD

**Issue by yanzhao77** [AlmasB/FXGL#698]
Error:(4, 27) java: cannot access com.almasb.fxgl.app.GameApplication
  Bad class file: /F:/mavenDownloads/com/github/almasb/fxgl/11.6/fxgl-11.6.jar!/com/almasb/fxgl/app/GameApplication.class
   Class file has wrong version  55.0, Should be 52.0
   Delete the file or make sure it is in the correct classpath subdirectory

**Comment by AlmasB** [comment]
@yanzhao77 Hi, it seems you are using 11.6 with Java 8. Either use 0.5.4 with Java 8, or use 11.6 with Java 11+. [Class file has wrong version](https://github.com/AlmasB/FXGL/wiki/Known-Issues#class-file-has-wrong-version-550--520)

**Comment by yanzhao77** [comment]
@AlmasB yes.I`m is java JDK1.8,
but i Add to plugin The same mistake

<plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.0</version>
                <configuration>
                    <release>8</release>
                </configuration>
            </plugin>

**Comment by AlmasB** [comment]
release needs to be to set to 11. The release configuration has been added later, so version 8 will not be supported.

Ultimately, if you need to use JDK8, you can only use FXGL 0.5.4.
