### ISSUE TITLE
Grid<> should have extra fields: cellWidth and cellHeight of type int

### ISSUE THREAD

**Issue by AlmasB** [AlmasB/FXGL#706]
Ctor with + ctor without

**Comment by AahzBrut** [comment]
What are the default values of cellWidth and cellHeight? 0's would be ok?

**Comment by AlmasB** [comment]
Yes, let's go with 0

**Comment by AahzBrut** [comment]
do I also need to change Cell by adding width and height to it?

**Comment by AlmasB** [comment]
No, just the grid please
