### ISSUE TITLE
Add scaleOrigin and rotationOrigin to AnimationBuilder

### ISSUE THREAD

**Issue by AlmasB** [AlmasB/FXGL#711]
In DSL animationBuilder(), we should be able to set the above via:

```
animationBuilder().scaleOrigin( ... )
animationBuilder().rotationOrigin( ... )
```

**Comment by AahzBrut** [comment]
Origins should be of type Point2D?

**Comment by AlmasB** [comment]
Yes, that's right.

I've just realised that, whilst functions above are easy, the actual implementation that makes use of origins is a slightly bigger change. If you are happy to go ahead, here's an approach that I had in mind:

1. Update `com.almasb.fxgl.animation.Animatable` with, setScaleOrigin and setRotationOrigin.
2. In AnimationBuilder, there are two extension functions: Node.toAnimatable() and Entity.toAnimatable(), which will need updating. With Entity, you can use its transformComponent to set scale and rotation origin. With Node, you will need something like this:

```
        val scale = Scale()

        // the new scale origin
        scale.pivotXProperty().set
        scale.pivotYProperty().set

       // for rotate
        val rotate = Rotate()
        rotate.axis = Rotate.Z_AXIS

        rotate.pivotXProperty().set
        rotate.pivotYProperty().set
```

In addition, in Node.toAnimatable(), the following will change to make use of the above Scale / Rotate objects appropriately. However, we should only use the above transforms if the user has set scaleOrigin / rotationOrigin via the animation builder. If not, we keep an existing implementation to avoid functionality change

```
        override fun scaleXProperty(): DoubleProperty {
            return n.scaleXProperty()
        }

        override fun scaleYProperty(): DoubleProperty {
            return n.scaleYProperty()
        }

        override fun rotationProperty(): DoubleProperty {
            return n.rotateProperty()
        }
```

3. Inside the same file, you will find class RotationAnimationBuilder and class ScaleAnimationBuilder. In both of them, there is `return makeConfig().build(`. I think the rotation / scale origins should be set just before this call. So `objects.forEach { it.setOrigin ... }`
4. I don't think existing tests need to change, but we will need a working sample to see all these changes visually

Let me know if you have the time to carefully consider this and would like to do this. If not, just leave this here, I'm happy to pick this up.

**Comment by AahzBrut** [comment]
Well, I'll take a look on the weekend and let you know if I have what it takes :)
