### ISSUE TITLE
Images.kt Pixel data structure should limit rgba values in 0-1 range

### ISSUE THREAD

**Issue by AlmasB** [AlmasB/FXGL#712]
Some blend modes in `Images.kt` file can produce a value outside of the [0..1] range, resulting in `Color.color()` crashing. 

A solution to this should figure out how to avoid this and whether changes to the `Pixel` data structure are necessary. In any case, the solution changes should only happen in `Images.kt`.

**Comment by ross-holloway94** [comment]
Do you have steps to recreate this?

**Comment by AlmasB** [comment]
Good point, leave this with me to add a crashing sample.
