### ISSUE TITLE
Add texture outline generation

### ISSUE THREAD

**Issue by AlmasB** [AlmasB/FXGL#717]
In Texture.kt

**Comment by SwarmShepherd** [comment]
This can be returned as multiple Polygon2D and/or Polyline2D objects then?  The new 'Geometry' approach to matching polygon vertices is coming along much better than the 'Physics" approach.  Here is capture with the mesh expanding to 'discover' the contour (and eventually the exact vertices if this should work out:
![Screenshot from 2019-12-26 17-59-21](https://user-images.githubusercontent.com/1083635/71494076-ddd8a180-2809-11ea-9954-9a5303b5f3d6.png)

**Comment by SwarmShepherd** [comment]
Do I understand correctly that this would produce one or more Polyline2D and/or Polygon2D objects?  (I have spent 100's of hours doing this in various tools,  and I will say that tracing contours is as much an Art as a Science.  For example changing contrast can have an significant effect.)

**Comment by AlmasB** [comment]
This will return another `Texture`, essentially the same as original but "extruded" in 4 directions, thus creating an outline.
