### ISSUE TITLE
(fxgl11) window is not displayed as expected on linux(manjaro kde)

### ISSUE THREAD

**Issue by phph9090** [AlmasB/FXGL#737]
I started with fxgl11 gradle example. (Drop App)
No error occurred, the expected window didn't show up, but s tiny vertical line
Please check the picture below

![image](https://user-images.githubusercontent.com/9319235/72664096-dc7b4d00-3a34-11ea-930f-6d43be3fa2d4.png)

**Comment by AlmasB** [comment]
Please can you use fxgl 11.7 and if the issue repeats, post the full log
(in logs/ directory), thanks

**Comment by phph9090** [comment]
use 11.7 but no luck
[FXGL-19-Jan-2020-21.15.51.log](https://github.com/AlmasB/FXGL/files/4082712/FXGL-19-Jan-2020-21.15.51.log)

**Comment by AlmasB** [comment]
I don't see anything suspicious in the log. Do other JavaFX 12 applications work fine, i.e. open `Stage` correctly?

**Comment by phph9090** [comment]
jfx12 demo works fine
![image](https://user-images.githubusercontent.com/9319235/72733021-fef69d00-3bd1-11ea-967c-cd84a44210ee.png)

**Comment by AlmasB** [comment]
I have exposed access to the primary `Stage` (the one you would normally get in a javafx app), so you can play around with it since I don't have the linux distribution in question to test it. The API is: `FXGL.getPrimaryStage()`. You can call this in any method, apart from `initSettings()` and your application constructor (the one that `extends GameApplication`).

I suppose, for starters, you would want to check the width and the height of the `Stage`. According to the log, it should be 800x600 or so. We can go from there ...

To get the latest build, you can use this:
```
<dependencies>
    <dependency>
        <groupId>com.github.almasb</groupId>
        <artifactId>fxgl</artifactId>
        <version>dev-SNAPSHOT</version>
    </dependency>
</dependencies>

<repositories>
    <repository>
        <id>oss.sonatype.org-snapshot</id>
        <url>http://oss.sonatype.org/content/repositories/snapshots</url>
    </repository>
</repositories>
```

**Comment by phph9090** [comment]
it seems that the width and height of primary stage can't be set correctly before loop.start() in startLoop function of Engine.kt
but if make the window to be resizable, the issue disappears. 
I'm new to jfx, I can't tell the real cause under the hood.
At at least, settings.setManualResizeEnabled(true) helps, thanks a lot

**Comment by marccollin** [comment]
right

settings.setManualResizeEnabled(true);

fix the issue.

tested with opensuse tumbleweed, java 11

**Comment by AlmasB** [comment]
This issue _should_ now be fixed in `dev-SNAPSHOT`. Make sure your runtime version of javafx is `13.0.2`. The log should say: `FX:13.0.2`.

```
<dependencies>
    <dependency>
        <groupId>com.github.almasb</groupId>
        <artifactId>fxgl</artifactId>
        <version>dev-SNAPSHOT</version>
    </dependency>
</dependencies>

<repositories>
    <repository>
        <id>oss.sonatype.org-snapshot</id>
        <url>http://oss.sonatype.org/content/repositories/snapshots</url>
    </repository>
</repositories>
```

Tested with manjaro linux, kde plasma: 5.17.5, kde frameworks 5.66.0, qt 5.14.1, kernel 5.4.23-1-MANJARO

**Comment by phph9090** [comment]
now it works as expected
