### ISSUE TITLE
Add support for spawning elements from TMX textures

### ISSUE THREAD

**Issue by JosephChotard** [AlmasB/FXGL#742]
FXGL 11 doesn't seem to be able to spawn entities based on TMX maps anymore. Have tried adding "Type" property and changing "name"

**Comment by AlmasB** [comment]
`.tmx` *is* supported, but not necessarily every feature. Please can you provide a minimal example?

**Comment by JosephChotard** [comment]
If I were to create a map with a layer called "collide" it doesn't call the spawn("collide") in the entity factory. Like in your platformer tutorial. 
if this is in the GameApplication, 
```
FXGL.setLevelFromMap("level2.tmx");
FXGL.getGameWorld().addEntityFactory(new GameAppFactory());
```
it should trigger
`@Spawns("collide")
	public Entity newCollide(SpawnData data) {
	}`
this code in GameAppFactory (if I have a layer called "collide")

**Comment by AlmasB** [comment]
A layer is a collection of objects. `@Spawns("collide")` will be called by an _object_ (not layer) with type `"collide"`.  

Also, as a side note, the factory should be added before parsing the level from map.

**Comment by JosephChotard** [comment]
My mistake, I had the code in the wrong order. However, this is now giving me the following error:
`No EntityFactory has a method annotated @Spawns()`
[Here](https://ibb.co/TqT1S0L) are the properties of the object layer.

**Comment by AlmasB** [comment]
It seems you might have an object with no type, which is what the error is
saying. If so, I'll see if I can make the error message more helpful. It
would typically say no method Spawns(type), but given type is empty, I
think that's what's printed

**Comment by AlmasB** [comment]
Also, to clarify, as explained above, layer and its properties have nothing to do with the spawn method. In a layer, you can create objects and assign types. I suggest that you refer to the platformer tutorial.

**Comment by JosephChotard** [comment]
Amazing! Thank you for your help and your amazing library!

**Comment by JosephChotard** [comment]
Amazing! Thank you for your help and your amazing library!
