### ISSUE TITLE
Update Zdepth while in game

### ISSUE THREAD

**Issue by JosephChotard** [AlmasB/FXGL#750]
I have a piece of code which updates the Z-index of the entity like so: `entity.getTransformComponent().setZ(5);`. I have tested it and I'm sure that the block of code is being executed, however: the update to the Z-index is never propagated to the screen and the entity remains above (or below) the other entities.

**Comment by AlmasB** [comment]
Now fixed, thanks for letting me know, please check that it works for you:

To get the latest build, you can use this:
```
<dependencies>
    <dependency>
        <groupId>com.github.almasb</groupId>
        <artifactId>fxgl</artifactId>
        <version>dev-SNAPSHOT</version>
    </dependency>
</dependencies>

<repositories>
    <repository>
        <id>oss.sonatype.org-snapshot</id>
        <url>http://oss.sonatype.org/content/repositories/snapshots</url>
    </repository>
</repositories>
```

**Comment by JosephChotard** [comment]
That doesn't seem to have fixed it, I've changed the pom.xml file to use your snapshot. However, the scene still isn't z-sorting on z-index update... 
Here's a screenshot from my app: the z-index of both entities are set to be their Y position (I have checked and entity.getZ() returns a higher number for the blue character than for the green one so the blue one should be displayed above the green one)
[screen shot](https://imgur.com/a/MXM6Rj7)
Could it be possible that I need to change the entity's texture's z-index?

**Comment by AlmasB** [comment]
1. Can you post the latest log (from logs/) please?
2. Can you also post the code that spawns and then updates z-index? `entity.setZ()` should do it...

**Comment by JosephChotard** [comment]
Here's my log: https://pastebin.com/06ACZr11

This component is being added to components that need their depth to be updated
`public class DepthComponent extends Component {
    Random random = new Random();

    @Override
    public void onUpdate(double tpf) {
        entity.setZ((int)entity.getY());  
    }
}`

**Comment by AlmasB** [comment]
It seems you are running an old version of the snapshot: 
```
15:50:43.799 [JavaFX Application Thread] INFO  Engine               - FXGL-dev-SNAPSHOT (11.02.2020 21.08) on MAC (J:11.0.1 FX:12.0.1)
```

Try force update maven dependencies. The build should be dated today 13.02.2020

**Comment by JosephChotard** [comment]
Thank you very much!!!! It worked, sorry didn't realise cleaning the project wasn't enough.

For future reference, here's the command to force update maven projects: 
`mvn clean install -U`
