### ISSUE TITLE
The exception cause should be written to log alongside exception itself

### ISSUE THREAD

**Issue by AlmasB** [AlmasB/FXGL#761]
Currently, only the top-level exception is logged in `GameApplication`. Ideally, the entire stacktrace should be logged so the cause can be examined.

**Comment by ross-holloway94** [comment]
Are you referring to `GameApplication#handleFatalError` ?

**Comment by AlmasB** [comment]
Yes, try creating a minimal example (e.g. the one from README) and crash it by throwing a runtime exception in `initGame()`. The error reporter will pick up the entire stacktrace but the log will not contain the entire trace.

**Comment by ross-holloway94** [comment]
This is quite strange, considering that the cause is shown in the game window. My latest theory is that it's the Logger class in the SSLogger project not seeing the stack correctly, but I don't have the sources to be able to put a breakpoint in to analyse it.

**Comment by AlmasB** [comment]
sslogger is now an fxgl module (`fxgl-logging`), so breakpoints can be set if necessary
