### ISSUE TITLE
Menu fullscreen check box is barely visible

### ISSUE THREAD

**Issue by AlmasB** [AlmasB/FXGL#765]
We should probably add contrasting colors (e.g. white since the box is black) to some bits of the check box, so it is visible on dark backgrounds. Looks like all changes should happen in the css file in the `fxgl` module.

To check the result, one can run the `MenuSample` from the `fxgl-samples` module.

**Comment by ross-holloway94** [comment]
![2020-04-08 15_21_13-Untitled 0 0](https://user-images.githubusercontent.com/20950727/78795249-b36fb600-79ac-11ea-9b9b-7d98c7b13024.png)

Where is the check box supposed to be?
