### ISSUE TITLE
Error using Version 11.8

### ISSUE THREAD

**Issue by marvinbuff** [AlmasB/FXGL#770]
Pumping up the version from 11.7 to 11.8 causes a run time error for me.

When I try to run my game it compiles fine but on `:run` it returns the error:
`Error: --module-path requires module path specification`

Not sure if this is my fault but the error message is a bit too cryptic and not thrown by my code to figure it own. Appreciate any help, thanks.

**Comment by AlmasB** [comment]
JavaFX was upgraded to `13.0.2` in 11.8. Try upgrading [the dependency here](https://github.com/marvinbuff/GalacticCombat/blob/Version0.2/build.gradle.kts#L57) to 13.0.2.

**Comment by marvinbuff** [comment]
Works perfectly now. Thank you very much.
