### ISSUE TITLE
Add virtual joystick input

### ISSUE THREAD

**Issue by AlmasB** [AlmasB/FXGL#772]
Visually, it should look similar to [this](https://github.com/MarcoFazioRandom/Virtual-Joystick-Godot#godot-virtual-joystick).

First, the API design should be proposed based on what information we want to obtain from the joystick. Presumably, we want a vector from the joystick center to where the player _pointer_ (finger / cursor) is, when the joystick is being pressed. Using the vector we can obtain both the direction and length (magnitude that we can use to estimate _force_).

Edit: functionality is there apart from force, which needs to be calculated and obtained via `vector` before this is closed.

**Comment by AlmasB** [comment]
Initial API design complete, see [initial commit](https://github.com/AlmasB/FXGL/commit/c3ab02159bf3f39aa0198c0a1cbac0a6c3af8385) 

The commit includes two `TODO` placeholders, which primarily require UI design and implementation. See link in the description for visual reference (does not have to look exactly like that).

**Comment by AlmasB** [comment]
@ross-holloway94 interested? There is also a sample included in the above commit to see how the virtual joystick would work.

**Comment by ross-holloway94** [comment]
Yeah, I'll have a look this week and see if I can get my head around it

**Comment by ross-holloway94** [comment]
Okay, initial thoughts are that the `VirtualJoystick` should instead be  composed of two `Circle` objects: A background and a foreground.
Then:

- The center of the foreground circle shall not be dragged past the edge of the background circle. If those points are equal, the maximum possible magnitude is returned.
- The foreground circle shall listen for dragging events
- On release, the foreground circle shall reset its position back to the center of the background circle.

**Comment by AlmasB** [comment]
Yes, sounds good, you should be able to use the `pressedProperty()` of the `Parent` (which `VirtualJoystick` is) to see if the foreground circle should be moved to where player input (cursor or finger) is.

**Comment by ross-holloway94** [comment]
Good stuff! :)
