### ISSUE TITLE
Document implicit assumption about GameApplication.launch

### ISSUE THREAD

**Issue by keymone** [AlmasB/FXGL#773]
The caller of GameApplication.launch must be a method in the same class that extends GameApplication. This is due to how ReflectionUtil looks up the stacktrace. Lost a bunch of hours chasing red herrings when trying to reproduce basic game example using clojure and calling App.launch directly from clojure code.

**Comment by AlmasB** [comment]
Thanks for this. I'll see if I can find a suitable place to document this.

**Comment by AlmasB** [comment]
This issue is merged into #677 regarding general documentation overhaul.
