### ISSUE TITLE
Allow input to handle a sequence of triggers, e.g. cheat codes / combos

### ISSUE THREAD

**Issue by AlmasB** [AlmasB/FXGL#774]
This should have API that is consistent with what we have now (e.g. [InputSample](https://github.com/AlmasB/FXGL/blob/master/fxgl-samples/src/main/java/basics/InputSample.java) )

What we have now:

```
getInput().addAction(user action, KeyCode.F);
getInput().addAction(user action, MouseButton.PRIMARY);
```

The new API related to this issue should be of the form:

```
getInput().addAction(user action, combo);
getInput().addAction(user action, cheat code);
```

To address this issue, a solution should first propose the API design, which should be consistent with existing API as above. Next, implementation details should be discussed. For example, where are we storing the input sequence and how long should the sequence be?

**Comment by AlmasB** [comment]
Proposed call site API:

```
InputSequence seq = new InputSequence(KeyCode.F, KeyCode.A, KeyCode.H, ...);
getInput().addAction(user action, seq);
```

Behaviour:

A user action object has three callbacks: `onBegin`, `on`, `onEnd`. These are well-defined for single key triggers. For `InputSequence`, I think it could be: when the entire sequence is correctly provided, then in that frame, it is `onBegin`. Starting from next frame while the last key in the sequence is held, that's `on`. Finally, when the key is released, that's `onEnd`.

@marvinbuff @ross-holloway94 would be good to hear your thoughts on all this.

**Comment by ross-holloway94** [comment]
That seems reasonable. I think the difficult part will be the `InputSequence` implementation. Somehow, it will need to be monitoring input events to see if the sequence is matched. If a different input is detected then it'll need to reset.

**Comment by AlmasB** [comment]
Done in 11.9
