### ISSUE TITLE
FXGL game app in child window

### ISSUE THREAD

**Issue by lifeinwild** [AlmasB/FXGL#780]
is this possible? 

parent window: javafx normal gui app
child window: fxgl game app

game app is launched from normal gui app.

any sample code?

im using fxgl 0.5.4

**Comment by AlmasB** [comment]
In 0.5.4 I don't think it is possible, but in 11.8 it is. You just need a `stage` object. [Sample code](https://github.com/AlmasB/FXGL/blob/master/fxgl-samples/src/main/java/sandbox/CustomApp.java)

**Comment by lifeinwild** [comment]
Can you rethink about java8?

2019 83%
https://www.jetbrains.com/lp/devecosystem-2019/java/
2018 84%
https://www.jetbrains.com/research/devecosystem-2018/java/

At this pace it will take another 83 years for java8 to stop being used.

**Comment by AlmasB** [comment]
I would love to support java 8. However, as it currently stands the architectures of fxgl for java 8 and fxgl for java 11+ are not compatible. There is significant effort and time required to backport the whole codebase to java 8. If you are interested, you are very welcome to provide such a port.

**Comment by lifeinwild** [comment]
Thank you for your response. I understand the situation.
