### ISSUE TITLE
ProgressBar customization

### ISSUE THREAD

**Issue by WojciechSerafin** [AlmasB/FXGL#785]
As we talk on Gitter that will be great if we can override ProgressBar with custom version to make it fit better to the game. If that’s not possible can you at least let developer access functions of ProgressBar’s rectangles options like corner arcs?

**Comment by ross-holloway94** [comment]
@AlmasB Perhaps we could make `backgroundBar` and `innerBar` final to prevent them from being declared as a new object, but allow access to them?

**Comment by AlmasB** [comment]
Adding two public accessor methods `getBackgroundBar()` and `getInnerBar()` seems like sufficient, at least in the meantime?

**Comment by WojciechSerafin** [comment]
I’m sorry for late respond. Thats great news. It’s perfect solution for me
right now.

W dniu sob., 11.04.2020 o 14:17 Almas Baimagambetov <
notifications@github.com> napisał(a):

**Comment by AlmasB** [comment]
@WojciechSerafin these methods are now available. 

To get the latest build (after CI has published them, which should be done in a few mins), you can use this:
```
<dependencies>
    <dependency>
        <groupId>com.github.almasb</groupId>
        <artifactId>fxgl</artifactId>
        <version>dev-SNAPSHOT</version>
    </dependency>
</dependencies>

<repositories>
    <repository>
        <id>oss.sonatype.org-snapshot</id>
        <url>http://oss.sonatype.org/content/repositories/snapshots</url>
    </repository>
</repositories>
```

**Comment by ross-holloway94** [comment]
Is this issue now ready to be closed?

**Comment by AlmasB** [comment]
I believe so.
