### ISSUE TITLE
Fix trigger sequence mini game

### ISSUE THREAD

**Issue by AlmasB** [AlmasB/FXGL#796]
File: https://github.com/AlmasB/FXGL/blob/dev/fxgl-gameplay/src/main/kotlin/com/almasb/fxgl/minigames/triggersequence/TriggerSequenceMiniGame.kt

At L96, 

https://github.com/AlmasB/FXGL/blob/43a1a24ac82b03ed733734c2c35ececb0bf5c4e2/fxgl-gameplay/src/main/kotlin/com/almasb/fxgl/minigames/triggersequence/TriggerSequenceMiniGame.kt#L96

there should be an extra check for "*and the view is between line1 and line2*"

**Comment by BeckFW** [comment]
@AlmasB Discussed and fixed. Please assign to
@artemijsem @dalehuntgb @beckfw

**Comment by AlmasB** [comment]
Great, looking forward to the PR 😄
