### ISSUE TITLE
Fix WobbleEffect

### ISSUE THREAD

**Issue by AlmasB** [AlmasB/FXGL#797]
File: WobbleEffect.kt

The logic in `init{ }` needs to be double checked. It is likely there is a rounding error in there. We should also take the last "quad" which may be smaller than chunk size

**Comment by AahzBrut** [comment]
I think the problem is here:
`val chunkSize = chunkSizeDouble.toInt().toDouble()`
all transaltions and dimensions are in `Double`, why chunkSize is rounded down to `Int` before slicing up the texture?

**Comment by AlmasB** [comment]
Yes, I think you are right. I don't remember why this was done, feel free to tweak as needed. There is an existing sample `WobbleEffectSample.java` in `sandbox.view` in `fxgl-samples that you can run to check the results.
