### ISSUE TITLE
Cannot close the application via TestFX

### ISSUE THREAD

**Issue by stefankablowski** [AlmasB/FXGL#805]
Hello, i am trying to use FXGL with TestFx and I can not find a way _to close the application via TestFx_. I am starting the application via customLaunch, but when running multiple tests one after another i get a logger error. We already tried triggering ALT+F4, but this also throws an error.

## My code
```java
@Override
    public void start (Stage stage) throws Exception {
        GameApplication.customLaunch(app, stage);
        TimeUnit.MILLISECONDS.sleep(200);
    }
```

## Errors:
```
java.lang.IllegalStateException: Logger already configured
    at com.almasb.sslogger.Logger$Companion.configure(Logger.kt:29)
    at com.almasb.sslogger.Logger.configure(Logger.kt)
```

Can you mention a quick fix for this? I am not so experienced so there might be a workaround for this.

Kind regards

**Comment by AlmasB** [comment]
Hi, I'm afraid there is no quick for this as FXGL is not meant to be multi-instance. I will not go into detail, but by design, only a single FXGL instance per JVM will function correctly.

If you do need to test with FXGL, the only viable approach I can think of is to start an FXGL application, do all tests, then close the FXGL application.

**Comment by stefankablowski** [comment]
Thanks so much for the fast reply!
I am not aiming to run the tests concurrently. Am I understanding it right that the following process is not possible: Start FXGL Game via Test framework -> Run Test -> Close FXGL Game after test -> Run New instance of FXGL -> Run next test.

TestFX is starting a new application for every test so this will obviously not work. My hope was that if I could properly shut down the FXGL Game (maybe with some other testing library or a method via the custom stage) I could somehow achieve the wanted behaviour.

**Comment by stefankablowski** [comment]
I found a solution which works for now.
When using testfx you can make an extra class for every test.
Then in build.gradle add:
```java
test {
forkEvery = 1
}
```
Doing so will prevent testfx from starting multiple FXGL instances.

**Comment by AlmasB** [comment]
Ah nice, I haven't used TestFX before, seems like a cool framework for testing javafx related stuff.
