### ISSUE TITLE
Add a util dsl that runs a function and provides execution time

### ISSUE THREAD

**Issue by AlmasB** [AlmasB/FXGL#809]
```
val timeTook: Long = runMeasuring {
    // code
}
```

**Comment by wakingrufus** [comment]
kotlin standard library has some built-in functions for this: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.time/measure-time.html
and https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.time/measure-timed-value.html

**Comment by AlmasB** [comment]
Nice, will check it out
