### ISSUE TITLE
Update built-in components with isComponentInjectionRequired()

### ISSUE THREAD

**Issue by AlmasB** [AlmasB/FXGL#824]
We now have `boolean isComponentInjectionRequired()` that can be overridden by subclasses of Component. There are many built-in components that FXGL provides. Ideally all of them should be tweaked so no injection is required and returning false for the above method to speed up component addition.

See [this commit](https://github.com/AlmasB/FXGL/commit/b4909b5ab119f2d569aa97968ef1d7a8a9f8f689) for some examples. Some components already do not require injection can override the above method immediately.

**Comment by AahzBrut** [comment]
How one can distinguish components that are require injection from those that are not?

**Comment by AlmasB** [comment]
Suppose we have the following:

```
class XXXXComponent {
    lateinit var yyyy: YYYYComponent
    lateinit var zzzz: ZZZZComponent

    override fun onAdded() {
        yyyy = entity.getComponent(YYYYComponent::class.java)
        zzzz = entity.getComponent(ZZZZComponent::class.java)
    }
}
```

By default, `isComponentInjectionRequired()` returns true so the above `onAdded()` is not needed as `yyyy` and `zzzz` are injected. However, to speed up component addition, we can override `isComponentInjectionRequired()` to return false and add the above `onAdded()` to manually initialize `yyyy` and `zzzz`.

So, to address this issue:
1. In cases where there are no fields of type (or subtype) `Component`, we can safely override `isComponentInjectionRequired()` with false. 
2. In cases, where component injection is needed, we should use `onAdded()` to initialize the components, as in the example above, and then override `isComponentInjectionRequired()` with false.

The above should be done for all built-in components. One approach is to find all usages (ALT + F7? in IntelliJ) of `Component` and identify its subclasses.
