### ISSUE TITLE
Method Input.isHeld() missing?

### ISSUE THREAD

**Issue by dykstrom** [AlmasB/FXGL#835]
On the wiki, on page "Input (FXGL 11)", section "Querying Keyboard/Mouse State", there is example code that suggests that you can call a method Input.isHeld() to find out if a specific key is being pressed at the moment. However, I cannot find such a method in class Input. I gather this is not the recommended way to check input, so maybe it has been removed in a recent release? In that case, the wiki should be updated as well. Otherwise, I guess the method should be added (again?) to class Input. Or is there now another way to accomplish the same functionality?

**Comment by AlmasB** [comment]
Well spotted! Have now updated [the relevant section](https://github.com/AlmasB/FXGL/wiki/Input-(FXGL-11)#using-trigger-listener). You are correct, this legacy method was superseded by a more general trigger listener.
