### ISSUE TITLE
Allow asset loading from a given URL

### ISSUE THREAD

**Issue by AlmasB** [AlmasB/FXGL#860]
`loadXXXX(url: URL)` to allow for a range of use cases, e.g. dialogue editor runtime environment, or to hot-swap assets in development

**Comment by softknk** [comment]
I could do that, but in which class should I write this method to load assets from URL?

**Comment by AlmasB** [comment]
Hi, thanks for your interest! This is currently under design (both API and use case) and assigned to me. If you would like to contribute, please consider issues with `help-wanted` label.
