### ISSUE TITLE
Improve performance of Texture::subTexture and superTexture

### ISSUE THREAD

**Issue by AlmasB** [AlmasB/FXGL#871]
Current implementation copies pixels one by one. This can be improved by bulk copying them by using one of the provided methods in PixelWriter

**Comment by AlmasB** [comment]
@AahzBrut please check when you get a chance

To get the latest build (once finished building), you can use this:
```
<dependencies>
    <dependency>
        <groupId>com.github.almasb</groupId>
        <artifactId>fxgl</artifactId>
        <version>dev-SNAPSHOT</version>
    </dependency>
</dependencies>

<repositories>
    <repository>
        <id>oss.sonatype.org-snapshot</id>
        <url>http://oss.sonatype.org/content/repositories/snapshots</url>
    </repository>
</repositories>
```

**Comment by AahzBrut** [comment]
@AlmasB , ok, I'll try, now i have 150+ images in one animation and it's really long wait :)
Now converting them to one image and also will check this out.

**Comment by AahzBrut** [comment]
Just awesome, instead of 3 minutes its now took only 5.5 seconds to init game.

Thanks a lot!

**Comment by AlmasB** [comment]
@AahzBrut I assume you use `Images::merge()` to combine the images. If so, please can you also try this new build (once CI is done). It avoids duplicate copying, so should be faster. I can see some minor difference with 8 images, but with 150+ the difference should be considerable.

**Comment by AahzBrut** [comment]
@AlmasB I am usinig `AnimationChannel(images: List<Image>)` but inside constructor there is call to `merge(images)` 
I'll test the new version as soon as it will be available in dev-SNAPSHOT

**Comment by AahzBrut** [comment]
@AlmasB yeah, it works, init time went down from 5.5 sec to 1.9 sec

Great! Thanks!
