### ISSUE TITLE
Packaging Project

### ISSUE THREAD

**Issue by computerfr33k** [AlmasB/FXGL#88]
How would I go about packaging a project that depends on FXGL and assets. Currently I am using maven for my project and have it add the FXGL lib to a folder in a classpath. So, my application loads correctly, but cannot find any of the assets even though they are contained in the jar as ./assets

For some reason FXGL isn't finding them and I was wondering what I would have to do for it to find them when packaging.

**Comment by AlmasB** [comment]
When packaging try to build an uber-jar using shade-plugin. So far I have only tested with FXGL being packaged into the same jar as the game app. It is possible that when loaded as a library it may have different resource path configuration.
P.S. If you are unsure how to use shade-plugin, have a look at this pom.xml https://github.com/AlmasB/NinjaCardCombat/blob/master/pom.xml where it says maven-shade-plugin

**Comment by computerfr33k** [comment]
That seems to have done the trick, it is now working. The one thing I suspect that is causing problems is that it sets the classpath to the actual FXGL jar and so then it tries to load from there or something. Where as the shade plugin puts everything in the same classpath because everything is loaded from the jar root. (Only my guess though)
