### ISSUE TITLE
Design and implement MultiplayerService

### ISSUE THREAD

**Issue by AlmasB** [AlmasB/FXGL#883]
**Please discuss the feature ideas on [Gitter](https://gitter.im/AlmasB/FXGL) first. Then please describe the feature**
The service sits on top of NetService and provides gameplay specific features, such as entity replication and chat.

**Comment by smabitsela** [comment]
Please discuss the feature ideas on Gitter first. Then please describe the feature
To be able to implement Input & Entity Replication on a setup consisting of a remote server hosting multiple FXGL clients in teams.

Describe alternatives you've considered (optional)
A clear and concise description of any alternative solutions or features you've considered.

Additional context (optional)
At our training institute "https://www.wethinkcode.co.za/" we are required to create a multi-team (two teams, four players each) strategy game hosted on a remote server with eight clients connected. Each client choosing a team. Our request is to have the MultiplayerService be able to implement and Replicated such a setup on the screens of each player.

**Comment by AlmasB** [comment]
Fundamental features implemented in 11.17, see linked Sample for how to use replication features.
