### ISSUE TITLE
Pressing a mouse button 4 or 5 crashes the game.

### ISSUE THREAD

**Issue by jacekpoz** [AlmasB/FXGL#891]
**Describe the bug**
When I press mouse button 4 or 5 with my mouse on the game window, it throws a `RuntimeException` saying it's not a mouse button. It's really annoying, I use mouse button 5 for talking on discord.

**To Reproduce**
1. Make a working window in FXGL
2. Press mouse button 4 or 5 with your mouse inside of the window
3. Rest your eyes on the stack trace

**Expected behavior**
Game should crash and throw an exception when pressing mouse button 4 or 5.

**Screenshots**
![obraz](https://user-images.githubusercontent.com/64381190/98100032-993d7e00-1e90-11eb-9117-1c833a1c7884.png)

**Runtime info(please complete the following information):**
 - OS and version: Windows 10

**Attach log associated with the bug (can be found in "logs/")**
[FXGL-04-lis-2020-11.18.32.log](https://github.com/AlmasB/FXGL/files/5487136/FXGL-04-lis-2020-11.18.32.log)

**Additional context / possible fixes**
I think this is enough context, I don't know how to fix it.

**Comment by AlmasB** [comment]
Many thanks, this should be easy to fix. Will have a look later today

**Comment by AlmasB** [comment]
Give CI 10-15 mins to build then can you please try the latest build and report back if the issue was solved?

To get the latest build, you can use this:
```
<dependencies>
    <dependency>
        <groupId>com.github.almasb</groupId>
        <artifactId>fxgl</artifactId>
        <version>dev-SNAPSHOT</version>
    </dependency>
</dependencies>

<repositories>
    <repository>
        <id>oss.sonatype.org-snapshot</id>
        <url>http://oss.sonatype.org/content/repositories/snapshots</url>
    </repository>
</repositories>
```

**Comment by jacekpoz** [comment]
It works now, thanks a lot for the quick response.
