### ISSUE TITLE
Provide a list of all engine services

### ISSUE THREAD

**Issue by AlmasB** [AlmasB/FXGL#896]
So the devs know which ones to provide implementation for if needed. Each service should be added to this issue, so that it can later be added to the wiki. Each service needs a brief explanation regarding what the service does.

Copy-pasted from Settings.kt: (probably not up to date)

```
        var engineServices: MutableList<Class<out EngineService>> = arrayListOf(
                // this is the order in which services will be initialized
                // by design, the order of services should not matter
                FXGLApplication.GameApplicationService::class.java,
                FXGLDialogService::class.java,
                IOTaskExecutorService::class.java,
                EventBusService::class.java,
                FileSystemService::class.java,
                LocalizationService::class.java,
                FXGLAssetLoaderService::class.java,
                SystemBundleService::class.java,
                SaveLoadService::class.java,
                FXGLUIFactoryServiceProvider::class.java,
                FXGLDialogFactoryServiceProvider::class.java,
                AudioPlayer::class.java,
                NotificationServiceProvider::class.java,
                AchievementService::class.java,
                CutsceneService::class.java,
                MiniGameService::class.java,
                NetService::class.java,
                UpdaterService::class.java,
                DevService::class.java
        ),
```

In addition to above, any subtype of `EngineService` should also be added here.

**Comment by jo372** [comment]
**FXGLAssetLoaderService**
Handles all resource (asset) loading operations.
- The "assets" directory must be located in "src/main/resources/" (using the Maven directory structure).  
Alternatively, (not recommended) source folder ("src" by default).  
- Resources (assets) will be searched for in these specified directories:  

Texture / images - /assets/textures/  
Sound - /assets/sounds/  
Music - /assets/music/  
Text (List of String) - /assets/text/  
FXML - /assets/ui/  
CSS - /assets/ui/css/  
Font - /assets/ui/fonts/  
Cursors - /assets/ui/cursors/  
Resource bundles - /assets/properties/    
-  If you need to access the "raw" JavaFX objects (e.g. Image), you can use \[getStream\]  
 - to obtain an InputStream and then parse into whatever resource you need.
</br>

**FXGLApplication.GameApplicationService**
___
Is a high level [blank]
</br>

**FXGLDialogService**
___
A Dialog Service allows you to display text to the screen.

**IOTaskExecutorService**
___
The IOTaskExecutorService allows you run tasks synchronously and asyncronously.
</br>

**FileSystemService**
___
The File System Service is a standard IO Wrapper that allows you to read, write and check the existence of directories and files.

**Comment by jo372** [comment]
**LocalizationService**
___

Services that provides functions to localize Strings to the given Language using String or StringBinding.  
Also supports lazy loading of language data.

**SystemBundleService**
___
It saves FXGL system data into a file. 


**SaveLoadService**
___
Responsible for save/load operations to/from data files.  
Also responsible for write/read IO operations of save files.

**FXGLUIFactoryServiceProvider**
___
FXGL provider of UI factory service.


**FXGLDialogFactoryServiceProvider**
___
Generates User Interface for Dialog Boxes


**AudioPlayer**
___
General audio player service that supports playback of sound and music objects.  It can also control volume of both.

**NotificationServiceProvider**
___
Shows Notifications to the Player


**AchievementService**
___
Responsible for registering and updating achievements.  
Achievements can only be registered via Settings, before the engine starts.  

**CutsceneService**
___
Manages and plays cutscenes

**MiniGameService**
___
Manages and plays minigames

**NetService**
___
All operations that can be performed via networking.


**UpdaterService**
___
 Checks if there is a newer version of FXGL than the one being used.
 
**DevService**
___
Provides developer options when the application is in DEVELOPER or DEBUG modes.  
In RELEASE mode all public functions are NO-OP and return immediately.

**Comment by AlmasB** [comment]
Pushed to https://github.com/AlmasB/FXGL/wiki/Engine-Services-(FXGL-11)
