### ISSUE TITLE
Add support for setting default language

### ISSUE THREAD

**Issue by amatzen** [AlmasB/FXGL#898]
**Please discuss the feature ideas on [Gitter](https://gitter.im/AlmasB/FXGL) first. Then please describe the feature**
Currently, you can add supported languages and customize the locales through properties files. However, you can't select a default language. This feature request is about adding this extra functionality.

**Describe alternatives you've considered (optional)**
Currently, I have used ```getSettings().getLanguage().set(Language.DANISH);``` in initGame, which means the language will first be set, when the game is run.

**Comment by AlmasB** [comment]
It should now be possible: `settings.setDefaultLanguage( ... )`. 

To get the latest build, you can use this:
```
<dependencies>
    <dependency>
        <groupId>com.github.almasb</groupId>
        <artifactId>fxgl</artifactId>
        <version>dev-SNAPSHOT</version>
    </dependency>
</dependencies>

<repositories>
    <repository>
        <id>oss.sonatype.org-snapshot</id>
        <url>http://oss.sonatype.org/content/repositories/snapshots</url>
    </repository>
</repositories>
```
