### ISSUE TITLE
Improve Tiled map loading performance

### ISSUE THREAD

**Issue by AlmasB** [AlmasB/FXGL#900]
- [ ] ~~The tile generation could potentially be parallelized.~~ parallel tile loading didn't yield significant improvements in performance.
- [x] Remove debug logs that begin `log.debug("Writing to buffer: ....`

**Comment by AlmasB** [comment]
@adambocco apart from above (parallelizing tile generation -- I still need to investigate this), any thoughts on how we can improve loading performance of .tmx?

**Comment by adambocco** [comment]
@AlmasB 
I spent some time looking at this. It seems like when a call is made to `setLevelFromMap('mapName.tmx')` there can be a couple seconds of load time on larger maps. I did some tests with a 500x500 tiled map of 16x16 tile sizes (tile layer entities) and I found that there is quite a slowdown in `TilesetLoader.kt::loadView(layerName: String)` here:
https://github.com/AlmasB/FXGL/blob/74c9c8cf4609c510b366456a4fc9caec80067019/fxgl-entity/src/main/kotlin/com/almasb/fxgl/entity/level/tiled/TilesetLoader.kt#L158-L163

Commenting out the line calling `log.debug(..)` gave me a big increase in performance in this specific case:

- Parse Time: 0.1913669
- TilesetLoader Init Time: 0.0024212
- Load View (for loop): 0.2882948
- Pixel Writer Time (consider overhead of 'measureNanoTime'): 0.1251819
- Load Image Time (consider overhead of 'measureNanoTime'): 0.0387208
- Conditional Time (consider overhead of 'measureNanoTime'): 0.0663441
- Initial Time (consider overhead of 'measureNanoTime'): 0.0374719
- **Log Flip Time (consider overhead of 'measureNanoTime'): 0.0080994**
- LoadView Time: 0.483584
-    Create Tile Layer Entities Time: 0.4860122
-    Create Object Layer Entities Time: 0.0425438
- **<------ setLevelFromMap timed ------>**
- **Engine Time: 0.7000000000000005**


Compared to:


- Parse Time: 0.2222178
- TilesetLoader Init Time: 0.0642288
- Load View (for loop): 1.933842
- Pixel Writer Time (consider overhead of 'measureNanoTime'): 0.2197043
- Load Image Time (consider overhead of 'measureNanoTime'): 0.0701937
- Conditional Time (consider overhead of 'measureNanoTime'): 0.1095921
- Initial Time (consider overhead of 'measureNanoTime'): 0.0730058
- **Log Flip Time (consider overhead of 'measureNanoTime'): 1.4642862**
- LoadView Time: 2.1110487
-    Create Tile Layer Entities Time: 2.1136285
-    Create Object Layer Entities Time: 0.0250793
- **<------ setLevelFromMap timed ------>**
- **Engine Time: 3.077777777777782**


Log flip time refers to this section of TilesetLoader:
https://github.com/AlmasB/FXGL/blob/74c9c8cf4609c510b366456a4fc9caec80067019/fxgl-entity/src/main/kotlin/com/almasb/fxgl/entity/level/tiled/TilesetLoader.kt#L161-L174

I also tried improving parsing but the method FXGL uses for parsing the CSV at least is quite fast. There are some aspects of this I haven't explored yet but let me know if I'm on the right track. I intend to run some other tests with many object layer entities, rotated tiles, and other non-CSV encodings.

Thanks!

**Comment by AlmasB** [comment]
This investigation is very helpful, thanks. Can you provide your "test" maps please -- you can add them under `sandbox/` in fxgl-samples alongside the `Sample` application to run. We should probably add a `tiled` package to `sandbox`.

Once you have PR'ed your benchmark maps, I'll add a few large maps too and we can go from there.

**Comment by AlmasB** [comment]
I've run own benchmarks and confirmed the `log.debug` being an issue -- now removed.

![Screenshot 2021-04-16 10 40 27](https://user-images.githubusercontent.com/3594742/115006043-52709d00-9ea0-11eb-8f53-e85c4dacaef7.png)

Further checks seem to reveal these two methods above ( `loadImage()` and `WritableImage()` ) being the main bottlenecks. I'll see what we can do about these

**Comment by AlmasB** [comment]
I've tried generating the buffer (WritableImage) in a background thread, while loading the tileset image on the thread that called loadView. There's some speed gain but not much, at least doesn't justify the complexity of the asynchronous code.

`WritableImage.<init>` implementation is essentially:

```
    @Override
    public PlatformImage createPlatformImage(int w, int h) {
        ByteBuffer bytebuf = ByteBuffer.allocate(w * h * 4);
        return com.sun.prism.Image.fromByteBgraPreData(bytebuf, w, h);
    }
```

The second line is just a constructor call, so the issue seems to be with `ByteBuffer.allocate(w * h * 4)` when `w` and `h` are sufficiently large, which is the case for the benchmark sample I've used.

I don't see yet how this can be improved.

Edit: I wonder if we can use a different type of buffer, thus avoiding these allocations altogether...

**Comment by AlmasB** [comment]
I am not sure we can easily improve single-layer loading speed. However, it should be possible to load layers in parallel. Do you want to explore that path?

The main thing to consider here is parallel access to any resource (class) by `forEach(layer -> load layer)`.

**Comment by adambocco** [comment]
@AlmasB 
I got a chance to look into this today and had good results using `Async.startAsyncFX` where we loop through the map layers in `createTileLayerEntities` here:

https://github.com/AlmasB/FXGL/blob/ae7889d717f8a94f5d3fcb037618fc1f5c93e171/fxgl-entity/src/main/kotlin/com/almasb/fxgl/entity/level/tiled/TMXLevelLoader.kt#L80-L85

Here are some of my averages on loading some maps:
 
*Parallelized:*
- 1 layer (500x500): **0.054**
- 5 tile layers (500x500) : **0.60**
- 10 tile layers (500x500): **1.19**
- 50 tile layers (100x100): **0.22**

*Not Parallelized*:
- 1 layer (500x500): **0.130**
- 5 tile layers (500x500) : **1.18**
- 10 tile layers (500x500): **2.10**
- 50 tile layers (100x100): **0.43**

**Comment by AlmasB** [comment]
@adambocco Thanks, I've finally had a chance to have a think about implications and how to manage them. There is now a `isParallel` setting for the loader. To avoid concurrency issues, each layer gets its own TilesetLoader.
