### ISSUE TITLE
Add support for pause the engine and hide the window

### ISSUE THREAD

**Issue by lucas-jay** [AlmasB/FXGL#909]
I have created a user client class using swing and a GameApp class using FXGL. When player finish the game, it'll close the window by 

**FXGL.getGameController().exit();**

But when I start an another new game at my user client I get this error:

**Java FX: application Launch Must not be called more than once**

How could I solve this problem?

**Comment by AlmasB** [comment]
Hi. JavaFX (and by extension FXGL) cannot be run more than once in a JVM. This is not something we can change, as it is so by design.

Workaround: commonly, this is solved by keeping FXGL running. Once your game finishes, remove all entities, pause the engine and hide the window. When you need a new game, add new entities and restart the game.

**Comment by lucas-jay** [comment]
Thanks for your reply !
But I'm still little confused about how to “ pause the engine and hide the window ”

**Comment by lucas-jay** [comment]
When we need to start a game more than once, we may need to remove all entities, pause the engine and hide the window. However, "pause the engine and hide the window" are not part of public API. It will be nice to add these two to public API.

**Comment by AlmasB** [comment]
Thanks, I'll take a look at this later today. Once added, you can use those immediately with:

To get the latest build, you can use this:
```
<dependencies>
    <dependency>
        <groupId>com.github.almasb</groupId>
        <artifactId>fxgl</artifactId>
        <version>dev-SNAPSHOT</version>
    </dependency>
</dependencies>

<repositories>
    <repository>
        <id>oss.sonatype.org-snapshot</id>
        <url>http://oss.sonatype.org/content/repositories/snapshots</url>
    </repository>
</repositories>
```

**Comment by AlmasB** [comment]
To pause / resume engine:

```
FXGL.getGameController().pauseEngine();
```

Access to native javafx primary Stage (window), e.g. to hide it:

```
FXGL.getPrimaryStage().hide();
```

With hide(), javafx will probably shut down as it's the only window, so to prevent, you want: `Platform.setImplicitExit(false);`

Play around with these and let me know if you managed to work around the issue.

**Comment by lucas-jay** [comment]
thanks a lot , I will try it today later: )



---Original---

**Comment by lucas-jay** [comment]
It can work now. Thanks a lot.

**Comment by AlmasB** [comment]
Contributed by @lucas-jay :

when the game finishes:
```
{
   ArrayList<Entity> es = FXGL.getGameWorld().getEntities();
   Iterator<Entity> iter = es.iterator();
   if (es.size() > 0) {
       while(iter.hasNext()) {
                Entity e = iter.next();
                iter.remove();
                e.removeFromWorld();
       }
   }
   Platform.setImplicitExit(false);
   FXGL.getGameController().pauseEngine();
   FXGL.getPrimaryStage().hide();
}
```
to restart the game:
```
{
   //add  entities here
   FXGL.getGameController().resumeEngine();
   Platform.runLater(new Runnable() {
            @Override
            public void run() {
                System.out.println("show the stage");
                FXGL.getPrimaryStage().show();
            }
    });
}
```
