### ISSUE TITLE
NetService::Download file

### ISSUE THREAD

**Issue by AlmasB** [AlmasB/FXGL#912]
**Please discuss the feature ideas on [Gitter](https://gitter.im/AlmasB/FXGL) first. Then please describe the feature**
Provide API to download a file over the network given a URL. The DownloadInfo progress callback should be allowed to be passed in.

**Comment by AlmasB** [comment]
@adambocco might be of interest?

**Comment by AlmasB** [comment]
Notes and draft API

```
IOTask<Path> downloadFileTask(String url);
IOTask<Path> downloadFileTask(String url, DownloadInfo info);

IOTask<Path> downloadFileTask(URL url);
IOTask<Path> downloadFileTask(URL url, DownloadInfo info);

class DownloadInfo {
    fun progressProperty(): ReadOnlyDoubleProperty
    // some internal way of updating progress property during download
}
```

Not sure of the best way to give download size back to user. Might be possible to just add a new function:

```
// return number of bytes or -1 if something failed
netService.getDownloadSize(URL url / String url): Long
```

OR wrap with an IOTask<> too. Need to weigh up advantages / disadvantages. Either way, the user needs to know that this is a slow operation, not to be done in UI thread.

For URL stream to Path, the copy operation should be done in a similar way to how JDK `Files` implements it.

**Comment by AlmasB** [comment]
@adambocco let me know if you are interested. If not, I'll give this a go over the weekend.

**Comment by adambocco** [comment]
@AlmasB sorry midterms are sucking a lot of my time.

I spent a lot of time looking at this and a lot of it was new to me. I think you should probably handle this.

Thanks!

**Comment by AlmasB** [comment]
No problem, good luck with the midterms!
