### ISSUE TITLE
Crash when rebinding keys to "space", "tab", or "enter" keys

### ISSUE THREAD

**Issue by sedezee** [AlmasB/FXGL#917]
**Describe the bug**
When rebinding keys from the game menu, the program crashes upon attempt to rebind to space, tab, or enter keys. Sometimes it simply refuses to rebind, other times it shuts down the game entirely.

**To Reproduce**
1. Launch the game (Mario is an example of where this bug occurs)
2. Hit the menu key once into the initial gameplay
3. Go to 'controls' and attempt to rebind any of the controls to space, tab, or enter

**Expected behavior**
The key should rebind as expected, setting the space, tab, or enter key to the desired action. 

**Screenshots**
![image](https://user-images.githubusercontent.com/32148160/102273460-5ab7cc00-3ef0-11eb-84b0-8d8cd9a3f1df.png)

**Runtime info(please complete the following information):**
 Windows 10

**Attach log associated with the bug (can be found in "logs/")**
Log unavailable, please refer to screenshot above

**Additional context / possible fixes**
We had a brief conversation about the issue in your gitter. You stated "My guess is that one of the actions is being "focused", so when the user presses "space", it actually triggers another "Press any key" subscene to be added to the scene graph, which in turn causes the error from your screenshot: Duplicate children."

**Comment by AlmasB** [comment]
The above fixes space and other keys, however I discovered that the error in the screenshot is due to a mouse event handler on each trigger. So the following bug remains:

- FXGL clicking again on action/trigger in menu while "press any key" is open causes crash due to subscene being added twice - therefore duplicate children

I'll have a look at this some time tomorrow, but once CI completes its build, you should be able to use this fixed version.
To get the latest build, you can use this:
```
<dependencies>
    <dependency>
        <groupId>com.github.almasb</groupId>
        <artifactId>fxgl</artifactId>
        <version>dev-SNAPSHOT</version>
    </dependency>
</dependencies>

<repositories>
    <repository>
        <id>oss.sonatype.org-snapshot</id>
        <url>http://oss.sonatype.org/content/repositories/snapshots</url>
    </repository>
</repositories>
```

**Comment by sedezee** [comment]
Is there a gradle version of this available or will I have to wait for the next version of FXGL?

**Comment by AlmasB** [comment]
Just use the same coordinates: `dev-SNAPSHOT` as version and `http://oss.sonatype.org/content/repositories/snapshots` as a dependency repo. If you haven't done this before, have a look at gradle's website.

**Comment by AlmasB** [comment]
The identified bugs in this issue should have been fixed now, please test when you get a chance.

**Comment by sedezee** [comment]
Everything appears to be working correctly; thank you for fixing it so quickly!
