### ISSUE TITLE
TransformComponent update direction3D on rotation change

### ISSUE THREAD

**Issue by AlmasB** [AlmasB/FXGL#924]
When rotation Y or X change, we also need to update direction3D. Possibly, through a listener or just before the value of direction3D is queried. Otherwise it creates a bug that moves the component in the wrong direction.

It would be beneficial to have a direct setter for direction3D, perhaps direction3DProperty() too.

**Comment by Snoopy137** [comment]
Hi @AlmasB any chance this fix will be applied to java library?
