### ISSUE TITLE
Resolve code duplication in AnimatedValue.kt

### ISSUE THREAD

**Issue by AlmasB** [AlmasB/FXGL#925]
The two classes below are duplicated for 3D. See if we can fix duplication. Maybe keep all 4 classes, but 2D calls 3D code with z = 0?

```
class AnimatedQuadBezierPoint2D
(val path: QuadCurve) : AnimatedValue<Point2D>(Point2D.ZERO, Point2D.ZERO) {

    override fun animate(val1: Point2D, val2: Point2D, progress: Double, interpolator: Interpolator): Point2D {
        return FXGLMath.bezier(
                Point2D(path.startX, path.startY),
                Point2D(path.controlX, path.controlY),
                Point2D(path.endX, path.endY),
                interpolator.interpolate(0.0, 1.0, progress)
        )
    }
}

class AnimatedCubicBezierPoint2D
(val path: CubicCurve) : AnimatedValue<Point2D>(Point2D.ZERO, Point2D.ZERO) {

    override fun animate(val1: Point2D, val2: Point2D, progress: Double, interpolator: Interpolator): Point2D {
        return FXGLMath.bezier(
                Point2D(path.startX, path.startY),
                Point2D(path.controlX1, path.controlY1),
                Point2D(path.controlX2, path.controlY2),
                Point2D(path.endX, path.endY),
                interpolator.interpolate(0.0, 1.0, progress)
        )
    }
}

class AnimatedQuadBezierPoint3D
(val path: QuadCurve) : AnimatedValue<Point3D>(Point3D.ZERO, Point3D.ZERO) {

    override fun animate(val1: Point3D, val2: Point3D, progress: Double, interpolator: Interpolator): Point3D {
        val p = FXGLMath.bezier(
                Point2D(path.startX, path.startY),
                Point2D(path.controlX, path.controlY),
                Point2D(path.endX, path.endY),
                interpolator.interpolate(0.0, 1.0, progress)
        )

        return Point3D(p.x, p.y, 0.0)
    }
}

class AnimatedCubicBezierPoint3D
(val path: CubicCurve) : AnimatedValue<Point3D>(Point3D.ZERO, Point3D.ZERO) {

    override fun animate(val1: Point3D, val2: Point3D, progress: Double, interpolator: Interpolator): Point3D {
        val p = FXGLMath.bezier(
                Point2D(path.startX, path.startY),
                Point2D(path.controlX1, path.controlY1),
                Point2D(path.controlX2, path.controlY2),
                Point2D(path.endX, path.endY),
                interpolator.interpolate(0.0, 1.0, progress)
        )

        return Point3D(p.x, p.y, 0.0)
    }
}

```

Design should be proposed first.

**Comment by GeorgeJoLo** [comment]
Hello @AlmasB !  
I've thought about it and want to propose a solution.
I've only changed one of the two pairs, and the other one can be managed in a similar fashion

```
class AnimatedQuadBezierPoint2D
(val path: QuadCurve) : AnimatedValue<Point2D>(Point2D.ZERO, Point2D.ZERO) {

    override fun animate(val1: Point2D, val2: Point2D, progress: Double, interpolator: Interpolator): Point2D {
        return FXGLMath.bezier(
                Point2D(path.startX, path.startY),
                Point2D(path.controlX, path.controlY),
                Point2D(path.endX, path.endY),
                interpolator.interpolate(0.0, 1.0, progress)
        )
    }
}


class AnimatedQuadBezierPoint3D
(val path: QuadCurve) : AnimatedValue<Point3D>(Point3D.ZERO, Point3D.ZERO) {

    override fun animate(val1: Point3D, val2: Point3D, progress: Double, interpolator: Interpolator): Point3D {
		val p = AnimatedQuadBezierPoint2D(QuadCurve).animate(Point2D(val1.x, val1.y), Point2D(val2.x, val2.y), progress, interpolator)

        return Point3D(p.x, p.y, 0.0)
    }
}
```

Would such a solution suffice? If so, I would like to complete the task with the PR

**Comment by AlmasB** [comment]
Hi,

Yes, I think this should work.

Just to give a bit of context to why we ended up with duplication: initially only 2D code was there since the animation system was 2D. Since recent commits, we now support 3D too (experimentally). To avoid having multiple animations systems, translation animation internally uses a Point3D representation, which allows both 2D and 3D animations.

1. Given Quad/Cubic Bezier curves are computed as 2D curves, I think we should hide the 3D one (add `internal class`) since it doesn't make sense to use it publicly.
2. `AnimatedQuadBezierPoint2D(path)` can be created once as a field, so we don't create it during each `animate()` call?

**Comment by GeorgeJoLo** [comment]
Hello again!

I expected that the duplication came like this.

1) Excuse me, but I'm not really sure I understand this one.
2) Completely agree. I'm going to make it like this.
3) I will add 2 more tests (one for each class).

If you explain me the first one, I think I can commit a PR asap.

**Comment by AlmasB** [comment]
Re: (1), just add 'internal' in front of the two 3D classes, so that they
cannot be used directly.

**Comment by GeorgeJoLo** [comment]
I realized that, and I will implement so. 
But, I would like to understand, why don't we want to access this classes from an other Module?
I'm thinking that, it's more meaningful to have the 2D classes as internal, because we can present 2D as a 3D object with z=0.

If you have enough time to explain me, I would really like to learn something!
Otherwise, I will just submit the PR now

**Comment by AlmasB** [comment]
`AnimatedQuadBezierPoint2D` is a well-defined concept of **a 2D bezier curve**. So it can be used as a 2D curve.

`AnimatedQuadBezierPoint3D` is **not a 3D curve**. It is only created on an ad-hoc basis to avoid duplicating a larger codebase inside the animation system. In other words, `AnimatedQuadBezierPoint3D` shouldn't exist, or at least it should be implemented as a fully interpolated 3D curve, not as a 2D curve. Hence, it is an implementation detail and should not be used in a public scope.

**Comment by GeorgeJoLo** [comment]
I've just made a Pull Request, I hope everything be fine (first time I commit one)
