### ISSUE TITLE
Wiki Page "Basic Game Example (FXGL 11)" outdated 

### ISSUE THREAD

**Issue by DieterMai** [AlmasB/FXGL#928]
I've did the tutorial Basic Game Example (FXGL 11) and discovered the following issues:

* In the complete source code there are some unused imports
* In the complete source code the deprecated API getGameState() is used. i think this should be replaced by FXGL.getWorldProperties()
* For FXGL to load assets from the game module, the game module has to open the resource packages. At least for me, this was not obvious and it took me more time to find out why then to do the actual tutorial.

**Comment by AlmasB** [comment]
Many thanks, I'll look into these

**Comment by AlmasB** [comment]
1) removed unused imports.
2) I couldn't find `getGameState()` in "Basic Game Example" tutorial, but did find it in "Adding images and sounds", updated.
3) I've added a link to modularity guide in images tutorial, as this is the first time assets are introduced.

Thanks for pointing these out.

**Comment by DieterMai** [comment]
Oh yes. "Adding images and sounds" was what i actually meant.

**Comment by AlmasB** [comment]
I believe this is now resolved. Feel free to let me know if there are any other outdated doc / links
