### ISSUE TITLE
Tutorial issues

### ISSUE THREAD

**Issue by DieterMai** [AlmasB/FXGL#930]
The tutorial has some issues that could be fixed:

Adding Collisions (FXGL 11)
- full source code unused import: import com.almasb.fxgl.dsl.FXGL

Simple Game Pong (FXGL 11)
- deprecated API is used: getUIFactory(). Use getUIFactoryService() instead.
- deprecated API is used: getGameState(). Use getWorldProperties() instead.

Simple Game Breakout (FXGL 11)
- deprecated API i used: from(). use entityBuilder(SpawnData) instead.

**Comment by AlmasB** [comment]
Many thanks, updated all 4 points
