### ISSUE TITLE
Allow seedable noise generation

### ISSUE THREAD

**Issue by AlmasB** [AlmasB/FXGL#935]
For reference: https://youtu.be/LWFzPP8ZbdU

**Comment by AlmasB** [comment]
@adambocco might be of interest?

**Comment by adambocco** [comment]
@AlmasB 

It looks like the three functions that should be seeded are `noise1D`, `noise2D`, and `noise3D`. 

I have played around with `noise2D` and get good effects from just randomizing the offset for the x and y inputs:

```java
  int inputSeed = 100000000;
  int seededNoiseOffset = FXGLMath.getRandom(inputSeed).nextInt();

  for (int i = 0; i < 50; i++) {
      for (int j = 0; j < 50; j++) {

//       double noise = FXGLMath.noise2D(0.1*i, 0.1*j);

          double noise = FXGLMath.noise2D(0.1 * (i+seededNoiseOffset), 0.1 * (j+seededNoiseOffset));

          FXGL.entityBuilder().at((i*10)+5, (j*10)+5).viewWithBBox(new Circle(noise*5, Color.BLACK)).buildAndAttach();

      }
  }
```

Here's an example of that:
![image](https://user-images.githubusercontent.com/54448507/112372557-543aac80-8cb6-11eb-9075-ba709089b7c4.png)


For `noise1D`, [the reference to the code it was adapted from](https://github.com/CRYTEK/CRYENGINE/blob/release/Code/CryEngine/CryCommon/CryMath/PNoise3.h) seeds a generator where FXGL currently just uses an unseeded `java.util.Random` object. 

Maybe we can use `FXGLMath.getRandom(seed)` here:
https://github.com/AlmasB/FXGL/blob/5a6065b3ec03a0a3da543212f281ece3098007e1/fxgl-core/src/main/kotlin/com/almasb/fxgl/core/math/PerlinNoiseGenerator.kt#L59-L61

Let me know if this is along the lines of what you were thinking.

Thanks!

**Comment by AlmasB** [comment]
I'm skimmed through the noise implementations we currently use: Perlin for 1D and Simplex for 2D/3D. It appears 2D/3D are already deterministic, as in for the same input x,y,(z) we get the same output. Can you confirm this?

If the above is correct, then we only need to modify 1D. In addition to the 1D function present, users should be able to call:

```
noise1D(seed, t)
```

so that for given `seed, t` the output is always the same. This, in turn, allows (re)generation of NPCs, terrains, level data, other gameplay features just from the same seed. For example,

```
class NPCComponent : Component {
      
       init {
                 var t = FXGLMath.getRandom(seed).nextDouble()
                
                some loop {  noise1D(seed, t); t += 0.016 }
        } 
}
```

Implementation-wise, I think you are right, we might be able to just pass the seed to Perlin generator. It would be good to add a unity test to confirm that for same input values, we get same output values.

**Comment by adambocco** [comment]
Yes, 2D and 3D are deterministic.

Looking at `PerlinNoiseGenerator.kt` for 1D, my first thought is to add a field for `seed` and change `setSeedAndReinitialize()` to take a seed which is called in `init`.

```java
 private const val seed = 1L

    init {
        setSeedAndReinitialize(seed)
    }
```

Change `setSeedAndReinitialize` to seed by creating a seeded `Random` object and matching how [the reference code](https://github.com/CRYTEK/CRYENGINE/blob/release/Code/CryEngine/CryCommon/CryMath/PNoise3.h) does it:

```java
            val random = FXGLMath.getRandom(seed)
            ...
            v.x = random.nextFloat() - 0.5f
            v.y = random.nextFloat() - 0.5f
```

Then to add an overload like this:

```java
    fun noise1D(t: Double, inputSeed: Long): Double {
        if (inputSeed != seed) {

            seed = inputSeed
            setSeedAndReinitialize(seed)
        }
        return noise1D(t)
    }
```

This has the effect of being deterministic as well. And yes I can add tests to confirm this to `FXGLMathTest`

Let me know what you think.
Thanks!

**Comment by AlmasB** [comment]
I think Perlin generator shouldn't be static. Then API becomes simple:

```
val perlin = Generator(seed)
perlin.noise1D(t)
```

The seed above should be a `val`, so each generator is immutable so to speak.

So, FXGLMath will have its own internal generator instance to work with existing `noise1D(t)`. As for new API, should we change it to:

```
getNoise1DGenerator(seed): Perlin generator
```

Then users can get their own instance and work with it as needed.

**Comment by adambocco** [comment]
I think giving the user the generator is the way to go. Currently it looks like `noise1D` calls `setSeedAndReinitialize` on every call and this change would only require that once . 

Should I keep direct access to `noise1D` for compatibility? There are a few occurences of it that might not be simple changes. Notably in **animation** -> `interpolators.kt` :
https://github.com/AlmasB/FXGL/blob/51933154414379c445a3610fdfa3fe6dba390046/fxgl-core/src/main/kotlin/com/almasb/fxgl/animation/Interpolators.kt#L300-L313

Other occurrences include `FXGLDefaultMenu.kt : 176`, `Viewport.kt : 390`, and `RandomMoveComponent.kt : 51`.

For this implementation, I was thinking change the definition for `PerlinNoiseGenerator.kt` and assigning a default seed (unless you want that a seed be necessary).

```java
class PerlinNoiseGenerator(inputSeed: Long = 0L) {
    private val seed = inputSeed;
```

Then include something like this to `FXGLMath`:

```java
    public static double noise1D(double t) {
        return new PerlinNoiseGenerator(0L).noise1D(t);
    }

    public static PerlinNoiseGenerator getNoise1DGenerator(long seed) {
        return new PerlinNoiseGenerator(seed);
    }
```

**Comment by AlmasB** [comment]
This is likely to be expensive, particularly in loops:

```
 public static double noise1D(double t) {
        return new PerlinNoiseGenerator(0L).noise1D(t);
    }
```

So we should have a `private static final generator` inside FXGLMath that would supply noise1D with current API. The 

```

public static PerlinNoiseGenerator getNoise1DGenerator(long seed) {
        return new PerlinNoiseGenerator(seed);
    }
```

looks fine.
