### ISSUE TITLE
Parent-Child-Relation of Entities: Remove Parent

### ISSUE THREAD

**Issue by hendrikebbers** [AlmasB/FXGL#952]
I created a parent child relation of `Entity` instances by providing parent child behaviour in `Component` classed.
When the parent entity is deleted I want to remove all child entities, too.

I'm using a `EntityWorldListener` to remove all children once the parent has been removed:
```
FXGL.getGameWorld().addWorldListener(new EntityWorldListener() {
            @Override
            public void onEntityAdded(final Entity entity) {}

            @Override
            public void onEntityRemoved(final Entity entity) {
                if (Objects.equals(entity, parent)) {
                    // FXGL.getGameWorld().removeEntity(child); //TODO FXGL -> Bug
                    FXGL.getGameWorld().removeWorldListener(this);
                }
            }
        });
```

When I uncomment the comment line in the code snippet I will receive the following exception:

```
java.lang.IllegalArgumentException: #iterator() cannot be used nested.
	at com.almasb.fxgl.core.collection.Array$ArrayIterator.hasNext(Array.java:719)
	at com.almasb.fxgl.entity.GameWorld.notifyEntityRemoved(GameWorld.kt:573)
	at com.almasb.fxgl.entity.GameWorld.removeEntity(GameWorld.kt:113)
```

**Comment by AlmasB** [comment]
Adding / removing entities during addition / removal of an entity is a design limitation to avoid concurrency issues. I think it's undocumented, so an action from this issue is on me to document this behaviour.

Workarounds depend on the use case, a common one:

Suppose you have a parent child component similar to this:

```
class ChildComponent extends Component {
     Entity parent;
}
```

Somewhere in your code `parent` gets removed from the world:

```
parent.removeFromWorld() or world.removeEntity(parent);
```

Before calling above code, how about:

```
world.getEntitiesByComponent(ChildComponent.class)
         .stream()
         .filter(e -> e.getComponent(ChildComponent.class).parent == parent)
         .forEach(e -> e.removeFromWorld());

// then
parent.removeFromWorld()
```

**Comment by hendrikebbers** [comment]
Sadly this won't work since the 'parent' can be removed based on several actions. A common fix for such use case would be the usage of a CopyOnWriteArrayList instead of using a ArrayList.

**Comment by AlmasB** [comment]
`CopyOnWriteArrayList` may introduce performance issues, though this would have to be tested.

How about:
```
class ChildComponent extends Component {
     Entity parent;

    onUpdate() {
         if (!parent.isActive()) {
              entity.removeFromWorld();
         }
    }
}
```

**Comment by hendrikebbers** [comment]
That Works :) THX
