### ISSUE TITLE
Inventory - allow setting max item quantity

### ISSUE THREAD

**Issue by AlmasB** [AlmasB/FXGL#953]
When calling `fun incrementQuantity(item: T, amount: Int): Boolean` we should check max item quantity limit and split the "stack" into a new item data object

**Comment by adambocco** [comment]
Hey again,

I'd like to work on this.

Thanks

**Comment by AlmasB** [comment]
Cool, please provide a short API design and your approach to implement it,
so we can discuss. For example, one immediate point is how we are planning
to store split stacks. I don't think current approach (i.e. data structure)
is sufficient because of duplicate keys.

**Comment by adambocco** [comment]
@AlmasB Sorry for the delay, I am in school and have been busy. I have given this some thought and I have two ideas.

1: - Add field maxStackQuantity to ItemData class
    - Change itemsData field in Inventory to hash map ( T -> ObservableList<ItemData<T>>
    - When incrementQuantity is called, it will traverse list and add on first stack that is not at capacity.

This would allow users to split stacks in the future.

2: Keep data structures and handle number of stacks in ItemData.
    - The new number of stacks and the "remainder stack" on  add/remove/increment

This option would be simpler but would only allow full stacks and one remainder stack (Ex. four stacks of 36 items:  10, 10, 10, 6 ) unless we added a data structure in ItemData to handle heterogenous stacks.


Let me know what you think!

Thanks,
Adam Bocco

**Comment by AlmasB** [comment]
The first option seems most consistent with the current approach. Plus the
new API should be compatible with the current one. The items() list is
essentially the keys of the new map. Though getItemData will be returning a
list I assume.

Feel free to go ahead with the implementation. It would probably be
sensible to start with a test, then implementation, then finally update the
sample with this new feature.

**Comment by AlmasB** [comment]
Closed by #973
