### ISSUE TITLE
Does FXGL use GRAALVM?

### ISSUE THREAD

**Issue by UltraBurstXD** [AlmasB/FXGL#954]
Hi,
I want to know if FXGL uses GRAALVM AOT to target mobile or embed systems. That because I think it's heavy (not well optimized) for low-end computer systems...

**Comment by AlmasB** [comment]
Hi, when targeting mobile, FXGL uses [Gluon Client](https://github.com/gluonhq/client-maven-plugin), which, in turn, is based on graalvm, so yes.

**Comment by UltraBurstXD** [comment]
I see...
