### ISSUE TITLE
Warn and ignore (instead of crashing) if an entity is being to the game world more than once

### ISSUE THREAD

**Issue by AlmasB** [AlmasB/FXGL#961]
This is at GameWorld.kt::L73 in fxgl-entity. Also we should do something similar for removeEntity L108 same file.

Tests will probably need updating too.

**Comment by oseph** [comment]
Perhaps in the EntityFactory documentation there could be mention that buildAndAttach should not be used in a call to `spawn()`? I think part of what confused me (as a n00b) is that in the current documentation I couldn't really tell the two methods apart.

**Comment by AlmasB** [comment]
Thanks for the feedback, I will update the documentation as part of this
issue

**Comment by AlmasB** [comment]
@adambocco could you take a look at this one please, when you've got time.

**Comment by adambocco** [comment]
@AlmasB 
Definitely!

It's a busy week for me but after Saturday I will have much more time.

Thanks!

**Comment by AlmasB** [comment]
Closed by #988
