### ISSUE TITLE
UI Editor support?

### ISSUE THREAD

**Issue by addstone** [AlmasB/FXGL#962]
UI Editor support?

**Comment by AlmasB** [comment]
Hi,

Could you elaborate on this please?

**Comment by addstone** [comment]
Something like this 
https://www.cocos.com/wp-content/uploads/2021/02/11.jpg

**Comment by AlmasB** [comment]
Ah I see, yes, there is a long-term plan for an editor: #362

**Comment by AlmasB** [comment]
Ah I see, yes, there is a long-term plan for an editor: #362

**Comment by AlmasB** [comment]
Initial functionality has been designed and described as #999 #1000 #1001 This issue is merged into them
