### ISSUE TITLE
In 11.13 event handler can not be removed anymore

### ISSUE THREAD

**Issue by hendrikebbers** [AlmasB/FXGL#964]
The following code worked as expected in `11.12`:

```
final EventType<T> eventType = ...
final EventHandler<? super T> eventHandler = ...

FXGL.getInput().addEventHandler(eventType, eventHandler);

//Now the event handler is registered and the program reacts on user interaction

FXGL.getInput().removeEventHandler(eventType, eventHandler);

//The handler has been removed and the program does not react on the user interaction anymore
```

With an update to `11.13` the `removeEventHandler` does not work anymore. The event handler is still registered.

**Comment by AlmasB** [comment]
[Add / remove event handler test](https://github.com/AlmasB/FXGL/blob/dev/fxgl-input/src/test/kotlin/com/almasb/fxgl/input/InputTest.kt#L510) is passing and I cannot seem to reproduce this manually either. Perhaps the issue is elsewhere? If there is a minimal reproducible example that would help too.

**Comment by AlmasB** [comment]
The behaviour might be related to the semantics of [this change](https://github.com/AlmasB/FXGL/commit/7073b14cc1ee8017e1b6648852f9f01f29493616). Both filter and handler capture the same event. However, if the same event is being fired into both filter _and_ handler, then it is a bug. I'll look into this later today.

**Comment by hendrikebbers** [comment]
I will try to provide a sample :)

**Comment by hendrikebbers** [comment]
Interesting behavior. While I can not reproduce the mentioned error with a first sample I found another problem.
Sample Code:
```
public class EventHandlerSample extends GameApplication {

    public static void main(final String[] args) {
        launch(args);
    }

    @Override
    protected void initSettings(final GameSettings settings) {
    }

    @Override
    protected void initGame() {
        final EventType<MouseEvent> eventType = MouseEvent.MOUSE_RELEASED;
        final EventHandler<MouseEvent> eventHandler = e -> System.out.println("ON EVENT");

        FXGL.getInput().addEventHandler(eventType, eventHandler);

        Executors.newSingleThreadExecutor().execute(() -> {
            try {
                Thread.sleep(10_000);
            } catch (final InterruptedException e) {
                e.printStackTrace();
            }
            System.out.println("PING");
            Platform.runLater(() -> FXGL.getInput().removeEventHandler(eventType, eventHandler));
        });
    }
}
```
Once the application started you will see a "ON EVENT" message for every mouse click (mouse release) on the canvas until the "PING" message is printed to the console. Afterwards no message will be shown for mouse clicks.

With 11.12 the behavior is as expected but with 11.13 the I see 2 "ON EVENT" messages for each mouse click...

**Comment by hendrikebbers** [comment]
And this sample shows the initially described problem. This happens only when handers are added / removed within a handler. The following code produces different output to the console when using it with 11.12 or 11.13:

```
public class EventHandlerSample extends GameApplication {

    private final EventHandler<MouseEvent> mouseReleasedEventHandler1 = new EventHandler<>() {
        @Override
        public void handle(final MouseEvent mouseEvent) {
            System.out.println("ON MOUSE RELEASED 1");
            mouseEvent.consume();
            FXGL.getInput().removeEventHandler(MouseEvent.MOUSE_RELEASED, this);
            FXGL.getInput().addEventHandler(MouseEvent.MOUSE_RELEASED, mouseReleasedEventHandler2);
        }
    };


    private final EventHandler<MouseEvent> mouseReleasedEventHandler2 = new EventHandler<>() {
        @Override
        public void handle(final MouseEvent mouseEvent) {
            System.out.println("ON MOUSE RELEASED 2");
            mouseEvent.consume();
            FXGL.getInput().removeEventHandler(MouseEvent.MOUSE_RELEASED, this);
            FXGL.getInput().addEventHandler(MouseEvent.MOUSE_RELEASED, mouseReleasedEventHandler1);
        }
    };

    public static void main(final String[] args) {
        launch(args);
    }

    @Override
    protected void initSettings(final GameSettings settings) {
    }

    @Override
    protected void initGame() {
        FXGL.getInput().addEventHandler(MouseEvent.MOUSE_RELEASED, mouseReleasedEventHandler1);
    }
}
```

**Comment by AlmasB** [comment]
Thanks for this. This is indeed a bug caused by the addition of event
filters in 11.13. The javafx scene fires both filters and handlers through
the same node in Input, causing event duplication.

I will turn these samples into integration tests (unit tests are passing
and won't work here since each module behaves correctly on its own) and
then fix the bug.

**Comment by AlmasB** [comment]
This should now be fixed, once the CI completes (5-10mins), to get the latest build, you can use this:
```
<dependencies>
    <dependency>
        <groupId>com.github.almasb</groupId>
        <artifactId>fxgl</artifactId>
        <version>dev-SNAPSHOT</version>
    </dependency>
</dependencies>

<repositories>
    <repository>
        <id>oss.sonatype.org-snapshot</id>
        <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    </repository>
</repositories>
```

Please can you check and let me know if everything works as expected?

**Comment by hendrikebbers** [comment]
Will do later. THX

**Comment by hendrikebbers** [comment]
Looks like the event handling issue is solved. But several JavaFX shapes are not visible anymore when using this version. I always add one javafx Group that implements the FXGL View interface to an entity. Looks like this groups are not visible anymore.

**Comment by hendrikebbers** [comment]
I will try to provide a sample

**Comment by hendrikebbers** [comment]
Looks like it is related to the Z index. My shapes are part of the scene but with the update they are all behind entities that have a lower Z-Index

**Comment by AlmasB** [comment]
The setZ() semantics changed in 11.13 since we now support 3D. Please use
setZIndex() to set z-index. Let me know if it works

**Comment by hendrikebbers** [comment]
yes, that solves the problem :)
