### ISSUE TITLE
TMXLevelLoader does not read tileset margin

### ISSUE THREAD

**Issue by dykstrom** [AlmasB/FXGL#969]
**Describe the bug**
The TMXLevelLoader does not read the "margin" attribute of the "tileset" element in the tmx file. This leads to tiles looking strange if the tileset does in fact have a margin. The margin attribute should be read like the spacing attribute.

**To Reproduce**
1. Create a tmx file that uses a tileset image that has margins.
2. Load tmx file in FXGL application.
3. See that tiles look strange, for example 1 pixel off if the margin is 1.

**Expected behavior**
The margin attribute is read from the file and stored in Tileset.margin.

**Runtime info(please complete the following information):**
 - Windows 10, but the error is OS independent.

**Comment by AlmasB** [comment]
Thanks, please can you include a minimal example tmx file (with everything it needs), so I can use it for development.

**Comment by dykstrom** [comment]
Hi, I just submitted a PR for this. :-)

**Comment by AlmasB** [comment]
Even better, many thanks, will check after CI.
