### ISSUE TITLE
Add DSL API

### ISSUE THREAD

**Issue by AlmasB** [AlmasB/FXGL#971]
Currently we have shortcuts for `.view(filename)`. We now also support loading from a URL.

Current API:
```
.view(getAssetLoader().loadTexture(getClass().getResource("...")))
```

- [x] New additional API:

```
.view(getClass().getResource("..."))
```

- [x] Same addition is needed for `.viewWithBBox()`
- [ ] FXGL.texture(URL)
- [ ] FXGL.image(URL)
- [ ] FXGL.play(URL)
- [ ] FXGL.loopBGM(URL)

**Comment by sormuras** [comment]
What about hiding the `getClass().getResource("...")` as well? For example, by providing a dedicated `viewResource("...")` variant that delegates to `.view(getClass().getResource("..."))`.

**Comment by AlmasB** [comment]
I thought about it, but not sure if getresource() call will succeed. I'll
check it

**Comment by sormuras** [comment]
https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/StackWalker.html to the rescue. ;-)
