### ISSUE TITLE
can i write my shader in javafx?

### ISSUE THREAD

**Issue by qq1053831109** [AlmasB/FXGL#975]
can i write my shader in javafx?

**Comment by AlmasB** [comment]
I don't think this is possible from public API, but @johanvos is better suited to answer this question.

**Comment by qq1053831109** [comment]
can i use webview read local file? i want use webgl for view 3d model it need shader!

**Comment by johanvos** [comment]
There is indeed no public JavaFX API for this, as not all platforms use GLSL, hence it would break the platform independency. It is possible though to create native components and then use e.g. the PixelBuffer API (which is public) to integrate between those components and your JavaFX app.

**Comment by qq1053831109** [comment]
> There is indeed no public JavaFX API for this, as not all platforms use GLSL, hence it would break the platform independency. It is possible though to create native components and then use e.g. the PixelBuffer API (which is public) to integrate between those components and your JavaFX app.

in some time，we just need make one exe for windows! so we dont need independency!
