### ISSUE TITLE
AssetLoader PropertyMap and Text should not be cached

### ISSUE THREAD

**Issue by AlmasB** [AlmasB/FXGL#977]
Instead, a new copy should be returned

Also check `List<String>` for text

**Comment by AlmasB** [comment]
@chengenzhao once the build is complete, please can you test that `List<String>` that is returned during the first and second calls do not affect each other if modified, as per #1233

**Comment by chengenzhao** [comment]
> @chengenzhao once the build is complete, please can you test that `List<String>` that is returned during the first and second calls do not affect each other if modified, as per #1233

it works
cheers
thx
