### ISSUE TITLE
Bind GameApplication width & height property to FXGLPane prefWidthProperty & prefHeightProperty

### ISSUE THREAD

**Issue by chengenzhao** [AlmasB/FXGL#978]
Hi:

We are experimenting embed mode of FXGL
and is it possible to bind width & height properties of GameApplication to pref width & height properties of FXGLPane ?
thus we could adjust fxgl pane when adjusting the scene size.

thx

**Comment by chengenzhao** [comment]
For example
if we adjust fxgl pane width & height
the game width & height will adjust accordingly 


var fxglRoot = GameApplication.embeddedLaunch(new MyGame());
fxglRoot.setPrefWidth(600);//the game width will adjust to 600 accordingly

**Comment by AlmasB** [comment]
Hi,

Thanks, yeah this is something I've been thinking about. My current plan is to have something like this:

```

var fxglPane = ...
fxglPane.setRenderWidth / Height

fxglPane.renderWidthProperty() / HeightProperty()
```

**Comment by AlmasB** [comment]
`renderWidth/Height` should now be present in `dev-SNAPSHOT`:
To get the latest build, you can use this:
```
<dependencies>
    <dependency>
        <groupId>com.github.almasb</groupId>
        <artifactId>fxgl</artifactId>
        <version>dev-SNAPSHOT</version>
    </dependency>
</dependencies>

<repositories>
    <repository>
        <id>oss.sonatype.org-snapshot</id>
        <url>http://oss.sonatype.org/content/repositories/snapshots</url>
    </repository>
</repositories>
```

The API is named to clearly delineate from the JavaFX API.

The behaviour remains consistent as compared to FXGL running normally in a Stage:

1. (with settings.isScaleAffectedOnResize set to false)

![Screenshot 2021-03-03 13 10 35](https://user-images.githubusercontent.com/3594742/109813655-8f9d0a80-7c25-11eb-8659-604ea91eab2e.png)

2. (with settings.isScaleAffectedOnResize set to true) (this is default behaviour)

![Screenshot 2021-03-03 13 30 33](https://user-images.githubusercontent.com/3594742/109813795-b65b4100-7c25-11eb-8f15-1fda463f936b.png)

In both cases, settings.width and height do not change

**Comment by chengenzhao** [comment]
wow
It works
Besides this function 
Is it possible to make settings width & height properties thus we could bind these properties to other JavaFX properties?

Thanks

**Comment by AlmasB** [comment]
You can use `settings.prefWidthProperty() / prefHeightProperty`. If the auto-scale is on, then these values are the same as settings.width / height and do not change. If the auto-scale is off, then these values change with stage.width / height, (or render width / height if running in embedded mode).

**Comment by chengenzhao** [comment]
Thanks 
but seems like there is no prefWidthProperty() in the game settings?

<img width="659" alt="Screen Shot 2021-03-04 at 5 25 56 PM" src="https://user-images.githubusercontent.com/5525436/109942008-b5520e80-7d0e-11eb-8ce7-9d7daaadce5c.png">

**Comment by AlmasB** [comment]
`FXGL.getSettings()` is the settings we need (after the engine is ready, e.g. in initGame()). The one inside `initSettings()` is the mutable one, only used during initialization.

**Comment by chengenzhao** [comment]
Found it
but it is read only property so we couldn't change the value by binding pref width property to other properties
Is it possible to change setting during the running of the game?

**Comment by AlmasB** [comment]
It cannot be changed since it reflects the following:

> If the auto-scale is on, then these values are the same as settings.width / height and do not change. If the auto-scale is off, then these values change with stage.width / height, (or render width / height if running in embedded mode).

If you are running in embedded mode _and_ with `settings.isScaleAffectedOnResize` set to false, then you can change render Width / Height of `FXGLPane`, which will change the read-only pref width / height accordingly.

If the above does not work for your use case, feel free to provide more info on what you are trying to achieve.

**Comment by chengenzhao** [comment]
It works, thanks
