### ISSUE TITLE
Wiki: update entry for Math Functions (FXGL 11)

### ISSUE THREAD

**Issue by AlmasB** [AlmasB/FXGL#984]
Link: https://github.com/AlmasB/FXGL/wiki/Math-Functions-%28FXGL-11%29

Update to include commonly used Math functions with code snippets and some explanations

**Comment by dltt83** [comment]
Had a look and would be happy to contribute and go through these math functions and edit the wiki for them.
Slightly new to github though and not entirely sure how to edit wiki pages?

**Comment by AlmasB** [comment]
Hi, see if there's an edit button on that page. If not, the easiest workflow for wiki entries is to add the text including full author name (or username if you prefer) here and I'll update the wiki.

**Comment by dltt83** [comment]
No edit button, but got the files for the wiki and will upload the page here when done.

**Comment by dltt83** [comment]
Done an entry for all the funcitons in the FXGlMath.java file
[Math-Functions-(FXGL-11).md](https://github.com/AlmasB/FXGL/files/6311203/Math-Functions-.FXGL-11.md)

**Comment by AlmasB** [comment]
Many thanks, I've removed `private static` constants since they cannot be accessed and they are for internal purposes only. I've fixed typos in `float` returning functions as they were missing `F` in method names.

Please check the updated page and let me know if you are happy with it. If so, I will close this issue.

**Comment by dltt83** [comment]
Everything looks good to me.
Happy to help

**Comment by AlmasB** [comment]
Awesome, thanks
