### ISSUE TITLE
Wrong mouse position for FXGLPane

### ISSUE THREAD

**Issue by hendrikebbers** [AlmasB/FXGL#997]
When integrating a FXGL application to another JavaFX application `FXGL.getInput().getMousePositionWorld()` returns the mouse position in the global stage and not within the FXGL world.

**Comment by AlmasB** [comment]
Thanks, both UI (FXGL UI space) and World (FXGL game space) positions should now be calculated from the FXGLPane's perspective. Please check when convenient.

```
<dependencies>
    <dependency>
        <groupId>com.github.almasb</groupId>
        <artifactId>fxgl</artifactId>
        <version>dev-SNAPSHOT</version>
    </dependency>
</dependencies>

<repositories>
    <repository>
        <id>oss.sonatype.org-snapshot</id>
        <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    </repository>
</repositories>
```

**Comment by hendrikebbers** [comment]
working :) THX
